### ISSUE TITLE
Release fix for Django 1.8 ou Pypi

### ISSUE THREAD

**Issue by ebertti** [summernote/django-summernote#100]

**Comment by lqez** [comment]
@ebertti is there any problem on django-summernote with Django 1.8 ?

**Comment by lqez** [comment]
If you're still in problem, please reopen this issue, thanks.

**Comment by ebertti** [comment]
I just requested to update the project on pypi :smile:

I see now is updated :+1:

thanks!

The right subject of this issue is:
Release fix for Django 1.8 on Pypi

Sorry for this error

**Comment by lqez** [comment]
P R O F I T
:dancer:
