### ISSUE TITLE
can't remove iframe from text in summernote-widget

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#101]
Looking in code view in the summernote widget, I have this within the text:

```<p>This is where you get to explore!&nbsp; Just try stuff.&nbsp; <strong>Use the rest of the class to just see what you can figure out!</strong> I know, it might be a bit frustrating, but I'll teach you more tomorrow =)<iframe style="width: 100%; height: calc(28px + 100%); border: 0px;" src="https://docs.google.com/presentation/d/1gdD2jjRk2b4WO-yrA_dg4Vl5U0POyory1ZhjVnHpzZs/embed" frameborder="0" height="150" width="300"></iframe></p>```

I can't delete that iframe.  If I save the changes it just reappears again. I can edit/save changes to anything else.

**Comment by lqez** [comment]
Yeah, this is a known issue.
If you want to apply modification on code view, then switch back to wysiwyg mode before you saving it.

**Comment by tylerecouture** [comment]
When I switch back to wysiwyg, the iframe comes back.

**Comment by lqez** [comment]
I tested your code. Please see https://www.youtube.com/watch?v=dBDQ8AdR6bE
But I failed to reproduce.

**Comment by lqez** [comment]
@tylerecouture Could you make a sample page for this problem?

**Comment by tylerecouture** [comment]
@Iqez  I can't reproduce the problem.  I suspect it was user error (me).  Thank you for this amazing widget!  If it happens again I will better note the steps and let you know.

**Comment by lqez** [comment]
@tylerecouture Gotcha. Thanks!
