### ISSUE TITLE
How to increase filesize limit and upload non-image files

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#102]
Hi! First, thank you for this awesome django app!

A couple questions I couldn't find in the docs:

1. How can I change the file size upload limit? I get the error: "Got an error uploading an image: File size exceeds the limit allowed and cannot be used"

2. Is there a way to upload arbitrary file types (i.e. non-image files?)

Thanks!

**Comment by lqez** [comment]
Thank you for using summernote.

1. You can set it on the limit of attachment in your `settings.py` See 
https://github.com/summernote/django-summernote/blob/master/django_summernote/settings.py#L76

2. Summernote only handles image files. But I have a plan for image gallery or file manager on `django-summernote` using plugin system of `summernote`.
