### ISSUE TITLE
Direction button.

### ISSUE THREAD

**Issue by ronysh** [summernote/django-summernote#105]
Thank you so much for creating a great editor. A direction button which sets the 'dir' attribute to 'rtl' and 'ltr' would be of great help for rtl Language users. Such languages include Hebrew and Arabic. Thank you again.

**Comment by lqez** [comment]
Got it. Yes, summernote supports ltr/rtr features,  but does not have a button for them. 
I'll make a PR for this on https://github.com/summernote/summernote and will leave the result here.
Thanks.

**Comment by lqez** [comment]
You can use https://github.com/virtser/summernote-rtl-plugin as a plugin. Thanks.

**Comment by AaronMcPoland** [comment]
I have tried to use the rtl plugin but get error of "can only concatenate tuple (not "set") to tuple"
