### ISSUE TITLE
Issue with django 1.9

### ISSUE THREAD

**Issue by peterchibunna** [summernote/django-summernote#108]
This plugin does not run on django 1.9. The error is on this line:
`from django.utils.importlib import import_module`

**Comment by Robinfr** [comment]
import_module was deprecated in 1.8 and removed in 1.9.

**Comment by lqez** [comment]
We already patched this issue by https://github.com/summernote/django-summernote/issues/84
And checkout https://travis-ci.org/summernote/django-summernote/builds/94915361, it passed django 1.9 tests. :)
