### ISSUE TITLE
unable to only pull in backquote and not all the style dropdown.

### ISSUE THREAD

**Issue by un33k** [summernote/django-summernote#113]
Is there a way to just pull in blockquote?
currently we have to use ['style', ['style']] to get blockquote which includes everything in the drop down.
If we use   styleTags: ['blockquote'], then we still get a dropdown for a single menu item.

**Comment by lqez** [comment]
This is an issue of summernote.
Please stay tuned on https://github.com/summernote/summernote/issues/1560
