### ISSUE TITLE
Add migrations for Attachements on Django>=1.9.x

### ISSUE THREAD

**Issue by shtalinberg** [summernote/django-summernote#115]
In  Django>=1.9   now no syncdb, only migrations, add it please

**Comment by lqez** [comment]
Is https://github.com/summernote/django-summernote/commit/fbb9abd9803ef198b9fc43966e1df6b59e386922 enough for migration?

**Comment by shtalinberg** [comment]
Yes, it should solve the problem

**Comment by shtalinberg** [comment]
you can make a release? To get included migration

**Comment by lqez** [comment]
Yeap, I'll release this on `0.8.x` shipped with summernote `0.8.x`. Summernote 0.8.0 still has some issues. So I'm waiting till it resolved.

**Comment by shtalinberg** [comment]
It is waiting for, to deliver client work.
I want to use this app to Django 1.9.2  in fresh project

**Comment by shtalinberg** [comment]
There Django solution. Perhaps it is useful to not wait 0.8.x 
`python manage.py migrate --run-syncdb`

**Comment by lqez** [comment]
I just released https://pypi.python.org/pypi/django-summernote/0.8.1
Thanks!
