### ISSUE TITLE
404 Error on summernote admin

### ISSUE THREAD

**Issue by sn0wle0pard** [summernote/django-summernote#124]
I install django-summernote 0.8.2., make migration and migrate.
add INSTALLED_APPS too.
In `admin.py`
`urlpatterns = [ ...
url(r'^summernote/', include('django_summernote.urls')),
...
]`

In admin.py
![image](https://cloud.githubusercontent.com/assets/16930958/13529938/19cdaaf6-e262-11e5-8e09-c3ce94cb6122.png)

But I saw 404 error at /summernote

**Comment by lqez** [comment]
You don't have to access to `/summernote` directly. Please see the model in your admin site.
