### ISSUE TITLE
not able to view the Image in  text box 

### ISSUE THREAD

**Issue by gjain0** [summernote/django-summernote#125]
When I upload Image using image button in editor(TextField) in django admin it doesn't update inline image in that text box. even after I click on save button and again reopen that entry in admin panel, still not able to view the image, however images are being stored in the desired path but it would have been nice if we can see image in text box itself.
I'm using django 1.9

**Comment by ajrbyers** [comment]
Encountering this issue as well with Django 1.9.

**Comment by springkjw** [comment]
I found the solution. Django print error 404 when I insert the image into textarea. It is problem with media url problem. you should verify media url. Put this code in urls.py

```
import django.conf import settings
import django.conf.urls.static import static

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

my django version is 1.9 and it works very well!

**Comment by BMXHashy** [comment]
I think I had nearly the same problem. I was able to upload them to 'Django-Summernote Attachments' via SummerNoteAdmin, but didn't seen anything.
Until I pressed on the Link at the Attachments. There I got an error that I cant read it. So I swapped the 'Media-Folders' to a apache-readable user/group and allowed to read them in the 'site-enabled' section. Now all works fine.

Dnn't know if this helps, but it's worth a try^^

**Comment by lqez** [comment]
These kind of errors were probably caused by two problems.
 - There was an compatibility problem on libraries, but fixed. Ref: https://github.com/summernote/django-summernote/pull/197
 - Mostly, `MEDIA_URL` didn't properly set.

Please reopen this issue when you're still in problem.
