### ISSUE TITLE
Not saving content while in code view?

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [summernote/django-summernote#127]
I'm using django-summernote 0.8.3 installed with mezzanine 4.1.0. After putting it in installed apps and adding a config to my settings.py, I just replaced all instances of admin.ModelAdmin in Mezzanine with SummernoteModelAdmin (there were only about 3 instances), and it seems to be working well.

I use summernote to add html in a good syntax-colored, tab-preserving environment for pages. I noticed that if I edit the HTML and then press "Save" before turning off Code View, that my changes don't get loaded. Is there an easy fix to this?

**Comment by lqez** [comment]
We're using `onBlur` to copy contents from summernote into exist textarea. But it doesn't be called while submitting form in codeview.

**Comment by geoffrey-eisenbarth** [comment]
Thanks for the info, I'll try to look into this when I can (although I'm
going on vacation tomorrow). I'd love to propose a pull request if I can
figure it out, although to be honest I haven't looked into the code very
much yet.

**Comment by lqez** [comment]
What a kind of you, @geoffrey-eisenbarth.
Please track https://github.com/summernote/summernote/issues/1529 before diving deep.

**Comment by lorencole** [comment]
I'm having this issue as well. Worked around it by adding an onblur to the codeview which turns it off when it loses focus. It's been working pretty well for us.
```javascript
$(element).next().on('focusout', ".note-codable", function() {
	if ($(element).summernote('codeview.isActivated')) {
		$(element).summernote('codeview.deactivate');
	}
});
```

**Comment by dorianamouroux** [comment]
My fix is to create a function `onsubmit` on my form : 
```html
    <form method="post" action="" onsubmit="return copyCodeIfCodeView()">[...]</form>
    [...]
    <script type="text/javascript">
        function copyCodeIfCodeView(e) {
            if ($summernote.summernote('codeview.isActivated')) {
                var context_textarea = window.document.getElementById('id_raw_content-textarea');
                context_textarea.value = $summernote.summernote('code')
            }
        }
    </script>
```
You get your textarea with this (the name of the id depends of your field, check your code source or inspect your page to get it)
`var context_textarea = window.document.getElementById('id_raw_content-textarea');`
my function will copy the content of the editor to the actual field if the editor is in code view mode.

**Comment by kjdion84** [comment]
+1

Based on the example above, this works for me:

	$('.note-codable').on('blur', function() {
		if ($('#summernote').summernote('codeview.isActivated')) {
			$('#summernote').summernote('codeview.deactivate');
		}
	});

**Comment by evtatarintsev** [comment]
I use summernote for django admin and override widget_inplace.html by adding this code to onInit callback.
It work for many widgets on page and for inlines.
```
$('.note-codable').on('blur', function() {
    $(this).closest('.note-editor').siblings('textarea').val(
            $(this).closest('.note-editor').siblings('div').summernote('code')
    );
});
```

**Comment by lqez** [comment]
I made a commit for this for both plain textarea and CodeMirror.
Ref: https://github.com/summernote/django-summernote/pull/221

**Comment by zschuessler** [comment]
This page is a top hit in Google for the problem, so I want to share that none of the code workarounds thus far solved my problem. If anyone is in the same boat, try this snippet:

``` 
$('.note-codable').on('blur', function() {
  var codeviewHtml        = $(this).val();
  var $summernoteTextarea = $(this).closest('.note-editor').siblings('textarea');

  $summernoteTextarea.val(codeviewHtml);
 });
```
The above worked on Summernote v0.8.8, using the "codeview" extension. It preserves all formatting as well!

**Comment by lqez** [comment]
Thank you @zschuessler, #221 gives exact same solution (actually better, it also supports CodeMirror case).

**Comment by ilcomp** [comment]
`var Editor = function (context) {`
...
`this.destroyCodeView = function () {
  context.invoke('codeview.destroy');
};`

And:
`$('form').submit(function(){
$(textarea).summernote('destroyCodeView');
});`

**Comment by jeremykenedy** [comment]
It's still not working as intended and we needed the patch by @zschuessler . This issue should be opened or patched.

**Comment by kadircakirpw** [comment]
$('.summerNoteCode').summernote({
		toolbar: [
			['view', ['fullscreen', 'codeview']]
		],
		callbacks: {
			onBlurCodeview: function() {
				let targetEditor = $(this);
				let target = targetEditor.siblings('div.note-editor').find('.note-codable');
				let codeviewHtml        = target.val();

				console.log(`Codeview area loses focus: ${codeviewHtml}`);
				targetEditor.val(codeviewHtml);
			}
		}
	});

**Comment by kadircakirpw** [comment]
This works for me;

```
$('.summerNoteCode').summernote({
		toolbar: [
			['view', ['fullscreen', 'codeview']]
		],
		callbacks: {
			onBlurCodeview: function() {
				let target = $(this).siblings('div.note-editor').find('.note-codable');
				let codeviewHtml        = target.val();

				console.log("Codeview area loses focus: " + codeviewHtml);
				$(this).val(codeviewHtml);
			}
		}
	});
```

**Comment by kadircakirpw** [comment]
Hi @jeremykenedy, you can try the code below this works for me;

```
$('.summerNoteCode').summernote({
	toolbar: [
		['view', ['fullscreen', 'codeview']]
	],
	callbacks: {
		onBlurCodeview: function() {
			let codeviewHtml = $(this).siblings('div.note-editor').find('.note-codable').val();
			console.log("Codeview area loses focus: " + codeviewHtml);
			$(this).val(codeviewHtml);
		}
	}
});
```

**Comment by kadircakirpw** [comment]
You can try the code below this works for me;

```
$('.summerNoteCode').summernote({
	toolbar: [
		['view', ['fullscreen', 'codeview']]
	],
	callbacks: {
		onBlurCodeview: function() {
			let codeviewHtml = $(this).siblings('div.note-editor').find('.note-codable').val();
			console.log("Codeview area loses focus: " + codeviewHtml);
			$(this).val(codeviewHtml);
		}
	}
});
```

**Comment by NVV-WebManager** [comment]
I'm using the codemirror plugin which mean that the code provided by @zschuessler wasn't working for me.  Here's what is working:

`callbacks: {
        onBlurCodeview: function () {
            let codeviewHtml = $(this).summernote('code');
            $(this).val(codeviewHtml);
        }
    }`

**Comment by NVV-WebManager** [comment]
If you happen to be using the codemirror plugin, this is the version that's working for me:

<pre><code>callbacks: {
    onBlurCodeview: function () {
        let codeviewHtml = $(this).summernote('code');
        $(this).val(codeviewHtml);
    }
}
</code></pre>

**Comment by Salvatos** [comment]
I'm on a platform that saves forms differently than what Summernote expects I think, and I don't control that platform, so while I could get @zschuessler's solution to print to console on blur, the event did not seem to fire in time when actually clicking the Save button or using the keyboard shortcut for it. So instead of messing with the form handling, I made a script that updates the master copy of the editor every time the code view content is changed, based on the API:

```js
$('#summernote').on('summernote.change.codeview', function(we, contents, $editable) {
    $('#summernote').val(contents);
});
```

I imagine this is a more resource-intensive way to handle the problem, perhaps noticeably so on very large entries, but it solved a long-standing annoyance for us and works well as an external user script.
