### ISSUE TITLE
problem with localization STATIC_URL is not passed to the iframe template

### ISSUE THREAD

**Issue by truhlik** [summernote/django-summernote#128]
Hi,

I have a problem with localization this awesome widget. 
using: `'body': SummernoteWidget(),`

There is a problem in the file `/templates/django_summernote/widget_iframe_editor.html`
in this line:
`$.getScript('{{ STATIC_URL }}django_summernote/lang/summernote-' + settings.lang + '.min.js');`

Because the template does not have access to the context, there is no variable STATIC_URL and the language file URL is broken.
Probably the STATIC_URL should be passed as a URL get parameter or something like that...? Not sure.

Thank you.

**Comment by lqez** [comment]
I think they were fixed.
Ref: https://github.com/summernote/django-summernote/issues/130, https://github.com/summernote/django-summernote/issues/170
