### ISSUE TITLE
How does one integrate plugins to django-summernote?

### ISSUE THREAD

**Issue by dep** [summernote/django-summernote#129]
For instance this one:

https://github.com/nilobarp/summernote-ext-emoji

**Comment by lqez** [comment]
You can add custom css/js files in your `django-summernote` settings via `css` / `js`.
At your `settings.py`;
```
SUMMERNOTE_CONFIG = {
    'toolbar': [
        # more toolbar items here ...
        ['misc', ['emoji']],
    ],
    'js': (  # This is for SummernoteWidget
        static_url('some/path/to/summernote-ext-emoji.js'),
    ),
    'js_for_inplace': (  # Also for SummernoteInplaceWidget
        static_url('some/path/to/summernote-ext-emoji.js'),
    ),
}
```

**Comment by dep** [comment]
Thanks!

**Comment by lqez** [comment]
@dep if this works well, then please close this issue :)

**Comment by StevenMapes** [comment]
Is their a minimum version for this as it just does not work for me, no request is made for the external files but I am testing against version 0.6.6.

**Comment by lqez** [comment]
@StevenMapes Sorry for inconvenience. `settings` of external files had been changed several times. Please use latest version or see changes on https://github.com/summernote/django-summernote/commit/03e3ac4594dce5585607b623d7a1b279bdc55187#diff-04c6e90faac2675aa89e2176d2eec7d8 .

**Comment by gdvalderrama** [comment]
I can't get this to work.
Is there anything else that needs to be done other than adding the plugin to the toolbar, setting `css` and `js` in the settings?

I'm using v0.8.5

**Comment by lqez** [comment]
@gdvalderrama Please refer [current settings](https://github.com/summernote/django-summernote/blob/f133167e58c02d76c6ea2a7bf373bd6ea51aa625/django_summernote/settings.py#L140-L144). It uses different options for `SummernoteWidget` and `SummernoteInplaceWidget`.

**Comment by gdvalderrama** [comment]
@lqez yes, thank you.
I've already tried both though, with no luck.

**Comment by pincoin** [comment]
@gdvalderrama ,

Recently, we added the subdirectory `djs_playground` which is Django sandbox project for testing.

https://github.com/summernote/django-summernote/blob/master/djs_playground/settings.py#L124-L139

You may refere the code as linked above. If you still encounter the issue, let us know your settings. 

Otherwise, we would like you to show the same error with our `djs_playground` subproject.

Thank you.

**Comment by SanjoyPator1** [comment]
> @gdvalderrama ,
> 
> Recently, we added the subdirectory `djs_playground` which is Django sandbox project for testing.
> 
> https://github.com/summernote/django-summernote/blob/master/djs_playground/settings.py#L124-L139
> 
> You may refere the code as linked above. If you still encounter the issue, let us know your settings.
> 
> Otherwise, we would like you to show the same error with our `djs_playground` subproject.
> 
> Thank you.

Hi I am trying to implement the print option in summernote in my django project. But it is showing some error in chrome browser developer tools as:
Refused to execute script from 'http://localhost:8000/summernote/editor/id_body/static/summernote-ext-print.js/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by SanjoyPator1** [comment]
> You can add custom css/js files in your `django-summernote` settings via `css` / `js`.
> At your `settings.py`;
> 
> ```
> SUMMERNOTE_CONFIG = {
>     'toolbar': [
>         # more toolbar items here ...
>         ['misc', ['emoji']],
>     ],
>     'js': (  # This is for SummernoteWidget
>         static_url('some/path/to/summernote-ext-emoji.js'),
>     ),
>     'js_for_inplace': (  # Also for SummernoteInplaceWidget
>         static_url('some/path/to/summernote-ext-emoji.js'),
>     ),
> }
> ```

I tried what you have said but in the browser it is showing this error:
Refused to execute script from 'http://localhost:8000/summernote/editor/id_body/static/summernote-ext-print.js/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
