### ISSUE TITLE
i`d like to save attached image in another model in django

### ISSUE THREAD

**Issue by manducku** [summernote/django-summernote#131]
first of all, Thank you for making a good project.

as the title, i want to save image separated from the text in summernote.
so i look at the code of summernote, i can`t not find how to save the image.

and also in my form, i check the request.FILE.getlist('files'). there is no image 

can you teach me how to access summernote attachment model in my view?

**Comment by lqez** [comment]
I got your point.
But I intended to make django-summernote without dependencies of model / instances.
When we create a new instance, it doesn't have a primary key (id). Then we can't store the relation between attachment files and new instance. If you want to make it as `ManyToMany` or `ForeignKey` style, you have to save the new instance first and make relationships later. 

And finally, you can customize your own `onFileUpload` callback.
