### ISSUE TITLE
problem with attaching image, link button on SummernoteInplaceWidget

### ISSUE THREAD

**Issue by manducku** [summernote/django-summernote#135]
now, I'am using Django Crispy from. 

when i click attaching image button or link button, it make screen darken.
and file also not upload to my storage.
but file upload works well when drop the image in post

<img width="839" alt="2016-04-26 11 02 16" src="https://cloud.githubusercontent.com/assets/3426196/14821565/3020c89c-0c06-11e6-9288-ff71d453df93.png">

in SummernoteWidget with iframe, there is no problem,  
 it works well.

is there conflict with my bootstrap theme?

if need further information about it, 
please tell me.

thank you

**Comment by lqez** [comment]
Maybe or maybe not. Sorry for late answering. Please feel free to register a new issue if you still use & have these problems.
