### ISSUE TITLE
Config option restructuring in 0.8.5 breaks inplace widget and more

### ISSUE THREAD

**Issue by nidico** [summernote/django-summernote#136]
Release 0.8.5 or more specifically commit 03e3ac4594dce5585607b623d7a1b279bdc55187 broke the inplace widget as jquery isn't loaded anymore.

This is due to the restructuring of the various css and js config options, particularly of missing jquery which was previously part of `external_js`, which [was removed](https://github.com/summernote/django-summernote/commit/03e3ac4594dce5585607b623d7a1b279bdc55187#diff-deb4330b950e97559e4865d53b8697beL119) in the mentioned commit.

This could be fixed by adding `summernote_config['default_js']` and friends instead.

However, the whole commit looks pretty broken to me:
- README.md still refers to `(css|js)_for_iframe`, `(internal|external)_(css|js)` which don't exist anymore, but misses the new `(css|js)`.
- Why are the inline options suffixed with `_inline` while the the iframe options are just called `js` / `css`? Or is `js` / `css` also intended to be included in the inline widget (see above)?
- How is the `default_` mechanism supposed to work? Previously I could override options; the introduction of the `default_` options and the use of only non-default options in the README makes it impossible to _not_ load a default option.

Shuffling around config options is not nice for users and should at least be mentioned in the CHANGES.

**Comment by lqez** [comment]
Really sorry for that, but the structure of settings could be changed without backward compatibilities. We will update the docs and README for them. Thanks.
