### ISSUE TITLE
README makes use of undocumented function static_url

### ISSUE THREAD

**Issue by nidico** [summernote/django-summernote#137]
4e6f49c910492ff66cefcc763ce5d1dcc1d826f6 and 03e3ac4594dce5585607b623d7a1b279bdc55187 introduced the use of the `static_url` function in `SUMMERNOTE_CONFIG` sample settings in the README.

However this function is only defined [locally](https://github.com/summernote/django-summernote/blob/03e3ac4594dce5585607b623d7a1b279bdc55187/django_summernote/settings.py#L37) and can not be used in the normal django settings.

Of course this isn't much of an issue, but it will confuse users.

**Comment by stvkas** [comment]
Sure confused me.

**Comment by lqez** [comment]
Sorry for inconvenient. We removed it.
