### ISSUE TITLE
Is it possible to disable editing for some pages?

### ISSUE THREAD

**Issue by avinassh** [summernote/django-summernote#140]
For some pages, I want to disable editing of the text area or restrict it. Is it possible? 

~~As of now I am manually passing `$('#summernote').summernote('disable');` to templates. But is there any documented or recommended way?~~ Looks like it doesn't work :(

**Comment by lqez** [comment]
You have to pick a right element when you disable it.
Like `$("#id_foobar").summernote("disable");`
XRef: https://summernote.org/deep-dive/#disable-enable
