### ISSUE TITLE
Impossible to override summernote settings

### ISSUE THREAD

**Issue by dorianamouroux** [summernote/django-summernote#141]
I don't want to give the user the opportunity to use class attribute in his HTML, it's pretty easy as only the table element uses classes (from summernote, it will take the settings 'tableClassName', if empty, it won't add class, perfect).
So in my `SUMMERNOTE_CONFIG`, I added `'tableClassName': '',`.
It doesn't work, because when django-summernote will create the settings array for Javascript, it will expect settings value to be positive (not None, not False, not empty string, not 0).

Here's the small fix I did (it's hard to be reusable though): 

``` python
class MySummernoteInplaceWidget(SummernoteInplaceWidget):

    def template_contexts(self):
        settings_editor = super().template_contexts()
        settings_editor['tableClassName'] = ''
        return settings_editor
```

and I use this custom widget and it works

**Comment by lqez** [comment]
Could you examine https://github.com/summernote/django-summernote/pull/198 for this issue and test it with the latest release? And please reopen again if you stuck in the same problem.
