### ISSUE TITLE
Adding new tags?

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#143]
Is it possible to add new tags?  For example, I'm using bootstrap and would like to be able to use the `kbd`, `code`, and `samp` tags.

Seems like it should be as easy as an `i` or `b`, since it's just wrapping the selected text in the tags?

Here's an enhancement request (:
In the config, ability to add an arbitrary tag, along with an icon (say font-awesome or glyph-icon)

For now though, would this be hard for me to do manually?  Thhank you!

**Comment by lqez** [comment]
I think this could be done by developing a new summenote plugin and add it.
Check out summernote plugins : https://github.com/summernote/awesome-summernote/

**Comment by tylerecouture** [comment]
Thanks. I didn't know there were plug ins! So many new options now... =)

**Comment by tylerecouture** [comment]
Thanks for inspiring me to create this plugin!  
https://github.com/tylerecouture/summernote-add-text-tags

**Comment by pincoin** [comment]
@tylerecouture 

Thank you for your collaboration. We will introduce your plugin at [awesome-summernote](https://github.com/summernote/awesome-summernote/).
