### ISSUE TITLE
SummernoteInplaceWidget doesn't work

### ISSUE THREAD

**Issue by pshulga-softheme** [summernote/django-summernote#144]
Hi, I want use  the SummernoteInplaceWidget but I can't use this becouse I get error from browser "Uncaught TypeError: $summernote.summernote is not a function"

```
class ReportForm(forms.Form):
    title_report = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Title report"}))
    text = forms.CharField(widget=SummernoteInplaceWidget())
```

If I use basic class all good

```
class ReportForm(forms.Form):
    title_report = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Title report"}))
    text = forms.CharField(widget=SummernoteWidget())
```

**Comment by pincoin** [comment]
As @cdrice  mentioned, jQuery and summernote libraries must be placed at page head for `SummernoteInplaceWidget`, 

We also feel that it needs to be improved, but it's really hard to implement it due to the design of Django custom widget.

Thank you for your question.
