### ISSUE TITLE
django right-side bar loop

### ISSUE THREAD

**Issue by nvcken** [summernote/django-summernote#145]
<img width="827" alt="screen shot 2016-07-05 at 3 49 56 pm" src="https://cloud.githubusercontent.com/assets/3489866/16579244/02644d44-42c9-11e6-94e0-516f6283c5bd.png">

**Comment by lqez** [comment]
You're using `SummernoteWidget` which uses `iframe`. If you avoid this;
 - Use `SummernoteInplaceWidget` - it doesn't use `iframe`. But it may be affected by / affect styles on your page.
 - Or, customize `SHOW_TOOLBAR_CALLBACK` of django-debug-toolbar to hide toolbar for summernote url.
