### ISSUE TITLE
No icons appearing

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#147]
I just upgraded django-summernote from 0.6.8 to 0.8.5 (upgrade required due to upgrade to Django 1.9).

After the upgrade, I can no longer see any icons in my production environment.

The static files have been collected, and I can get to them via web (e.g. summernote.css).  I am using font-awesome all over my project and its working great, but I can't figure out where dj-summernote is trying to get them from.  I don't see font-awesome referenced anywhere except in the html itself, so I don't know where to start troubleshooting!

Any ideas?

**Comment by lqez** [comment]
summernote uses its own static font, not font-awesome. Please check the status of serving and deploying static files.
XRef: https://github.com/summernote/summernote/tree/develop/dist/font

**Comment by gdvalderrama** [comment]
@lqez the link provided is broken

**Comment by lqez** [comment]
Sorry for inconvenient. https://github.com/summernote/summernote/tree/master/dist/font

**Comment by Snailedlt** [comment]
> Sorry for inconvenient. https://github.com/summernote/summernote/tree/master/dist/font

Also broken

**Comment by gdvalderrama** [comment]
master branch is now main, which is why the link failed (the default branch must be develop, where it redirects to)

you can find it at https://github.com/summernote/summernote/tree/main/dist/font @Snailedlt

**Comment by Snailedlt** [comment]
Thanks a bunch!
