### ISSUE TITLE
Save pictures in another files

### ISSUE THREAD

**Issue by Ladeia** [summernote/django-summernote#148]
Hello,

Maybe its a dumb question, but I dont see it in anywhere...
I can save my upload pictures in another location? Is perfect if I can do it in folder "/USER_NAME/date/image_hash.extension".

And in list images, I can filter for logged user...

**Comment by lqez** [comment]
You can customize it by changing `attachement_upload_to` function as you like.
Ref: https://github.com/summernote/django-summernote/blob/d32835ad1aa37ec6ba5b354828457fd6db188f3e/django_summernote/settings.py#L103
