### ISSUE TITLE
CSRF Token cookie name

### ISSUE THREAD

**Issue by plopidou** [summernote/django-summernote#149]
Hey there!

Just a quick change request, in case it was not done/planned.

line 8 of: https://github.com/summernote/django-summernote/blob/master/django_summernote/templates/django_summernote/widget_inplace.html

`var csrftoken = getCookie('csrftoken');`

Hard-coding of the cookie name can cause problems with the django setting:

`CSRF_COOKIE_NAME = 'my_csrf_cookie_name'`

[ see https://docs.djangoproject.com/en/1.9/ref/settings/#csrf-cookie-name ]

It would be best if that cookie name was taken from the settings, instead of hardcoded.

Cheers and congratulations on a great product!

PS: hopefully this will prevent someone to spend hour looking at @csrf_exempt, setenforce, security contexts, chmod and chown and various conf files all over the place :)

Also, somewhere in the doc should be the advice not to do this:

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True

As this would cause `var csrftoken = getCookie('csrftoken');` to fail.

**Comment by lqez** [comment]
Totally agreed. Thanks!

**Comment by lqez** [comment]
Closed by #155
