### ISSUE TITLE
Need helps about how to use it.

### ISSUE THREAD

**Issue by rightx2** [summernote/django-summernote#154]
My model : 

```
class Post(models.Model):

    objects = PostManager()

    author = models.ForeignKey(User)
    title = models.CharField(max_length=120)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
```

My forms (modelform):

```
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content, 'image')
        widgets = {
            'content': SummernoteInplaceWidget(),
        }
```

But it doesn't show summernote in template. What's wrong with my code?

**Comment by alexadkins** [comment]
+1

**Comment by msert29** [comment]
Although this post is old, for future references, try outputting it using the |safe tag within your template.

**Comment by pincoin** [comment]
README.md file is now updated as shown below:

In `forms`,

    from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

    # Apply summernote to specific fields.
    class SomeForm(forms.Form):
        foo = forms.CharField(widget=SummernoteWidget())  # instead of forms.Textarea

    # If you don't like <iframe>, then use inplace widget
    # Or if you're using django-crispy-forms, please use this.
    class AnotherForm(forms.Form):
        bar = forms.CharField(widget=SummernoteInplaceWidget())

And for `ModelForm`,

    class FormFromSomeModel(forms.ModelForm):
        class Meta:
            model = SomeModel
            widgets = {
                'foo': SummernoteWidget(),
                'bar': SummernoteInplaceWidget(),
            }

Last, please don't forget to use `safe` templatetag while displaying in templates.

    {{ foobar|safe }}


This question will be closed. Thank you for your question.
