### ISSUE TITLE
Character count on HTML ?

### ISSUE THREAD

**Issue by RCambier** [summernote/django-summernote#160]
Hi,

Is it somehow possible to count the characters on the html text only (what the user sees in the not-code view) instead of counting the count of characters inside the code view ?

This way, the server validation would be adequate to what the user sees he inputs in the text field.

Thanks !

**Comment by lqez** [comment]
You can count it by calling `$(editable).text().length`
XRef: https://github.com/summernote/summernote/pull/2554
