### ISSUE TITLE
Overriding shortcuts

### ISSUE THREAD

**Issue by stvkas** [summernote/django-summernote#164]
Hello,

I'm having some trouble finalizing an enhancement in my own fork. I want to update shortcuts with keyMap options, as in [issue 104](https://github.com/summernote/summernote/issues/104). I've added `keyMap` to the `__summernote_options__` list in my [widgets.py](https://github.com/stvkas/django-summernote/commit/1d11df15beb1d431b60419c8fb52593603bb1cd9). In the browser console, `window.parent.settings_id_conent.keyMap` has the `keyMap` data; however, I get a TypeError:

> Uncaught TypeError: Cannot read property 'replace' of undefined                    summernote.min.js:3

When I pretty print the minified text, it looks to do line 2785. It turns out `b` is undefined.

![screen shot 2016-10-21 at 4 33 21 pm](https://cloud.githubusercontent.com/assets/2933702/19614474/c78060b6-97b2-11e6-9ddb-c91cec927512.png)

I've tried loading the summernote JavaScript from a different source and it works fine, e.g. replace `static_url('django_summernote/summernote.min.js)` with `static_url('//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.min.js')` in settings.py.

I'd like to make a pull request with this enhancement. Why would the default copy of summernote throw that error?

**Comment by lqez** [comment]
Could you retry this one with the latest release? I've added `summernote` section in `SUMMERNOTE_CONFIG` for custom settings of summernote itself.

**Comment by lqez** [comment]
Sorry, the PR with custom settings is not still merged yet. https://github.com/summernote/django-summernote/pull/225 Just wait for a moment.

**Comment by lqez** [comment]
#225 was merged. I'm closing this.

**Comment by dfrankow** [comment]
Thanks for this, very helpful.
