### ISSUE TITLE
Unexpected syntax error with USE_THOUSAND_SEPARATOR

### ISSUE THREAD

**Issue by truhlik** [summernote/django-summernote#166]
Hi,

if you have: `USE_THOUSAND_SEPARATOR=True` and uploaded file is bigger then 1000B then template `upload_attachment.json` render file size with separator and **Unexpected syntax error** cause that the image is not shown in the summernote widget.

I fixed the issue with:
```
{% load l10n %}
{% localize off %}
...
{% endlocalize %}
```

**Comment by lqez** [comment]
Thanks!

**Comment by lqez** [comment]
Ref: https://github.com/summernote/django-summernote/commit/c0588c996b9aa3eae56eefad5dd8f16a39395b6f
