### ISSUE TITLE
Forbidden <CSRF token missing or incorrect>:/ summernote/load_attachment/

### ISSUE THREAD

**Issue by predragfalcic** [summernote/django-summernote#167]
Hi I am getting this error when I try to load an image in the editor when I am using SummernoteInplaceWidget. 
The full error is: 

Forbidden <CSRF token missing or incorrect>:/ summernote/load_attachment/
POST /summernote/upload_attachment/ HTTP/1.1 403 2502

When I use SummernoteWidget it works fine, but I can not resize the editor, but with SummernoteInplaceWidget I can resize it, but when I upload an image it show that error in console, and the image is not shown in the editor.

I just want to say, that my header_photo is a ImageField and it works perfect, as SummernoteWidget does.

my forms.py file:
```
class CreatePostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'status', 'header_photo', 'body')

		widgets = {
            #'body': SummernoteWidget(),
            'body': SummernoteInplaceWidget(),
        }
```
body is:
```
body = models.CharField(max_length=5000, 
                               blank=True, 
                               unique=False, 
                               null=True)
```
settings.py file:
```
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    #'/var/www/static/',
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static_cdn')

MEDIA_URL = '/media1/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media_cdn')


SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode
    'iframe': False,  # or set False to use SummernoteInplaceWidget - no iframe mode

    # Using Summernote Air-mode
    'airMode': False,

    # Use native HTML tags (`<b>`, `<i>`, ...) instead of style attributes
    # (Firefox, Chrome only)
    'styleWithTags': True,

    # Set text direction : 'left to right' is default.
    'direction': 'ltr',

    # Change editor size
    'width': '100%',

    # Max length
    'max-length': 5000,
}
```
and my form is:
```
<form class="form-horizontal" method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="text-center" style="margin-bottom: 20px">
                            <h2 style="color: #c1b4b4;">Upload the header picture for your post</h2>
                            {% render_field post_form.header_photo class="form-control" style="background-color: #E8E8E8" %}
                        </div>

                        <div class="form-inline">
                            <div class="form-group" style="margin-bottom: 20px;">
                                {% render_field post_form.title class="form-control" placeholder="Blog title" %}
                                {% render_field post_form.status class="form-control" %}
                            </div>
                        </div>
                        {{ post_form.media }}
                        {{ post_form.body }}
                        <hr>
                        <div class="control-group">
                            <!-- Button -->
                            <div class="controls" style="margin-bottom: 20px">
                                <button class="btn btn-lg btn-success" style="min-width: 300px">Save</button>
                            </div>
                        </div>
                        {% if redirect_field_value %}
                        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                        {% endif %}
                     </fieldset>
                </form>
```
If you need I can upload any of my files. Thank you for your help

**Comment by lqez** [comment]
`SummernoteInplaceWiget` uses a cookie for getting csrf token. See https://github.com/summernote/django-summernote/blob/master/django_summernote/templates/django_summernote/widget_inplace.html#L8

If you have no problem on `SummernoteWidget` but on `SummernoteInplaceWidget`, then it must not be a problem caused by other settings. Please check out the cookie things.

**Comment by predragfalcic** [comment]
Thank you for your answer, I will see if I can solve my problem now.

**Comment by yinkanghong** [comment]
Did you solve this problem now? I have the same one.

**Comment by yinkanghong** [comment]
I find he forget to send a parameter named CSRF_COOKIE_NAME to widget_inplace.html
`var csrftoken = getCookie('{{ CSRF_COOKIE_NAME }}');` I add it in widgets.py->SummernoteInplaceWidget->render->Context as below:
`'CSRF_COOKIE_NAME': 'csrftoken' `
so i can upload the image to my server,but the js don't call success method when the upload_attachment.json is send back,my js is poor,look forward someone will debug this.If someone has solve this promble,please let me,thank you very much.

**Comment by yinkanghong** [comment]
Finally I solved this problem by change django_summernote/templates/django_summernote/widget_inplace.html line 8 from `var csrftoken = getCookie('{{ CSRF_COOKIE_NAME }}');` to `var csrftoken = getCookie('csrftoken');`

**Comment by tobiasmcnulty** [comment]
I can confirm `var csrftoken = getCookie('');` shows up in my source too (thereby breaking uploads), so something about getCookie('{{ CSRF_COOKIE_NAME }}') is not working...will continue to investigate.

**Comment by tobiasmcnulty** [comment]
Oh. The current pip-installable version does not pass `CSRF_COOKIE_NAME` in the context, but current master does, courtesy of #168.

I am assuming this ticket is a duplicate of #165.

It would be great to get a new release on PyPI with the changes from #168, as the inline widget w/uploads seems unusable otherwise (?).

**Comment by lqez** [comment]
I released v0.8.7 with latest patches. This must be fixed. Please reopen this if you still in a problem.

**Comment by jacopsd** [comment]
I see the same problem with django 1.8.16 and the new django-summernote 0.8.7

Using inplacewidget to avoid IFRAME. On my development server, things work fine. 
On production server this issue arises:
When uploading a picture, CSRF error is returned.
Other uploads work fine (e.g. avatar pictures)

In the script source (of the popup) I see:
```
$(function() {
    var id_email_template_textarea = window.document.getElementById('id_email_template-textarea');
    var id_email_template_src = window.document.getElementById('id_email_template');
    var id_email_template_settings = {"lang": "nl-NL", "url": {"upload_attachment": "/summernote/upload_attachment/"}, "height": "600", "toolbar": [["undo_redo", ["undo", "redo"]], ["style", ["style"]], ["style", ["bold", "italic", "underline", "clear"]], ["font", ["fontname", "fontsize"]], ["color", ["color"]], ["para", ["ul", "ol", "paragraph"]], ["height", ["height"]], ["insert", ["link"]], ["picture", ["picture"]], ["table", ["table"]], ["hr", ["hr"]], ["help", ["help"]]], "width": "100%"};
    var csrftoken = getCookie('csrftoken');

```

So that seems correct.

Settings:
```
SUMMERNOTE_CONFIG = {
    'iframe': False,
    'width': '100%',
    'height': '600',
    'toolbar': [
        ['undo_redo', ['undo', 'redo']],
        etc
    ],
}

```

Any clue?

PS: Great django app by the way :) Thank you.

**Comment by lqez** [comment]
@jacopsd Thank you for reporting & reopening.

**Comment by lqez** [comment]
@jacopsd It's very weird. `v0.8.7` doesn't assume the cookie name as `csrftoken`. (as same as default) It pulls out the cookie name from `Context`.
See: https://github.com/summernote/django-summernote/blob/master/django_summernote/templates/django_summernote/widget_inplace.html#L8

Please checkout your production code or try to hard refresh them.

**Comment by jacopsd** [comment]
No success yet.

Re-read the documentation, wondering what this means:

- "{{ foobar|safe }}"     -> should this be placed where the form is rendered? 
- "!!!Be sure to put {{ form.media }} in template before initiate summernote"     -> only for inplacewidget? What if I use crispyforms?

Thank you for your help

**Comment by boryskuczkowski** [comment]
> * "{{ foobar|safe }}"     -> should this be placed where the form is rendered?

this should go to html template
> * "!!!Be sure to put {{ form.media }} in template before initiate summernote"     -> only for inplacewidget? What if I use crispyforms?

Yeah, this goes where the form is, I use crispy forms and I put {{ form.media }} in-between
 `        {% block jquery %}
            {{ form.media }}
        {% endblock %}
` 
and
 `    {% block jquery %}{% endblock %}` 
at the very bottom of the `<body>` of base.html, this makes sure jquery loads before it executes the script.
Also check that you are using "full version" of jquery from cdn or locally, I struggled for days searching for answer as I couldn't get mine to work by any means, turns out I was using slim version of jquery which didn't include necessary files :/

**Comment by nad2000** [comment]
I ran into this issue switching to _SummernoteInplaceWidget_ with crispy forms.
The passed **csrfmiddlewaretoken** is set to **null** when I tried to upload a file.

(django-summernote==0.8.11)
