### ISSUE TITLE
SummernoteInplaceWidget: $summernote.summernote is not a function

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#171]
If I set my widget to `SummernoteWidget` it works fine, but I'm using crispyforms and don't want an iframe, so trying to get `SummernoteInplaceWidget` to work.

When I change to `SummernoteInplaceWidget`, it doesn't render and I get this error: 

`$summernote.summernote is not a function`

Here is what my `<head>` looks like after including jquery and loading {{form.media}}, and I've confirmed that all the js links work:

```
  <!-- required at top for django-summernote widgets -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- form.media -->
  <link href="/static/django_summernote/summernote.css" type="text/css" media="all" rel="stylesheet" />
<link href="/static/django_summernote/django_summernote_inplace.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/django_summernote/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/static/django_summernote/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="/static/django_summernote/jquery.fileupload.js"></script>
<script type="text/javascript" src="/static/django_summernote/summernote.min.js"></script>
</head>
```

**Comment by lqez** [comment]
Thank you for reporting @tylerecouture,

As you know, django-summernote provides different js/css including options for each widget. See  https://github.com/summernote/django-summernote/blob/master/django_summernote/settings.py#L106-L131

`SummernoteInplaceWidget` assumes jquery and bootstrap stuffs are already loaded in the page.
And it could be caused by previous javascript errors, so please double check the console log.

**Comment by tylerecouture** [comment]
This is the only message in the console.

**Comment by kameruchi** [comment]
Im getting exactly the same problem with SummernoteInplaceWidget. @lqez , all the jquery and bootstrap stuff is loaded.
 @tylerecouture did you manage to solve this?

**Comment by kameruchi** [comment]
Ok I solved this one! I forgot to add {{ form.media }} in the template :P Working fine now!

**Comment by lqez** [comment]
Thanks!
