### ISSUE TITLE
Multiple SummernoteInplaceWidget receive same height

### ISSUE THREAD

**Issue by IlyaSemenov** [summernote/django-summernote#173]
## Problem

If you include multiple SummernoteInplaceWidget's on the same page, and specify different height for them, they all get resized to the last widget's height.

## How to reproduce

Construct a form and pass it to the template:

```python
class TestForm(forms.Form):
	text1 = forms.CharField(widget=SummernoteInplaceWidget({'height': '500px'}))
	text2 = forms.CharField(widget=SummernoteInplaceWidget({'height': '200px'}))

def show_form(request):
	return render(request, "test_form.html", {'form': TestForm()})
```

In template:

```django
{{ form }}
```

### Result

Two editors are created, both have height 200px.

### Expected result

Two editors are created, first one has height 500px, second has height 200px.

## The underlying reason

The generated jQuery selectors refer to first/all elements, not the element of the current widget:

```js
    $summernote.summernote($.extend(id_text2_settings, {
        callbacks: {
            onInit: function() {
                var nEditor = $('.note-editor'); // <------------- incorrect selectors
                var nToolbar = $('.note-toolbar');
                var nEditable = $('.note-editable');
                var nStatusbar = $('.note-statusbar');
                // ...
                nEditable.height(setHeight); // <------------- resizing all editors
```

**Comment by lqez** [comment]
You got the point. It would be much appreciate if you could provide a pull request for this issue.

**Comment by lqez** [comment]
This was fixed by https://github.com/summernote/django-summernote/pull/220.
Thanks.
