### ISSUE TITLE
Summernote Django Iframe widget doesn't work on iPad for me

### ISSUE THREAD

**Issue by MrCsabaToth** [summernote/django-summernote#175]
Neither Safari, nor Chrome. It's kinda hard to debug on my side, cause I don't have Apple products. I'm debugging an iPad remotely and my colleague made me a favor to try some stuff. I'm using the iframe summernote widget.
So we get:
![pasted image at 2017_01_09 09_57](https://cloud.githubusercontent.com/assets/744949/21779495/d0fbe8c0-d65c-11e6-83ce-3270decd65fd.png)
I replaced the `summernote.min.js` reference in the `summernote_iframe_editor.html` of the installed packege to `summernote.js` so I could see more details. Now I don't get an error in the console, but the `notes` field is not in the `self.changed_data` of my form (it's empty dictionary if I only changed the notes field) and also the change doesn't appear in the `self.cleaned_data`'s dictionary (the old version is there). Otherwise my form is functional, just the summernote change doesn't work.

**Comment by MrCsabaToth** [comment]
It's kind of a deal breaker right now

**Comment by MrCsabaToth** [comment]
Maybe the onBlur doesn't get called in iOS Safari / Chrome?

**Comment by lqez** [comment]
@MrCsabaToth is this only occurred in just iPad? or on every Apple products?

**Comment by MrCsabaToth** [comment]
Just iOS, I even tested it with a 2013 release of Safari for Windows and that was fine.

**Comment by lqez** [comment]
I tested both widgets on iPad Air 2 with iOS 11.0, but they worked without an error like below.
Please reopen when you're still struggling with the problem.
![fullsizerender 3](https://user-images.githubusercontent.com/579366/32593130-1738d4b8-c56a-11e7-8f84-4542efc61b41.jpg)
![fullsizerender 2](https://user-images.githubusercontent.com/579366/32593131-1761be32-c56a-11e7-88ec-99a744527c79.jpg)
