### ISSUE TITLE
drop-down menu is cropped in resized frame

### ISSUE THREAD

**Issue by xho95** [summernote/django-summernote#176]
Drop-down menu is cropped in resized frame as shown as below.

It works anyway, but it's hard to use.

Could you fix to move the drop-down menu according with frame boundary?

![summornote issue](https://cloud.githubusercontent.com/assets/8176454/22091591/f9cd7580-de3a-11e6-985b-d2a90150d191.jpeg)

**Comment by lqez** [comment]
Thank you for reporting.
I tried to fix this by https://github.com/summernote/django-summernote/commit/b4bd7f06d1622a43c84bcfcb3336ae61b240424b
Please test this with the latest release (v0.8.7)
