### ISSUE TITLE
Iframe Widget: double scrollbar hides the buttons

### ISSUE THREAD

**Issue by ppython** [summernote/django-summernote#177]
On Safari 9.11 at least (with the option on my os to always show scrollbars) :

Initial scroll state:
<img width="639" alt="screen1" src="https://cloud.githubusercontent.com/assets/18702503/22186371/c12d6e4e-e0c2-11e6-9e21-0e8081c3a6a0.png">

Scrolled a bit down with the trackpad, first row of buttons disapears:
<img width="640" alt="screen2" src="https://cloud.githubusercontent.com/assets/18702503/22186372/c1300f3c-e0c2-11e6-96c0-b2d92871321b.png">
Chrome and Firefox are handling this better....
Anyone with a quickfix ?!

**Comment by lqez** [comment]
I tried to fix this with [ResizeSensor](https://marcj.github.io/css-element-queries/).
ref: https://github.com/summernote/django-summernote/commit/56873e689a98d7836a46ca03acf7b6274dbb60e5

Could you try to test this with the latest release?
