### ISSUE TITLE
Display django-summernnote widget not in iframe

### ISSUE THREAD

**Issue by lqez** [summernote/django-summernote#18]
From roboslone@gmail.com (via email)

I’m trying to use django-summernote in my web app, but there’s an issue with it. I didn’t open an ‘issue’ on github, because I think it’s not quite right place for this one - django-summernote uses `iframe` to display form and this basically disables fullscreen feature. And also I couldn’t change form appearance (e.g. change toolbar background color or make round corners).

Is there any way to build a form (in my webapp's forms.py) that I can use in my templates like {{ form.as_table }}? And if there isn’t, do you have plans to implement this functionality?

**Comment by Uznick** [comment]
It does not work, it just shows empty textarea :(

**Comment by panza1991** [comment]
@lqez i have the same problem. SummernoteInplaceWidget does not work. it shows empty textarea

**Comment by lqez** [comment]
These problems are up to override admin media files. I'll add an example for it.

**Comment by Przemek625** [comment]
I still have the same problem - SummernoteInplaceWidget does not work. it shows empty textare. What is the solution?
