### ISSUE TITLE
Predefining a custom template 

### ISSUE THREAD

**Issue by msert29** [summernote/django-summernote#182]
Hi,

I want to predefine a custom html template which will be the blue print of the summernote text area.

I have checked many specifications incuding JS side ones however without a luck.

Is this functionality available ?

**Comment by lqez** [comment]
This does not need any special behavior. Summernote handle the target dom as an initial value by default. So, if you want to set 'default' value for summernote-ized field, set `initial` on the form (ref:https://docs.djangoproject.com/en/1.11/ref/forms/fields/#initial) or set `default` on each field (ref:https://docs.djangoproject.com/en/1.11/ref/models/fields/#default).
