### ISSUE TITLE
django-summernote 코드 중에 업로드 처리 부분에서 장고 1.11과 호환성 이슈가 발생하고 있습니다.

### ISSUE THREAD

**Issue by allieus** [summernote/django-summernote#183]
django-summernote 코드 중에 업로드 처리 부분에서 장고 1.11과 호환성 이슈가 발생하고 있습니다.

장고 1.11부터 파일업로드 시의 request.POST._mutable 속성이 True에서 False로 변경되었네요.
https://github.com/django/django/commit/4a246a02bdcbc13b15480c014f51cb0682af7c1e

이로 인해, django-summernote 아래 코드에서 AttributeError 가 발생합니다. pop 은 _mutable=False에서는 지원되지 않습니다.

```python
request.POST.pop('csrfmiddlewaretoken', None)
```

다음 2가지로 처리해볼 수 있을 듯 한데요.

```python
request.POST._mutable = True
request.POST.pop('csrfmiddlewaretoken', None)
kwargs = request.POST
```

혹은

```python
kwargs = request.POST.copy()
kwargs.pop('csrfmiddlewaretoken', None)
```

어떤 코드가 좋을까요?

**Comment by lqez** [comment]
Thank you for recommendation. I fixed this by https://github.com/summernote/django-summernote/commit/d887f1c5ad1f611e300f1868485efba9c2b34488.
