### ISSUE TITLE
Can't upload image from disk in summernote error

### ISSUE THREAD

**Issue by baal130** [summernote/django-summernote#184]
I have an error uploading an image from local files. If I use picture from url it saves it normally.
I have media url and root inside settings. 
This is the error:
got and error uplading an image : OperatiolError at /summernote/upload_attachment no such table :django_summernote_attachment

Any thought on this. Thanks

**Comment by lqez** [comment]
You have to run `migrate` before using it.
Please read : https://github.com/summernote/django-summernote#setup
