### ISSUE TITLE
Not able to view in inserting image from files while inserting image from url is okay

### ISSUE THREAD

**Issue by mich71095** [summernote/django-summernote#190]
Whenever I insert image from my local files the image from text area doesn't appear and when I check my media files the image is there. It seems it download the upload image automatically whenever I insert it and doesn't appear in the text area. Why is that? I tried inserting the image from url and the image appear in the text area. I already put

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

in urls.py and put 

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

in settings.py and nothing happen.

**Comment by lqez** [comment]
There was an error while retrieving uploaded image information (up to changes of jquery-file-upload) Could you try it again with the latest release? And please reopen this issue when it fails again.

**Comment by lqez** [comment]
Ref: https://github.com/summernote/django-summernote/pull/197
