### ISSUE TITLE
삭제된 파일에 대해서 어떻게 할 것인가?

### ISSUE THREAD

**Issue by lqez** [summernote/django-summernote#195]
첨부파일(Attachment)로는 존재하지만 해당 이미지를 포함하고 있던 글이 수정되거나 삭제되어 해당 파일이 더 이상 사용되지 않는 경우에, 해당 파일들은 orphan file 이 되는데, 이 파일들에 대한 처리가 필요합니다.

**Comment by pincoin** [comment]
개인적으로 에디터에서 처리할 일이 아닐 것 같습니다.

관리자가 비동기적으로 주기적으로 삭제할 수 있는 스크립트를 제공하면 어떨까 싶습니다.

**Comment by lqez** [comment]
@pincoin 해당 스크립트를 django command 로 구현하면 어떨까 싶습니다.
https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/#
