### ISSUE TITLE
Deploy Server Errors

### ISSUE THREAD

**Issue by benella** [summernote/django-summernote#206]
I was developing on my local machine and everything was working great, but after I deployed to Heroku (with WhiteNoise and S3) I get an 'Server Error (500)' in my admin page, instead of the widget.

My model has a TextField:
text_2 = models.TextField(default="", blank=True)

and on the Heroku log I'm getting:

2017-08-24T12:21:19.959131+00:00 heroku[router]: at=info method=GET path="/summernote/editor/id_text_2/" host=rawart-gallery.herokuapp.com request_id=899ed5e6-a5c9-4df3-942d-80dee1568b13 fwd="109.66.67.91" dyno=web.1 connect=0ms service=168ms status=500 bytes=253 protocol=https

#### admin.py

from django_summernote.admin import SummernoteModelAdmin
from django.contrib import admin
from .models import TextPage

class TextPageAdmin(SummernoteModelAdmin):
module = TextPage

admin.site.register(TextPage, TextPageAdmin)

#### settings.py

has 'django_summernote' in INSTALLED_APPS.

#### urls.py

has url(r'^summernote/', include('django_summernote.urls')), in urlpatterns

Any ideas about what could go wrong?
Thanks!

**Comment by lqez** [comment]
Hi @benella, did you check whether django-summernote installation while deploying or not?

**Comment by benella** [comment]
It was installed on the server and migrated as far as I can tell , django-summernote==0.8.7.3. Anything else I need to check?

**Comment by lqez** [comment]
Then it's enough. We need to check out error logs with `DEBUG=True` setting.

**Comment by benella** [comment]
Thank you man! Setting DEBUG=True fixed something and now it's working again.

**Comment by lqez** [comment]
@benella Awesome, would you like to write it down here to be helpful for others?

**Comment by benella** [comment]
As soon as I figure it out :)

**Comment by benella** [comment]
It seems to be a migration error. Thanks again!

**Comment by pincoin** [comment]
@benella 

It seems that you solved your problem, so this issue will be closed.

We would like you to post how you solved it for others.

Thank you.
