### ISSUE TITLE
using the nuggets extension

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#208]
https://github.com/pHAlkaline/summernote-plugins/tree/master/plugins/nugget

Is there a way to use this with django-summernote?  I'm not sure how to add the list of nuggets in to settings.py (adding them as is does nothing), or even just adding them on afterwords with js when the summernote is generated in an iframe:

```
    'nugget': {
        list: [  # list of your nuggets
            '[[Test Code]]',
            '[[code nugget 2]]',
            '[[code nugget 3]]'
        ]
    },
```

**Comment by tylerecouture** [comment]
Similar question with the "[add class](https://github.com/creativeprogramming/summernote-addclass)" extension, how to I add this part?
```

    addclass: {
        debug: false,
        classTags: [{title:"Button",value:"btn btn-success"},"jumbotron", "lead","img-rounded","img-circle", "img-responsive","btn", "btn btn-success","btn btn-danger","text-muted", "text-primary", "text-warning", "text-danger", "text-success", "table-bordered", "table-responsive", "alert", "alert alert-success", "alert alert-info", "alert alert-warning", "alert alert-danger", "visible-sm", "hidden-xs", "hidden-md", "hidden-lg", "hidden-print"]
    },
```

**Comment by pincoin** [comment]
Sooner or later, additional custom options will be supported.

**Comment by lqez** [comment]
You can add custom plugin settings via `summernote` section. Please see #225. Thanks.
