### ISSUE TITLE
Uploaded image not instantly visible in editor

### ISSUE THREAD

**Issue by Chayemor** [summernote/django-summernote#228]
**Django: ** 1.11.3
**Python:** 2.7.10
**Django-summernote:** 0.8.8.2

When I upload an image in Django admin, the image gets uploaded correctly to desired destination, but it does not appear within the text editor unless I **add image>from URL** after uploading. I can view the image if I set the `setttings.MEDIA_URL` in a browser tab, but for some reason the image doesn't get inserted on its own after the upload. Could it be because of that "permanently moved" message in Network?

These are the network messages when uploading the image. There are no console messages.

![error](https://user-images.githubusercontent.com/3482816/30536130-8ee53862-9c5c-11e7-8038-9c9b4b413330.png)

**settings.py**

```
DEBUG = True
TEMPLATES = [
    {
       ...
        'OPTIONS': {
            'context_processors': [
                '...
                'django.template.context_processors.media'
            ],
        },
    },
]
#Media files
MEDIA_URL='media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

#Static directories not tied to any apps
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# SUMMERNOTE editor configuration
def summernote_custom_upload_to():
    return "inline/media/" + datetime.datetime.now().strftime("%Y/%m")

SUMMERNOTE_CONFIG = {
    'prettifyHtml': False,
    'attachment_upload_to': summernote_custom_upload_to(),
    'toolbar': [
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['font', ['strikethrough', 'superscript', 'subscript']],
        ['color', ['color']],
        ['para', ['ul', 'ol']],
        ['insert', ['picture', 'video', 'link', 'hr']],
        ['misc', ['codeview']]
    ],
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    ),
    'codemirror': {
        'mode' : 'htmlmixed',
        'lineWrapping' : True,
        'lineNumbers': 'true',
        'theme': 'monokai',
    },
}
```
**urls.py**

```
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static( settings.MEDIA_URL, document_root= settings.MEDIA_ROOT )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

**Comment by lqez** [comment]
Could you try it again with `MEDIA_URL='/media/'`? (add a slash in front of the path)

**Comment by Chayemor** [comment]
Magic. Works perfect now, thank you. Sorry I didn't think of that first, it didn't even cross my mind for some reason. Appreciate it!

**Comment by kgadde** [comment]
I know this old. But on the same topic here. Can I put the uploaded file into a folder with post instance for example?
I have a blog post with the exact same setup as above. But would like to have my files go into a specific folder with post id.
