### ISSUE TITLE
styleWithTags don't work

### ISSUE THREAD

**Issue by amorino** [summernote/django-summernote#230]
I'm trying to use the styleWithTags parameter in the Setting in order to view the style attributes on the actual DOM tag but changing between True and False make no changes to the actual input.

Am I missing something? Thanks

**Comment by lqez** [comment]
There is no option `styleWithTags` in summernote. Did you mean `styleWithSpan`? And django-summernote only passes valid options. See https://github.com/summernote/django-summernote/blob/master/django_summernote/widgets.py#L23

**Comment by amorino** [comment]
styleWithTags ootion is mentioned on README.md under SUMMERNOTE_CONFIG.

**Comment by lqez** [comment]
Really sorry for the outdated document. I will fix it.

**Comment by lqez** [comment]
I replaced `styleWithTags: True` with `styleWithSpan: False` along to Summernote.
