### ISSUE TITLE
makemigrations didn't applied in v0.8.8.2

### ISSUE THREAD

**Issue by Beomi** [summernote/django-summernote#231]
django summernote needs `makemigrations` before migrate.

version 0.8.8.2

<img width="729" alt="2017-09-21 01 32 46" src="https://user-images.githubusercontent.com/11323660/30655801-fa4cc1d0-9e6c-11e7-952b-c1791556a3ae.png">

**Comment by lqez** [comment]
Could you share the migration code?

**Comment by Beomi** [comment]
0003_auto_20170921_0131.py file:

```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True),
        ),
    ]

```

**Comment by Beomi** [comment]
Not with master branch, but happends with v0.8.8.2 tag branch :)

**Comment by lqez** [comment]
Thank you for sharing. Then it should occur by missing of `unicode_literals` in the previous migration file.

**Comment by lqez** [comment]
I will close this issue after releasing the next version.
