### ISSUE TITLE
How I can hide django

### ISSUE THREAD

**Issue by qari** [summernote/django-summernote#232]
Hello, I wanna hide that I use django, but I find "/src/django_summernote/lang/summernote-*.min.js" in code. How I can hide that?

**Comment by lqez** [comment]
Currently, it can't. But I can guess why you want to hide the URL for static files.
Then how about to just `summernote` instead of `django_summernote`? I also think it is better to use `summernote` only.

**Comment by qari** [comment]
Yes, just summernote without django

**Comment by lqez** [comment]
Got it. Please stay tuned till next release. Thanks.

**Comment by lqez** [comment]
Renamed as just `summernote`.
