### ISSUE TITLE
The"Code View" html is a mess

### ISSUE THREAD

**Issue by stefko18** [summernote/django-summernote#233]
When I tried to edit the source html via "Code View" it was all mingled together, no lines, tabs, spaces ... all tags together in one line. It is very difficult to find something in the source. This way the "Code View" is nearly useless ... Is it something I do wrong or is that the defined behaviour? And if so could you fix it?

**Comment by qari** [comment]
It's normal! You can copy html in redactor who has formating and then after changes fill back

**Comment by stefko18** [comment]
Coud you specify what redactor? I am finding just paid modules ...

**Comment by qari** [comment]
SublimeText or Pycharm any HTML

**Comment by qari** [comment]
https://duckduckgo.com/?q=online+html+editor&t=ffab&ia=web

**Comment by stefko18** [comment]
That doesn't help .. I tried SublimeText, so first things that after import all formatting is lost, I have a plain text. But I need to preserve the html styles and get rows between html tags so I can find stuff and change in source. 

Seriously couldn't the developers just add this functionality? Who is suppose to use a online editor that has a messy html output? It's a good plain text editor but to be used as a content editor on a on a blog by editors ... i don't know ...  I still don't know how to make this work and I am not computer iliterate ...

**Comment by stefko18** [comment]
Ok, this does what i need: https://dirtymarkup.com/
Solved.

**Comment by lqez** [comment]
I'm trying to add embedded sanitizer in next release.
