### ISSUE TITLE
SummernoteInplaceWidget

### ISSUE THREAD

**Issue by qari** [summernote/django-summernote#234]
When use SummernoteWidget in Firefox blocked frame and I wanna use SummernoteInplaceWidget. but I can't setting. Where I can see example?

Load denied by X-Frame-Options: https://***/wysiwyg/editor/id_body/ does not permit framing.

**Comment by qari** [comment]
Load denied by X-Frame-Options: https://***/wysiwyg/editor/id_body/ does not permit framing. because I use on production X_FRAME_OPTIONS :)

**Comment by lqez** [comment]
There are two choices that you can do.

1. Use `SAMEORIGIN` on your `X-Frame-options` in web server settings.
1. Or, (as you said) use `SummernoteInplaceWidget`.

`djs_playground` shows both ways of using Summernote widgets.
Please refer it: https://github.com/summernote/django-summernote/tree/master/djs_playground
