### ISSUE TITLE
Code/Syntax Highlighting?

### ISSUE THREAD

**Issue by alzearafat** [summernote/django-summernote#235]
Hi!

I love django-summernote! And use it almost on my every project. 
But I dont know how to implement code highlighting. Anyone care to explain? 

Thank you!
Regards

**Comment by lqez** [comment]
Summernote supports [CodeMirror](https://codemirror.net/) for code highlighting. You can use it by adding `codemirror` option in your settings. 
```
SUMMERNOTE_CONFIG = {
    'codemirror': {
        'mode': 'htmlmixed',
        'lineNumbers': 'true',
    },
}
```

**Comment by alzearafat** [comment]
Thanks very much! @lqez
