### ISSUE TITLE
Some static storage issue on summernote-en-US.min.js file

### ISSUE THREAD

**Issue by clichedmoog** [summernote/django-summernote#236]
I've got this error with STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage' setting with DEBUG = False

`raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'django_summernote/lang/summernote-en-US.min.js'`

Which file is missing initially. but called with lang = None django-summernote setting
And the ManifestStaticFilesStorage checks file's existence, raises error.
So I've added a empty file, does not raise errors any more.

**Comment by lqez** [comment]
OMG
