### ISSUE TITLE
Missing staticfiles manifest entry for 'django_summernote/summernote.css'

### ISSUE THREAD

**Issue by tamhv** [summernote/django-summernote#238]
I got this error when using `STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'`
`ValueError: Missing staticfiles manifest entry for 'django_summernote/summernote.css'`
I'm not sure if it relates to #170 

DEBUG = False
Django==1.11.4
django-summernote==0.8.8.2

**Comment by lqez** [comment]
I haven't tested it on `ManifestStaticFilesStorage`. I will check it out.

**Comment by pincoin** [comment]
@tamhv 

https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-staticfiles

You will have to implement your own derived class from `django.contrib.staticfiles.storage.ManifestStaticFilesStorage` in order to set `ManifestStaticFilesStorage.manifest_strict` to `False`

Of course, the new subclass must be specified in `settings.py`.

We will give you a sample code as soon as possible. Thank you.

**Comment by tamhv** [comment]
thanks @pincoin 
I followed below instruction to use `MyCustomManifestStaticFilesStorage` with `manifest_strict = False`

> To enable the ManifestStaticFilesStorage you have to make sure the following requirements are met:
> 
> - the STATICFILES_STORAGE setting is set to 'myapp.MyCustomManifestStaticFilesStorage'
> - the DEBUG setting is set to False
> - you’ve collected all your static files by using the collectstatic management command

If i dont misunderstood, i have to `collectstatic` with `StaticFilesStorage` first, then change to `MyCustomManifestStaticFilesStorage` and `collectstatic` again to get file `staticfiles.json`, and commit `staticfiles.json`, then i can run `collectstatic` with `MyCustomManifestStaticFilesStorage` without error on production.

Because if i `gitignore` `STATIC_ROOT`, run `collectstatic` with prod settings:
DEBUG = False
STATICFILES_STORAGE = 'myapp.MyCustomManifestStaticFilesStorage'
I got error:
`ValueError: The file 'django_summernote/summernote.css' could not be found with <myapp.MyCustomManifestStaticFilesStorage object at`

**Comment by pincoin** [comment]
@tamhv 

I also made `DjsManifestStaticFilesStorage` which extends `ManifestStaticFilesStorage`.

```
class DjsManifestStaticFilesStorage(ManifestStaticFilesStorage):
    manifest_strict = False
```

I also encountered the same error. I solved the problem by overriding `hashed_name` method.

```
import os

from django.contrib.staticfiles.storage import ManifestStaticFilesStorage
from django.utils.six.moves.urllib.parse import (
    unquote, urlsplit, urlunsplit,
)


class DjsManifestStaticFilesStorage(ManifestStaticFilesStorage):
    manifest_strict = False

    def hashed_name(self, name, content=None, filename=None):
        # `filename` is the name of file to hash if `content` isn't given.
        # `name` is the base name to construct the new hashed filename from.
        parsed_name = urlsplit(unquote(name))
        clean_name = parsed_name.path.strip()
        if filename:
            filename = urlsplit(unquote(filename)).path.strip()
        filename = filename or clean_name
        opened = False
        if content is None:
            try:
                content = self.open(filename)
            except IOError:
                # Handle directory paths and fragments
                return name
            opened = True
        try:
            file_hash = self.file_hash(clean_name, content)
        finally:
            if opened:
                content.close()
        path, filename = os.path.split(clean_name)
        root, ext = os.path.splitext(filename)
        if file_hash is not None:
            file_hash = ".%s" % file_hash
        hashed_name = os.path.join(path, "%s%s%s" %
                                   (root, file_hash, ext))
        unparsed_name = list(parsed_name)
        unparsed_name[2] = hashed_name
        # Special casing for a @font-face hack, like url(myfont.eot?#iefix")
        # http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax
        if '?#' in name and not unparsed_name[3]:
            unparsed_name[2] += '?'
        return urlunsplit(unparsed_name)
```

I just removed the code which checks file exist. It seems to work, but I am not sure if it's correct. I have to study more in detail. That's why I told you that I would provide the code as soon as possible.

I also want your feedback. Thank you.

**Comment by tamhv** [comment]
thanks @pincoin 
I just tried your `DjsManifestStaticFilesStorage`. It works.
But i don't know if it makes issue to other packages. I guess there must be a reason to `raise ValueError("The file '%s' could not be found with %r." % (filename, self))` there.

**Comment by pincoin** [comment]
@tamhv 

Thank you for your response. We will close this issue at this point.

I also wonder if there's a side-effect on that change. If you encounter another problem, feel free to tell us. And, we will talk again after opening the new issue.
