### ISSUE TITLE
Some options are not working

### ISSUE THREAD

**Issue by marcelombc** [summernote/django-summernote#240]
The options iframe and disable_upload are not working.

**Comment by lqez** [comment]
`iframe` only affects on django admin site, not on custom pages. And `disable_upload` means ‘we will not use the uploading function built in django-summernote’ not disabling `image` button in toolbar. I agree that its name may confuse.

**Comment by marcelombc** [comment]
But iframe is not affecting on the admin site. I want to use the SummernoteInplaceWidget but when I set iframe to False nothing happens.
