### ISSUE TITLE
lang does not seem to work

### ISSUE THREAD

**Issue by frague59** [summernote/django-summernote#252]
Hi, 

I"ld like to use a translated (French) version of summernote in a django application. 

I've set 'lang' parameter in the `SUMMERNOTE_CONFIG` settings, but it is still in english...
```python
SUMMERNOTE_CONFIG = {
     # Does not use iframe for rendering
    'iframe': False,
    # 'inplacewidget_external_css': ('/static/fontawesome/css/font-awesome.css',),
    # 'inplacewidget_external_js': (),
    # airMode active
    'airMode': False,
    # Toolbar
   'toolbar': [
       ['style', ['style']],
       ['misc', ['undo', 'redo']],
       ['para', ['ul', 'ol', 'bold', 'italic', 'underline']],
       # ['view', ['fullscreen', 'codeview']],
       ['insert', ['link']],
       ['cleaner', ['cleaner']],
    ],
    # Editor size
    'width': '100%',
    'height': '320',
    'minHeight': '320',
    'maxHeight': '640',
    # lang
    'lang': 'fr',
    # Cleaner plugin
    'js': {'cleaner': '/static/js/forms/summernote-cleaner.js'},
}
```
I'm using the 0.8.8.2 version of django-summernote, the 0.8.8.3 is broken due to #245 

Thanks for your help !

**Comment by frague59** [comment]
Exploring JS / HTML, I can see that:

```js
$.getScript('django_summernote/lang/summernote-' + id_chapeau_settings.lang + '.min.js');
```
But this file does not exists...

**Comment by lqez** [comment]
Thank you for reporting. Could you try it again with the latest version? I think we fixed #245 by #253 .

**Comment by frague59** [comment]
Hi, 
The issue was on my side : I did pollute the templates (I did not remember why...)
Sorry !

**Comment by lqez** [comment]
Wow, not bad! Thank you for replying!
