### ISSUE TITLE
Codemirror settings dont work in SummernoteInplaceWidget.

### ISSUE THREAD

**Issue by NogerbekNurzhan** [summernote/django-summernote#256]
In my form I use `SummernoteInplaceWidget`.

I have 2 problems:

1. I notice that when I open form _bold button_ in toolbar is always active. I notice this bug in Firefox Mozilla but in other browsers it works fine. Also when I click to text which is without any style bold button became active. I notice this bug only in Firefox Mozilla. What do you this about that?
![default](https://user-images.githubusercontent.com/8999232/33844681-3789b24e-decb-11e7-85fb-5014543b3878.PNG)

2. Why next my settings dont change codemirror? I want to add colors and line numbers. What can you advice to me? Where is my mistake?

I want codemirror like this:
![default](https://user-images.githubusercontent.com/8999232/33845160-b775f746-decc-11e7-81f3-c366d7f896d1.PNG)

**settings.py:**
```
SUMMERNOTE_CONFIG = {
   'css': {
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    },
   'codemirror': {
        'mode': 'htmlmixed',
        'lineNumbers': 'true',
        'theme': 'monokai',
    },
}
```

I load static files in template cause when I tried to set static files in settings.py file it raise error.
**CSS:**
```
<link rel="stylesheet" type="text/css" href="{% static "summernote/summernote.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "summernote/django_summernote.css" %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">
```
**JS:**
```
<script src="{% static 'summernote/jquery.ui.widget.js'%}"></script>
<script src="{% static 'summernote/jquery.iframe-transport.js'%}"></script>
<script src="{% static 'summernote/jquery.fileupload.js'%}"></script>
<script src="{% static 'summernote/summernote.min.js'%}"></script>
<script src="{% static 'summernote/ResizeSensor.js'%}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js"></script>
```

Right now I have this:
![1](https://user-images.githubusercontent.com/8999232/33844953-17430548-decc-11e7-898d-4a0bf9729268.PNG)

**Comment by pincoin** [comment]
Hello,

We will test with your settings, and we will answer your issue soon. Thank you.

**Comment by NogerbekNurzhan** [comment]
I found the reason of second problem. The problem was in order of loading static files. I notice that codemirror static files must be set first and then must be summernote files.

```
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/codemirror.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.css">

But I have still one question. 

<link rel="stylesheet" type="text/css" href="{% static "summernote/summernote.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "summernote/django_summernote.css" %}">
```
![2017-12-12 10 37 24](https://user-images.githubusercontent.com/8999232/33867711-baca297e-df28-11e7-9e3c-fc9eb361af5d.png)

But I have still one question. As you can see from the picture I have long lines. Is it possible to move to a new row that part of code which not fit in the box? What can you advice, maybe some plugins?

Also what about the first problem? Do you have any ideas?

**Comment by pincoin** [comment]
@NogerbekNurzhan ,

Hello,

IHMO, the first question and your new question look like the problem of "summernote" not "django-summernote".

If we encounter the same problem, we will report it to "summernote" team, and we will answer you as soon as possible.

Thank you.

**Comment by NogerbekNurzhan** [comment]
Keep me posted on any developments, pls? :)

**Comment by NogerbekNurzhan** [comment]
@lqez  This bugs happens only in mozilla firefox browser, in other browsers there are no such problem. I think its summernote bug.

The content inside widget without any style and without any html. In codeview it looks like this:
![default](https://user-images.githubusercontent.com/8999232/33897056-a4ee1dca-df8e-11e7-87b5-4cf2d5aed1ca.PNG)

This is in normal position:
![default](https://user-images.githubusercontent.com/8999232/33897272-2ea25ff4-df8f-11e7-8acf-c9774d102100.PNG)

**Comment by lqez** [comment]
But I already tested it on Firefox (Quantum, 57.0 (64-bit)) on summernote.org page, but failed to reproduce it.

![screen shot 2017-12-13 at 1 56 07 am](https://user-images.githubusercontent.com/579366/33897448-d0bd7d50-dfa8-11e7-8dcb-52429c895329.png)

**Comment by NogerbekNurzhan** [comment]
In summernote.org page widget works fine. I use Firefox 57.0.1 (64 bit).

Right now I notice that in my project I have this style:
```
body {
    font: 500 14px/1.357 MuseoSansCyrlMedium, Arial, sans-serif;
    font-size: 14px;
}
```
When I disable this style bold button do not active. I think Firefox render page differently from other browsers. Its strange cause 100-500 is normal, and 600-900 bold. As you can see I use 500. I changed to 400 and now it works fine.

**Comment by pincoin** [comment]
@NogerbekNurzhan ,

Thank you for your sincere reports.
