### ISSUE TITLE
Is it possible to enable resize in django-summernote?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [summernote/django-summernote#258]
I use `SummernoteInplaceWidget` in my project.

In summernote its possible to enable resize of widget by next settings:
```
$("#discription").summernote({
	focus: true,
	disableResizeEditor: true
});
```

My question is simple. Have you included this capability in django-summernote?

**Comment by lqez** [comment]
`disableResizeEditor` was not in `__summernote_options__`. 
I updated it with another latest options by https://github.com/summernote/django-summernote/commit/1b38cbd6649dbb0c6c3b577312fba62e4334bdd4, thanks.
