### ISSUE TITLE
Upgrade v0.8.7 to v0.8.8.5 FullScreen only show half height of window.

### ISSUE THREAD

**Issue by yinkanghong** [summernote/django-summernote#261]
I upgrade my Django from v1.11.5 to Django2.0,so i upgrade DjangoSummernote from v0.8.7 to 0.8.8.5.After upgrade i find full-screen not work like before.In v0.8.7 full-screen will resize  SummernoteInplaceWidget to full screen,but in v0.8.8.5 SummernoteInplaceWidget only resize to about half of screen.
0.8.8.5:
[before full-screen ](https://blog.dreamgotech.com/media/summer_note/20171214-181750-923.png)
[after full-screen ](https://blog.dreamgotech.com/media/summer_note/20171214-181757-119.png)

**Comment by yinkanghong** [comment]
One more thing,I get this error when upload pic:
```
[Thu Dec 14 17:37:12.616429 2017] [:error] [pid 27622:tid 139723088406272] 2017-12-14 17:37:12,615 [ERROR]- Internal Server Error: /summernote/upload_attachment/
[Thu Dec 14 17:37:12.616437 2017] [:error] [pid 27622:tid 139723088406272] Traceback (most recent call last):
[Thu Dec 14 17:37:12.616440 2017] [:error] [pid 27622:tid 139723088406272]   File "/django/Blog/environment/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
[Thu Dec 14 17:37:12.616443 2017] [:error] [pid 27622:tid 139723088406272]     response = get_response(request)
[Thu Dec 14 17:37:12.616447 2017] [:error] [pid 27622:tid 139723088406272]   File "/django/Blog/environment/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
[Thu Dec 14 17:37:12.616450 2017] [:error] [pid 27622:tid 139723088406272]     response = self.process_exception_by_middleware(e, request)
[Thu Dec 14 17:37:12.616453 2017] [:error] [pid 27622:tid 139723088406272]   File "/django/Blog/environment/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Thu Dec 14 17:37:12.616456 2017] [:error] [pid 27622:tid 139723088406272]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Dec 14 17:37:12.616459 2017] [:error] [pid 27622:tid 139723088406272]   File "/django/Blog/environment/lib/python3.4/site-packages/django_summernote/views.py", line 46, in upload_attachment
[Thu Dec 14 17:37:12.616462 2017] [:error] [pid 27622:tid 139723088406272]     if not request.user.is_authenticated():
[Thu Dec 14 17:37:12.616466 2017] [:error] [pid 27622:tid 139723088406272] TypeError: 'bool' object is not callable
```
In django2.0 releases note:

`Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported.`

so 
```
    authenticated = \
        request.user.is_authenticated if django.VERSION >= (1, 10) \
        else request.user.is_authenticated()
```

need be change something like:

`    authenticated = request.user.is_authenticated `

**Comment by lqez** [comment]
Thank you for reporting @yinkanghong, could you share your environment like OS, browser, etc?

**Comment by lqez** [comment]
And the second thing is a bug. (I wrote it reversed, lol)

**Comment by yinkanghong** [comment]
Python 3.5
Django 2.0
browser:Chrome

Project has same bug on windows and Ubuntu14.04

**Comment by lqez** [comment]
Thanks, I will find out.

**Comment by yinkanghong** [comment]
I find the bug  only exist v0.8.8.4,you fix it in  v0.8.8.5. :+1:

**Comment by yinkanghong** [comment]
And i find when SummernoteInplaceWidget is required in ModelForm,when form preverification,if you not click the SummernoteInplaceWidget ,the error msg to remind require will not showup.
This is logged in chrome:
`An invalid form control with name='content' is not focusable.`

**Comment by yinkanghong** [comment]
The full screen bug exist in all version v0.8.8.x,I find you start to merge iframe and inplce in

**Comment by yinkanghong** [comment]
I get why the bug occur,in `widget_common.html`,line 59-64:

```
                        // Resize again when the height of note-toolbar changed
                        // This enhances calculation behaviors on Safari
                        new ResizeSensor($nEditor.find('.note-toolbar'), function () {
                            recalcHeight($nEditor);
                        });
```
You re-calc height when widget in change,so when full screen this function will set widget to a new calculated value， Am I right？
If i delete the code block,this bug will gone.So how can we fix this?

**Comment by lqez** [comment]
It would be great if you could fix it and make a pull request here.

**Comment by yinkanghong** [comment]
Is SummernoteWidget full screen then set the height of wysiwyg editer to iframe height right?
