### ISSUE TITLE
Awkward popovers in iframe

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#266]
I have a `TextField` using summernote with   `formfield.widget = SummernoteWidget()`

using an iframe:
```
SUMMERNOTE_CONFIG = {
    'iframe': True, 
    'width': '100%',
    'height': '460',
    ...
```
But if I have an element close to the edge of the iframe, for example an image at the bottom, then the popover creates this awkward second scrollable area within the scrollable area since the popover appears below the image and outside the container.  Here's an image example:

![summernotepopoverproblems](https://user-images.githubusercontent.com/10604391/34464363-927b599a-ee30-11e7-8d6b-497b043d56af.png)

Is there a way around this?  Everything looks and works great until I need a popover..

Here's some additional CSS in case it's the problem:

```
.panel-summernote, .list-group-item-summernote {
    padding: 0px;
    border-radius: 0px;
    /*DOM height on load so doesn't grow when Summernote finishes loading */
    min-height: 544px;
}

.note-editable {
  /*need to override inline height which is 20px too short*/
  height: 382px !important;
}


```

**Comment by lqez** [comment]
@tylerecouture thank you for reporting. Could you share your environment for further debugging?

**Comment by lqez** [comment]
I can't reproduce this on my local. Please reopen this again with testing env. (like codepen or jsfiddle)
