### ISSUE TITLE
Language is not being properly loaded

### ISSUE THREAD

**Issue by agessner** [summernote/django-summernote#267]
I am trying to use `django-summernote` in Portuguese and it works fine on `local` environment, but in `production` it does not. 

After digging into the code, I found out (in `templates/django_summernote/widget_common.html`) that the request to get the translated titles is supposed to be done synchronously.

```js
if( settings.lang != 'en-US' ) {
    $.ajax({url: settings.url.language, dataType: "script", async: false}
}
$sn.summernote($.extend(settings, {
    ...
}))
```

But, accordingly to [JQuery`s docs](http://api.jquery.com/jQuery.ajax/):
> async: [...] Cross-domain requests and dataType: "jsonp" requests do not support synchronous operation. [...]

That being sad, (_if I get it right_) the static language files that are in a different domain (i.e., s3), will not be synchronously loaded.

My idea is to change this ajax request to use an on complete callback, so we can make sure the language is loaded before we initiate the editor. What do you think, can I go on and open a PR?

```js
var initEditor = function() {
    $sn.summernote($.extend(settings, {
        ...
    }))
};

if( settings.lang != 'en-US' ) {
    $.ajax({url: settings.url.language, dataType: "script", complete: initEditor}
} else {
    initEditor();
}
```

**Comment by lqez** [comment]
Hi @agessner, thank you for your suggestion.
As you wrote above, I also knew that I wrote it with a bad approach.

But I do not want to correct it on `django-summernote` side. Currently, `summernote` does not provide a proper way to change its translation dynamically. (Ref: https://github.com/summernote/summernote/issues/2616)

Before fixing it on `summernote` side, your idea looks pretty good enough.

**Comment by agessner** [comment]
Thanks @lqez. Am I able to create a pull request with the changes I suggested? (sorry if it's a dumb question, I'm not a regular contributor)

**Comment by lqez** [comment]
@agessner Sure, just fork this project (with right above button) and see https://help.github.com/articles/fork-a-repo/ 👍
