### ISSUE TITLE
csrfmiddlewaretoken not getting set in payload on image upload

### ISSUE THREAD

**Issue by wilsonand1** [summernote/django-summernote#269]
When I try and upload images with summer note, i get "Forbidden (403) CSRF verification failed. Request aborted." only in production, it doesn't happen local. I have SSL enabled and set up correctly. I've switched to using the SummernoteInplaceWidget.

I've noticed that the csrfmiddlewaretoken is set to null in the payload. This is the request payload from chrome. 
```
------WebKitFormBoundaryTRqaNsyvpwAeJCrh
Content-Disposition: form-data; name="csrfmiddlewaretoken"

null
------WebKitFormBoundaryTRqaNsyvpwAeJCrh
Content-Disposition: form-data; name="files"; filename="Screen Shot 2018-02-07 at 15.02.40.png"
Content-Type: image/png


------WebKitFormBoundaryTRqaNsyvpwAeJCrh--
```

It gets set fine locally.

Here's my summernote config:
```
SUMMERNOTE_CONFIG = {
    'iframe': False,
    'toolbar': [
        ['style', ['fontsize', 'color', 'bold', 'italic', 'underline', 'striketrough', 'clear']],
        ['para', ['ol', 'ul']],
        ['insert', ['link', 'picture', 'video']]
    ],
    'width': '100%'
}
CSRF_COOKIE_NAME = 'csrftoken'
```

The summernote js code has the right cookie name in but doesn't seem to pick it up.

**Comment by lqez** [comment]
Could you check it out whether `django.middleware.csrf.CsrfViewMiddleware` exists in your middleware settings.

**Comment by wilsonand1** [comment]
here's my middleware config

``` python
MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)
```

**Comment by lqez** [comment]
`SummernoteInplaceWidget` uses a cookie to get `csrftoken`. You have to check your domain settings or environments about cookies. Cookie can be varied by domains.

**Comment by wilsonand1** [comment]
Thanks. This was the problem. I had set `CSRF_COOKIE_HTTPONLY` set to `True`. Changing it to `False` fixed my issue.

Thanks for your help man.
