### ISSUE TITLE
TypeError at /summernote/editor/id_content/

### ISSUE THREAD

**Issue by terlord1** [summernote/django-summernote#271]
I recieved this error only when I placed the SUMMERNOTE_CONFIG in my settings.py file. 
Traceback:

Request Method: | GET
-- | --
http://127.0.0.1:8000/summernote/editor/id_content/
2.0.2
TypeError
can only concatenate tuple (not "set") to tuple
/home/dawid/Dev/thepoint/lib/python3.5/site-packages/django_summernote/views.py in __init__, line 29
/home/dawid/Dev/thepoint/bin/python
3.5.2
['/home/dawid/Dev/thepoint/src',  '/home/dawid/Dev/thepoint/lib/python35.zip',  '/home/dawid/Dev/thepoint/lib/python3.5',  '/home/dawid/Dev/thepoint/lib/python3.5/plat-x86_64-linux-gnu',  '/home/dawid/Dev/thepoint/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/dawid/Dev/thepoint/lib/python3.5/site-packages']
Fri, 9 Feb 2018 16:13:45 +0000

/home/dawid/Dev/thepoint/lib/python3.5/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/home/dawid/Dev/thepoint/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/home/dawid/Dev/thepoint/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/home/dawid/Dev/thepoint/lib/python3.5/site-packages/django/views/generic/base.py in view
            self = cls(**initkwargs) ...
▶ Local vars
/home/dawid/Dev/thepoint/lib/python3.5/site-packages/django_summernote/views.py in __init__
                   + summernote_config['css'] ...
▶ Local vars

**Comment by pincoin** [comment]
@terlord1 

Could you share your `SUMMERNOTE_CONFIG` here?

Thank you.

**Comment by terlord1** [comment]
SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode
    'iframe': True,  # or set False to use SummernoteInplaceWidget - no iframe mode

    # Using Summernote Air-mode
    'airMode': False,

    # Use native HTML tags (`<b>`, `<i>`, ...) instead of style attributes
    'styleWithSpan': False,

    # Set text direction : 'left to right' is default.
    'direction': 'ltr',

    # Change editor size
    'width': '100%',
    'height': '640',

    # Use proper language setting automatically (default)
    'lang': None,

    # Or, set editor language/locale forcely
    'lang': 'us-EN',

    # Customize toolbar buttons
    'toolbar': [
        ['style', ['style']],
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['para', ['ul', 'ol', 'height']],
        ['insert', ['link']],
    ],
    # Set common css/js media files
    'base_css': (
        '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css',
    ),
    'base_js': (
        '//code.jquery.com/jquery-1.9.1.min.js',
        '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js',
    ),
    'default_css': (
        os.path.join(STATIC_URL, 'django_summernote/summernote.css'),
        os.path.join(STATIC_URL, 'django_summernote/django_summernote.css'),
    ),
    'default_js': (
        os.path.join(STATIC_URL, 'django_summernote/jquery.ui.widget.js'),
        os.path.join(STATIC_URL, 'django_summernote/jquery.iframe-transport.js'),
        os.path.join(STATIC_URL, 'django_summernote/jquery.fileupload.js'),
        os.path.join(STATIC_URL, 'django_summernote/summernote.min.js'),
    ),

    # You can disable file upload feature.
    'disable_upload': False,

    'css': {
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    },
    'codemirror': {
        'mode': 'htmlmixed',
        'lineNumbers': 'true',

        # You have to include theme file in 'css' or 'css_for_inplace' before using it.
        'theme': 'monokai',
    },

    'lazy': True,
}

**Comment by lqez** [comment]
Please change css `dict` to `set`. Like below;
```
'css': (
    '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
),
```
