### ISSUE TITLE
My summernote widget form dosent render when in production in heroku

### ISSUE THREAD

**Issue by terlord1** [summernote/django-summernote#272]
My summernote widget does not render on production. When i have it on my local machine and with debug mode on it would work and everything would work. When i checked heroku logs it would return a 200 http status. All my other views would work fine on heroku.

**Comment by terlord1** [comment]
Fixed this error by setting X_FRAME_OPTIONS off. 
### Whoops

**Comment by lqez** [comment]
I tested it in the similar environment, but there was no problem.
Could you check the domain name when you used in production code? If the domain name is same, there should be no error.
