### ISSUE TITLE
from django.views import View in django1.9 do not inport

### ISSUE THREAD

**Issue by rudj** [summernote/django-summernote#274]
On mine eviroment (dj 1.9.13) I had to change row 10 in view.py to import View from views.generic.
I find the change from django.views.generic.base.View to from django.views import View in 1.10 release notes.
Am I missing something?

**Comment by lqez** [comment]
Django changed their rule for importing `View` from 1.10.
So we have https://github.com/summernote/django-summernote/blob/master/django_summernote/views.py#L8-L11 to determine the way how to import it.

If you're still using under Django 1.10, it should use `from django.views.generic import View`.

**Comment by rudj** [comment]
right!
So, maybe line 8 of django-summernote/django_summernote/views.py have to be changed from:
`if django.VERSION <= (1, 9):
    from django.views.generic import View
else:
    from django.views import View
`
to
`if django.VERSION < (1, 9):
    from django.views.generic import View
else:
    from django.views import View
`
