### ISSUE TITLE
Set CSS attributes in widget for form validation

### ISSUE THREAD

**Issue by allegre** [summernote/django-summernote#275]
I have several Summernote text input boxes on a single page and I would like to change the border color of the boxes if the input doesn't pass validation. Without Summernote, the border color is styled by CSS using the "form-control is-invalid" class in the textarea tag:

```
<textarea name="field1" class="form-control is-invalid" required="" id="id_field1"></textarea>
```

Is there a way to replicate this behavior by passing a CSS border color attribute to Summernote?

I've tried passing CSS attributes through the Django widget in the same way that height and width can be set on a per-field basis, like this:

```
self.fields['field1'] = forms.CharField(widget=SummernoteInplaceWidget(attrs={'border': '1px solid #dc3545'}))
```

but the 'border' attribute does not make it into the rendered HTML, which looks like this:

```
<div class="note-editor note-frame card" style="width: 100%;">
```

I would like to pass the border attribute through the widget so the rendered HTML looks like this:

```
<div class="note-editor note-frame card" style="width: 100%, border: 1px solid #dc3545;">
```

Alternatively, if there was a way for the "note-editor" class to inherit the "is-invalid" class of the underlying textarea, I could style the border through an included CSS file.

Any suggestions?

**Comment by lqez** [comment]
I've recognized this problem a couple of years ago. But no time to handle this.
I'll try to implement this out. Thanks.

**Comment by lqez** [comment]
Now, this could be done by https://github.com/summernote/django-summernote/commit/c64e002b3c077fe4be0b4b4d022af496912b6b9f, like below;

```python
some_text = forms.CharField(                                                          
    label='Some text',                                                             
    widget=SummernoteInplaceWidget(attrs={'style': 'border: 1px solid #dc3545;'})
)
```

Custom attributes will be placed on the original tag (like `textarea`) and summernote will copy attributes from it. This will be available in next release.

<img width="897" alt="screen shot 2018-09-12 at 4 37 31 pm" src="https://user-images.githubusercontent.com/579366/45409491-439f2980-b6aa-11e8-8cf3-e0f8121ba58c.png">
