### ISSUE TITLE
Summernote icons not showing up on production

### ISSUE THREAD

**Issue by connectshopsco** [summernote/django-summernote#276]
![screen shot 2018-03-30 at 3 18 53 pm](https://user-images.githubusercontent.com/36456726/38155699-eba7fb48-342d-11e8-8b23-704102dc882f.png)

On local, everything is perfectly working well, but on production, feature icons of the summernote show up with a small rectangle thing. From what I found in dev tool of chrome, it shows summernote.woff?0d0d5fac99cc8774d89eb08b1a8323c4 and Roboto-* were not imported.

Have anyone had this type of issue?

**Comment by adamshamsudeen** [comment]
Configure the static correctly, set the STATIC_ROOT directory.

**Comment by jaddison** [comment]
You may need something like 
```
    location ~* \.(eot|ttf|otf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
        ...
    }
```
in your nginx config (if you're using nginx to serve static, of course)

**Comment by elifrah** [comment]
Same problem, my project deployed on Google App engine and return `Failed to decode downloaded font: <URL>` 
I'm not showing icons like @connectshopsco 
I added also `Access-Control-Allow-Origin *` and my STATIC_ROOT directory well defined for my another static files. 

I need help 

Thanks

**Comment by jaddison** [comment]
If anyone here is using FTP to transfer files to a server, make sure it's transferring in binary mode, NOT ASCII. I've ready reports elsewhere that ASCII tranfers corrupt the files (pretty common with FTP).

**Comment by lqez** [comment]
Agree with @jaddison. This is not a django-summernote issue.
Please refer https://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font

**Comment by anshuUnity** [comment]
> Same problem, my project deployed on Google App engine and return `Failed to decode downloaded font: <URL>`
> I'm not showing icons like @connectshopsco
> I added also `Access-Control-Allow-Origin *` and my STATIC_ROOT directory well defined for my another static files.
> 
> I need help
> 
> Thanks

did you solve this

**Comment by anshuUnity** [comment]
> You may need something like
> 
> ```
>     location ~* \.(eot|ttf|otf|woff|woff2)$ {
>         add_header Access-Control-Allow-Origin *;
>         ...
>     }
> ```
> 
> in your nginx config (if you're using nginx to serve static, of course)

still not able to solve
