### ISSUE TITLE
How to limit the number of suggestions offered by Hint/Mention functionality?

### ISSUE THREAD

**Issue by SophieLauren** [summernote/django-summernote#277]
Hej there!
First of all I would like to say a huge thank you! #
Your project is amazing. I have been using it for a couple of months and it is just brilliant. Lovely, great work!  <3

I  am currently working on a project using Django, Django Rest Framework and Django Summernote.

At the moment I am customizing Summernote WYSIWYG editor in order to offer my users the opportunity to mention other users. I am passing the user list to Summernote via Django Rest Framework. My Code at the moment looks like this:

Grabbing the Users: 
//with this function I grab the user list from and endpoint that I set w/ Django Rest Framework

```
function userList(){
    console.log("fetching user list...")
    user_list = []
    $.ajax({
        url: '/api/users/user_list/',
        method: "GET",
        success: function(data){
            for (i in data) {
                    user_list.push(data[i].username);
                }
        }
    })
    return user_list
```

Django Rest Framework View Function:
```
class UserListAPIView(generics.ListAPIView):
    serializer_class = UserDisplaySerializers
    queryset = User.objects.all()

```

Summernote:

```
hint: {
    mentions: userListt(),
    match: /\B@(\w*)$/,
    search: function (keyword, callback) {
      callback($.grep(this.mentions, function (item) {
        return item.indexOf(keyword) == 0;
      }));
    },
    content: function (item) {
      return '@' + item;
  },
},
```
The Code Works. I Can get the user list and offer autocompletion features to my users. But I am really afraid that as the website grows, giving the whole list of users could result in some excessively slow quering of the database, slowing down the whole website.

How could I fix this? How can I limit the number of users shown, and then update the autocomplete suggestions based on the letters that the user is typing after @ ?

I would like to setup something like what is offered by django-automplete-light, if you know what I mean.

Thanks everyone for your precious help.

Sophie.

p.s. I also, still have to figure out how to notify the users that they have been mentioned. So far I am using django-notification-hq + custom signals, to notify the users of other things going on, but got no idea on how to combine the various things together to notify the users when mentioned using Summernote.

Any suggestions on that too? Thanks so much!!!

p.p.s 
I guess I should have added also a lable with "need help", I am sorry about that but I couldn't figure out how to add it!

**Comment by lqez** [comment]
Thank you for using Summernote and django-summernote. Happy to hear that. :)
This is not a django-summernote related issue. But IMHO,

- Show recently mentioned users when `@` is pressed. You can hold user list in cookie or session, not accessing database.
- Limit the count of items in the list. Django already supports it by slicing. e.g. `users = User.objects.filter(name__startswith="somewhat")[:10]`
