### ISSUE TITLE
Different behavior on different machines on same configurations.

### ISSUE THREAD

**Issue by lk-geimfari** [summernote/django-summernote#280]
I have configured it and it works fine locally, but when I have to try to edit something in admin on the production version of a project then I see that it does not work.

I have checked Chrome console and see this:

![screenshot from 2018-04-18 17-21-42](https://user-images.githubusercontent.com/15812620/38938025-470de322-432d-11e8-83d7-dc9623b6b7d0.png)

Any ideas why does it happen and how to fix it?

Env: Django==1.11.9, `django-summernote==0.8.8.6`

**Comment by lk-geimfari** [comment]
I feel myself like an idiot, sorry for the opening this issue. Seems like i just forget run `manage.py collectstatic --noinput`. Usually, this command runs automatically on the server on each `git merge`, but for reasons unknown to me, it did not work.

Sorry again and thanks for this great library.

**Comment by lqez** [comment]
No worries, thank you for using Summernote!
