### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by patabongo** [summernote/django-summernote#283]
Are there plans to make django-summernote Bootstrap 4 compatible? One project I'm working on recently upgraded Bootstrap, and all its plugins, to version 4. It has made the Summernote formatting a bit screwy (although everything still works, I think).

I saw that the non-Django Summernote project is now BS4 compatible, so I thought I would check here before I start digging around and trying to fix things.

**Comment by lqez** [comment]
`0.8.10.0` will be shipped with this. https://github.com/summernote/django-summernote/pull/320
