### ISSUE TITLE
Youtube current point in time embedding does not work

### ISSUE THREAD

**Issue by yuong1979** [summernote/django-summernote#285]
The embedding of youtube videos at a chosen point in time does not work, it either starts at 0:00 or some random point in time. 

I have tried different ways of inserting the video such as using https://youtu.be/OLHdzLpMg-s?t=1486 and https://youtu.be/OLHdzLpMg-s?t=1h3m21s but it is not working. 

Is that a bug?

**Comment by lqez** [comment]
This is not a bug of django-summernote. I made a PR for this. Please stay tuned on the issue of summernote: https://github.com/summernote/summernote/pull/2847.
