### ISSUE TITLE
Mixes content of different fields in Inline model.

### ISSUE THREAD

**Issue by lk-geimfari** [summernote/django-summernote#286]
When adding and saving a new object, the previous field with TextField is not being saved.

Steps:

1. Add new item
2. Fill the field 
3. Click "Add" link to show another blank inline
4. Fill the second field
5. Save

The content of the first field is saved in the second field, the content of the second field is saved in the third field etc.

There is how it looks like:

![screenshot from 2018-05-28 14-25-41](https://user-images.githubusercontent.com/15812620/40612411-15f946bc-6283-11e8-9a4b-803d39fb1ae1.png)

Here concept must contain `concept`, tokens - `tokens` and model - `model`.

This issue exists when `extra = 1`.

**Comment by lqez** [comment]
Could you let me know which widget has been used? `SummernoteWidget` or `SummernoteInplaceWidget` ?

**Comment by lk-geimfari** [comment]
@lqez I have try both, right now it looks like this:

```python
class WebReportInfoAdminInline(TranslationStackedInline, SummernoteInlineModelAdmin):
    model = models.WebReportInfo
    extra = 1
    fields = (('title', 'score'), 'text')
    summernote_fields = ('text',)
```

**Comment by lqez** [comment]
@lk-geimfari gotcha. I'll test with both.

**Comment by lqez** [comment]
I'd tried to overcome this with `SummernoteInplaceWidget` but it's a little bit complicated.
I recommend to use `SummernoteWidget` (`iframe: True` mode) for inline elements.
Sorry for late replying, thanks.
