### ISSUE TITLE
Custom Default Fontsize Not Being Applied to Bullet and Numbered Lists #

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#292]
#### steps to reproduce
1.  I am using latest version of the summernote lite without Bootstrap.
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>
     I got these libraries from the latest summernote lite instructions on the website.
2.  This is the code I am using in my HTML.
    <textarea id="summernote" name="book"></textarea>
        <script>
          $('#summernote').summernote({
            width: 755,
            height: 300,
            toolbar: [
              ['undo', ['undo',]],
              ['redo', ['redo',]],
              ['style', ['bold', 'italic', 'underline',]],
              ['font', ['strikethrough',]],
              ['fontsize', ['fontsize']],
              ['color', ['color']],
              ['para', ['ul', 'ol', 'paragraph']],
            ]
          });
          $('#summernote').summernote('fontSize', 22);
        </script>
3.  The default fontSize is being applied as outlined above, but the bulleted lists and the number lists are still at the default 6 so when user click to set a list, the bullets and numbers are basically illegible.  Am I doing something incorrectly as far as setting the default fontSize?  Is there a setting that I'm not aware of or is this in need of being addressed?

#### browser version and os version and summernote version
What is your browser and OS?  I am using the latest version of Chrome.
What is your summernote version?  django_summernote 0.8.8.7
![summernote](https://user-images.githubusercontent.com/30054587/42414566-f5ea9580-81fc-11e8-8ad0-916039ab86e5.PNG)

#### screenshot of issue
Add screenshot which shows your issue(if needed).
You can make [gif from Recordit](http://www.recordit.co/).

![summernote5](https://user-images.githubusercontent.com/30054587/42463605-3d99ac66-836c-11e8-8e29-4c2c48ee42b4.PNG)
![summernote6](https://user-images.githubusercontent.com/30054587/42463612-4438c2b4-836c-11e8-9732-adbd0c2a6335.PNG)

Confirmed today the bullet and number are of a reasonable size using bootstrap, but don't appear to be influenced by fontsize either.  Using the following libraries:

            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
             <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
             <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
             <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
             <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
             <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>      

Produces the following result:

![summernote7](https://user-images.githubusercontent.com/30054587/42476874-e9237c2e-8394-11e8-952f-b6ea3684d294.PNG)

At a minimum would be great to see this in the lite version.  The current lite version just shows a spec for both the number and the bullet.

If you can make the issue using jsfiddle(https://jsfiddle.net/), We can save time to reproduce the problem.

**Comment by lqez** [comment]
Thank you for using Summernote, but this is not an issue of `django-summernote`. Please leave this issue on https://github.com/summernote/summernote. IMHO, you'd better set font sizes in your CSS files, not just in Summernote settings.
