### ISSUE TITLE
Custom Toolbar With Django CreateView Not Working

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#293]
When I do a straight forward CreateView with Django and a custom toolbar, I write my code as outlined below, and all works as expected.  

<div class="spacer89">
  <textarea id="summernote" name="procedure"></textarea>
      <script>
        $('#summernote').summernote({
          width: 755,
          height: 300,
          fontSizes: ['8', '9', '10', '11', '12', '14', '18', '22','24', '36', '48' , '64', '82', '150'],
          toolbar: [
            ['undo', ['undo',]],
            ['redo', ['redo',]],
            ['style', ['bold', 'italic', 'underline',]],
            ['font', ['strikethrough',]],
            ['fontsize', ['fontsize']],
            ['fontSizes', ['8', '9', '10', '11', '12', '14', '18', '22','24', '36', '48' , '64', '82', '150']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
          ],
        });
        $('#summernote').summernote('fontSize', 22);
      </script>
  </div>

I then get the toolbar as shown below:

![summernote11](https://user-images.githubusercontent.com/30054587/42483102-29afc966-83b1-11e8-8380-db5f17440a56.PNG)

However, when I try to copy in data into a CreateView with a custom toolbar, the toolbar shows as expected, but my data does not show up in the box to edit.   The only way I can seem to get the data to show up is when I leverage the following HTML:

<div class="spacer89">
  <div>
  {{ form.book}}
  </div>
  </div>  

And then leverage a widget in my ModelForm

        widgets = {
        'book': SummernoteWidget(),
        }

But this then obviously gives me the full toolbar configuration as shown below which I do not want.

![summernote12](https://user-images.githubusercontent.com/30054587/42483303-51a5adf4-83b2-11e8-870f-36fed55a3243.PNG)

Is there some other way for me to customize the toolbar so that my custom toolbar settings can be leveraged?  I suspect maybe a copy is happening and overwriting my data when the custom toolbar is used in the present configuration but I can't be sure...

**Comment by lqez** [comment]
You can customize `Summernote`'s options inside `SUMMERNOTE_CONFIG` at your `settings.py`.
```python
SUMMERNOTE_CONFIG = {
    'summernote': {
        'toolbar': ...
    },
}
```
