### ISSUE TITLE
Enable Resize Editor

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#294]
I have defined a custom toolbar to my django installation in the settings.py file.  This is working as desired.  I am trying to enable the resize editor as it appears disabled.  I have tried to add the the following to the settings.py file.  

        'disableResizeEditor': False,

This doesn't appear to work.  Is it possible to define this setting in the settings.py file?

**Comment by lqez** [comment]
And also, `SummernoteWidget` uses `iframe` to display editor isolated. In that case, django-summernote disables the resize bar automatically. You have to use `SummernoteInplaceWidget` to use it.

**Comment by dunkinman** [comment]
Thank you!  Yes this solved that problem.  Previously my CSS file was controlling the placement of the SummernoteWidget perfectly.  After making the change you suggested, it solved the editor resize problem but now I can't seem to position the editor with CSS as I did before.  I did look at the instructions, and it suggested to possibly add custom css?  I added the code below to my settings.py file and it does not seem to influence the position of the InPlace Widget:
        'css_for_inplace': (
        '/Book/Author/assets/css/mystyle.css',
        ),

**Comment by dunkinman** [comment]
After a clean install of my environment, updated my CSS as shown below:

.spacer84 {
  font-size: 18px;
  margin-left: 24.4rem;
}

Additional settings.py configs were not necessary.  I ultimately used the SummernoteInplaceWidget to enable the resize of the editor in my form and then used the CSS documented above to position the editor on my page with a default font-size of 18.
