### ISSUE TITLE
django-summernote SummernoteInplaceWidget Not Working Locally

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#303]
I was reviewing my django-summernote install this morning and tried to install Summenote locally on my Windows 10 machine.  During this exercise, I realized that I did not need the libraries in my HTML header as part of the django-summenote install.  I had these libraries in my HTML header:

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>

After I removed them from my HTML header, the SummernoteWidget continued to work as normal, but the SummernoteInplaceWidget disappeared altogether.  The only way I can get the SummernoteInplaceWidget to appear is if I add the libraries referenced above back into my HTML header.  Is this normal, expected behavior?  I would prefer to use the SummernoteInplaceWidget for a couple of reasons, but I can't seem to get it to work properly even when I am using the libraries above, I opened up separate issues for my other SummernoteInplaceWidget difficulties.

In this case, I am trying to avoid the CDN libraries and run locally, but without them SummernoteInplaceWidget does not appear.

**Comment by dunkinman** [comment]
After extensive trial and error, it would appear that in order to use the SummernoteInplaceWidget for django-summernote, you need to include the Jquery and bootstrap libraries in order for the SummernoteInplaceWidget to work.  However, I am still not able to get the SummernoteInplaceWidget for django to show editable content in my view.  It shows the editor as desired, but it does not show the content.

**Comment by dunkinman** [comment]
Closing out as my original question was how to get the SummernoteInplaceWidget working locally.  Answer was to make sure both Jquery and Summernote-lite files are referenced in HTML header.  SummernoteWidget does not require these files, but SummernoteInplaceWidget does.

**Comment by OmkarPathak** [comment]
@dunkinman how did you solve this issue? Can you please provide an example how did you include the required jquery and summernote files in HTML head?

**Comment by dunkinman** [comment]
@OmkarPathak I found this code in my code base.  I ultimately went a different direction because Summernote could not meet my requirements, or I couldn't figure out how to get it to do everything I wanted it to do.  However, I believe the code below might help answer your question.            
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
          <script type="text/javascript" src=https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js></script>
          <link rel="stylesheet" href="{% static 'summernote/summernote-lite.css' %}" type="text/css">
          <script src="{% static 'summernote/summernote-lite.js' %}"></script>
           <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
           <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>
