### ISSUE TITLE
django-summernote not appearing if my system is not connected to the internet

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#305]
I was testing django-summernote today, and found that if my system is not connect to the internet, the summernote widget does not appear in my app.  I followed the instructions to install django in my environment to the letter.  If I am connected to the internet, the widget appears.  If not, it does not.  Based on the instructions, all I need to do is pip install django-summernote, define to my app, urls, etc.  The instructions do not indicate that I need to do anything to install django-summernote locally.  I've installed other editors and they work perfectly fine when my system is not connected to the internet.  Please help me understand why this might be!

**Comment by dunkinman** [comment]
This morning, I tried to copy in bootstrap into my config and include it even though my project is not using bootstrap.  I know it's working because my screens are affected by the bootstrap library.  I have the Jquery, summernote, and bootstrap libraries local to my machine, but still no summernote if I am not connected to the internet.  Any thoughts are appreciated.

**Comment by lqez** [comment]
It loads base libraries from the internet before initializing. Summernote is designed to be used while online. But you could use it even you're in offline. Copy https://github.com/summernote/django-summernote/blob/master/django_summernote/settings.py#L103-L120 files into your projects and change paths in settings.
