### ISSUE TITLE
django-summernote not recognizing default CSS font-size parameters

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#306]
I have noticed that when I use the SummernoteWidget in my model form, it is not referencing my custom CSS settings as defined below:

.editor {
font-size: 18px;
margin-left: 24.4rem;
}

I have customized my toolbar by defining my config in the settings.py file, and the toolbar is showing up as expected, but the default font size with the SummernoteWidget is not taking affect as shown below:

![image](https://user-images.githubusercontent.com/30054587/42651154-2e3f2722-85d4-11e8-95e5-6f68e532bf3d.png)

I had received feedback earlier to use CSS as a means of modifiying the default font-size value in the toolbar, but no matter what I do it always stays at 14.  Curiously, the margin-left works as expected. 

Thanks in advance for your thoughts and for all that you do to support this project!

**Comment by lqez** [comment]
Summernote follows the default styling of the page. You don't have to refine it again.

e.g. If you want to change base paragraph `<p>`, then just set styles on it.

```css
p {
  font-size: 18px;
  margin-left: 24.4rem;
}
```

**Comment by dunkinman** [comment]
Could I possibly be experiencing trouble with this because I'm not using bootstrap?  I'm not an expert, but I can figure out CSS pretty good..and adding font-size just doesn't change no matter what I do.  The header always says 14.
