### ISSUE TITLE
django-summernote SummernoteInplaceWidget configuration question

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#307]
Hello,

I've recently spent quite a bit of time reviewing django-summernote and it's capabilities.  From my testing, I've come to the conclusion that using the SummernoteInPlaceWidget and trying to also do images requires that you have to write your own backend for the images, is this accurate?  With the SummernoteWidget, this is not required, and works just fine as a default, but the SummernoteInPlaceWidget does not provide this functionality.  Please confirm my findings.  Thank you!
  
I have tried using the boostrap libraries for my SummernoteInplaceWidget configuration...

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
```

I also tried to use the Summernote-lite libraries for my installation....( I'm not using bootstrap in my project at all and would prefer this route )

```
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>
```

In both cases, when I drag and drop an image on the editor, I receive the following error in my console...

![summernote1000](https://user-images.githubusercontent.com/30054587/43284589-e559d7c8-90e1-11e8-9525-a700efea764b.PNG)

I'm just trying to make sure I understand what is required in order for the SummernoteInplaceWidget to be able to accept images in the same way the SummernoteWidget does.  

Thank you for this project and all that you do to support it!

**Comment by lqez** [comment]
It looks like you may omit `{{ form.media }}`.
django-summernote needs https://github.com/summernote/django-summernote/blob/master/django_summernote/settings.py#L128-L132 as base libraries. 

If you don't want to use `{{ form.media }}`, please loads base libraries manually.
