### ISSUE TITLE
SummernoteInplaceWidget does not place origin text

### ISSUE THREAD

**Issue by teripak** [summernote/django-summernote#311]
version : 0.8.8.7
Django 1.11.7

I changed widget to SummernoteInplaceWidget from SummernoteWidget to use fullscreen mode.
And I couldn't open my saved text into editor with SummernoteInplaceWidget and I found that there is code to make it place to editor in function initSummernote_{{ id }}() in widget_common.html.
In that function, there is a code like "$sn.html(origin.value);" in iframe mode, but there is no such a code for not-iframe mode.
Creation is OK with CreateView, but Update is not ok with UpdateView because the editor is not populating the text in the textarea field.

Edit:
I found old issue [here ](https://github.com/summernote/django-summernote/issues/289) and the bug has been fixed with changing 2 lines. But it seems not to be reflected to the master branch.
It it still not fixed at the moment?

**Comment by lqez** [comment]
Closed by #287, thanks.
