### ISSUE TITLE
Django SummernoteInplaceWidget Question

### ISSUE THREAD

**Issue by dunkinman** [summernote/django-summernote#314]
I have been playing with various configurations, and can't quite get the SummernoteInplaceWidget to work properly on my machine.  I am running Windows10 and can get the basic SummernoteWidget to work with Django.  However, I can't seem to get the SummernoteInplaceWidget to work.  I am not using the Bootstrap libraries and my understanding is that the straight Django-Summernote widget does not require them.  I can get the SummernoteWidget to work without any additional libraries, but it would appear that perhaps the SummernoteInplaceWidget requires either the Bootstrap libraries or the Summernote-Lite libraries.  Is this accurate?

**Comment by lqez** [comment]
Yes, you've got the point. Summernote was built on Bootstrap 3 and now it supports Bootstrap4 and lite mode. `SummernoteInplaceWidget` was designated to be used in (literally) Bootstrapped-site. But django-summernote also supports `SummernoteWidget` (which uses `iframe`) for non-bootstrap site. So,
 - If your site uses Bootstrap 3/4 already, then you can use `SummernoteInplaceWidget` without additional libraries.
 - If not, then I recommend you to use `SummernoteWidget`.
