### ISSUE TITLE
Stop adding http:// to urls

### ISSUE THREAD

**Issue by stefko18** [summernote/django-summernote#315]
Hello, 

when I add a relative url like '/some-category/my-article/' the editor keeps prepending "http://" to it. Which breaks the url and I have to go in to source mode and fix it there. Which again is extremly annoying as the source is not prettyfied ... so how to stop this?

Thank you for any ideas.

**Comment by lqez** [comment]
This is related with https://github.com/summernote/summernote/issues/1037. A pretty old issue.
You have to customize the callback function for now. I know that it's very annoying.

**Comment by claudep** [comment]
Everyone was waiting for you to provide the patch :-)

**Comment by lqez** [comment]
OK, I just wrote it: https://github.com/summernote/summernote/pull/2933
But I'm not sure when it gonna be merged.

**Comment by lqez** [comment]
The previous PR had been merged, ready to serve ...

**Comment by lqez** [comment]
Closed by https://github.com/summernote/django-summernote/pull/320

**Comment by ajrbyers** [comment]
I've just upgraded to the latest version of django-summernote via PIP and don't see this option, am I doing something wrong?
