### ISSUE TITLE
Multiple forms

### ISSUE THREAD

**Issue by frague59** [summernote/django-summernote#317]
Hi, 
I'm using django-summernote (0.8.8.8) on a 1.11.15 Django instance, and I've multiple forms on the same page, and one with summernote (inplace).

The widget is actually rendered in ANOTHER form.

If I uses the iframe summernote, the original in displayed before the summernote widget (the textarea is not hidden).

How can I force the widget rendering into the right form ?
Thanks !

**Comment by lqez** [comment]
As you see https://github.com/summernote/django-summernote/blob/61ba865b72533d84c363937556497ea35e119f34/djs_playground/views.py#L8-L20, you can choose which fields will be rendered with Summernote.

Please reopen again with your form code. Thanks.
