### ISSUE TITLE
Youtube Video link not working on new version summernote 

### ISSUE THREAD

**Issue by dejavu88** [summernote/django-summernote#319]
This feature was working fine on the old version but couldn't install the older one now. Adding YouTube  link shows the frame but doesn't play the video . I'm using Django 1.11.

**Comment by lqez** [comment]
I'll test it out.

**Comment by lqez** [comment]
I failed to reproduce it. YouTube embedding was successful not just on BS3, even on BS4 and Lite UI.

**Comment by dejavu88** [comment]
@lqez I really don't know what happened but I reinstalled the package and it's working fine now ......thanks for the support!
