### ISSUE TITLE
Uncaught TypeError: undefined is not a function textarea.value = $(this).code();

### ISSUE THREAD

**Issue by ramusus** [summernote/django-summernote#32]
I have error on this line https://github.com/lqez/django-summernote/blob/master/django_summernote/templates/django_summernote/widget_inplace.html#L14:

```
Uncaught TypeError: undefined is not a function (index):109
$.summernote.onblur (index):109
b.event.dispatch jquery.js:6495
v.handle

textarea.value = $(this).code();
```

What is this plugin? Hard to find by the name of method.

**Comment by stwhh** [comment]
I use summernote,but it has error 'Uncaught TypeError: $(...).summernote is not a function'.My jquery version is 2.13,bootstrap version is 3.35.I don't know what's problem.I use local js and css files ,it can't work.But i use online js and css files ,it works.
