### ISSUE TITLE
Full screen in admin panel dose not work

### ISSUE THREAD

**Issue by Przemek625** [summernote/django-summernote#323]
I implemented django-summernote in my app. I did everything as documentation says.

This is part of my code in `admin.py`

```
class InlineEnrolmentTour(admin.TabularInline):
    model = EnrolmentTour
    exclude = ['ended']
    form = EnrolmentTourForm


class AdminCourse(SummernoteModelAdmin):
    # form = CourseForm
    inlines = [InlineEnrolmentTour]
    list_display = ('name', 'course_type')
    summernote_fields = ('description', )
```

Unforutely the full screen button dosent do its job.

**Comment by lqez** [comment]
`SummernoteWidget` uses `iframe` to display summernote editor. Currently, it could not be expanded its editor over the iframe window. I'll try it later. Thanks.

**Comment by lqez** [comment]
Latest version `0.8.11.2` fixed this problem.
Thanks, @Przemek625 !

**Comment by Przemek625** [comment]
@lqez This is a great message! Thank you buddy!
