### ISSUE TITLE
How to not load Django Summernote Attachments on the Admin page?

### ISSUE THREAD

**Issue by aleon05** [summernote/django-summernote#329]
I want to be able to configure on the settings.py a settings that does not load at all the `Django Summernote Attachments` option.  

How do I do that?

**Comment by lqez** [comment]
I think you might forget to add `django_summernote` module within your `INSTALLED_APPS`.

**Comment by aleon05** [comment]
No I did not forgot to add that module in the INSTALLED_APPS.

And if I remove it, an error comes up.

**Comment by lqez** [comment]
@aleon05 Sorry, I misunderstood your question.
I think there is a lot of ways to hide specific model from admin, but I tried below and succeed.

```python
# Do below somewhere in your own admin.py
from django_summernote.utils import get_attachment_model 
admin.site.unregister(get_attachment_model())
```

**Comment by saileshkush95** [comment]
> @aleon05 Sorry, I misunderstood your question.
> I think there is a lot of ways to hide specific model from admin, but I tried below and succeed.
> 
> ```python
> # Do below somewhere in your own admin.py
> from django_summernote.utils import get_attachment_model 
> admin.site.unregister(get_attachment_model())
> ```
> 
> Another ways: https://stackoverflow.com/questions/2431727/django-admin-hide-a-model


Sorry to saythat this is not working

**Comment by Dinmukhamet** [comment]
It worked for me

**Comment by arjun-gautam** [comment]
Worked for me also. Thanks

**Comment by DAVIDhaker** [comment]
More correct way is:
```python
from django.apps import AppConfig
from django.contrib import admin
from django_summernote.utils import get_attachment_model


class YourMainConfig(AppConfig):
    def ready(self):
        admin.site.unregister(get_attachment_model())
```
In your project/app/apps.py
