### ISSUE TITLE
Have to paste a link twice (?) into Image url in order for "Insert Image" button to become active  

### ISSUE THREAD

**Issue by boryskuczkowski** [summernote/django-summernote#333]
Anyone experiences the same behaviour?

**Comment by boryskuczkowski** [comment]
To be precise - when pasting link with the use of mouse (the link is not pasted with keyboard)

**Comment by lqez** [comment]
I think this is not a django-summernote problem. If you have any question on Summernote itself, please visit https://github.com/summernote/summernote instead of here.
