### ISSUE TITLE
code style missing

### ISSUE THREAD

**Issue by gvm2121** [summernote/django-summernote#334]
Hi, i did install django-summernote to render code and the "code" style is missing.
![image](https://user-images.githubusercontent.com/43762832/47688537-9b471500-dbc4-11e8-8ed6-578603a36a64.png)

i need it style. 
why i am doing wrong?
thanks.

**Comment by lqez** [comment]
Please check `styleTags` of your settings.
Default value is `styleTags: ['p', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']`;
https://github.com/summernote/summernote/blob/develop/src/js/bs3/settings.js#L123

**Comment by gvm2121** [comment]
ok, but it doesnt work on bs4. You sendme bs3 settings. thanks
