### ISSUE TITLE
Image rotation issue on images uploaded from iOS device and vertical photos showing up horizontally

### ISSUE THREAD

**Issue by boryskuczkowski** [summernote/django-summernote#336]
I have encountered this issue while testing a site, there was a known issue with PIL which didn't read EXIF data correctly from Imagefield which I addressed in my app. However I realized that the issue persist with images uploaded to summernote field and it only occures with images uploaded from iOS devices. So the pictures are rotated randomly and I can't figure out how to address this issue.
Any ideas?

Drag&drop doesn't work (?), also get warnings for photos which are rotated:
TiffImagePlugin.py:<number here>: UserWarning: Possibly corrupt EXIF data. 
or
TiffImagePlugin.py:<number here>: UserWarning: Corrupt EXIF data.

And the following pertains ALL devices - portrait photos shown horizontally.

**Comment by lqez** [comment]
Thank you for using django-summernote. 
However, as you already knew, this is not a django-summernote issue.
There are several solutions to this. One of XRef: https://stackoverflow.com/questions/13872331/rotating-an-image-with-orientation-specified-in-exif-using-python-without-pil-in

**Comment by boryskuczkowski** [comment]
Sorry, I might be mistaken but I think it is related to summernote-django. The solutions you mentioned are dealing with instances of django imagefield. It specifically targets field which has image in it, while summernote is using its own widget and comprises of many elements and not only images. 

I am not very sure how would I implement any of these solutions in relation to summernote, could you give me a hint please?
