### ISSUE TITLE
Deleted font sumernote.eot still referenced

### ISSUE THREAD

**Issue by tjwalch** [summernote/django-summernote#342]
The font file `summernote.eot` has been removed but it is still referenced by `summernote.css`.

**Comment by lqez** [comment]
Thanks for reporting. I'm handling this now...

**Comment by lqez** [comment]
Found a related issue: https://github.com/sapegin/grunt-webfont/issues/367

**Comment by lqez** [comment]
Just released `0.8.11.1`. Thanks!
