### ISSUE TITLE
SummernoteInplaceWidget rendering broken when upgrading from 0.8.10.0

### ISSUE THREAD

**Issue by jmsmkn** [summernote/django-summernote#343]
The rendering of `SummernoteInplaceWidget` is broken with the latest major version. We're using bootstrap4 with django-crispy-forms, in v0.8.10.0 the rendering is ok:

<img src="https://user-images.githubusercontent.com/12661555/50593184-9427d600-0e97-11e9-90e4-83685f7cccd5.png" width="200px">

but when upgrading to v0.8.11.2 the editable area renders over the save button:

<img src="https://user-images.githubusercontent.com/12661555/50593303-1912ef80-0e98-11e9-8f60-97b94b516207.png" width="200px">

Thank you for your work on this excellent package.

**Comment by lqez** [comment]
Thank you for using Summernote and django-summernote.
I successfully reproduce the problem with the latest release.

**Comment by lqez** [comment]
Fixed in `0.8.11.3`. You can now unpin it, thanks!
<img width="912" alt="screen shot 2019-01-04 at 5 44 07 pm" src="https://user-images.githubusercontent.com/579366/50679808-61710f80-1048-11e9-9819-4108846444f8.png">

**Comment by jmsmkn** [comment]
Perfect, thank you!
