### ISSUE TITLE
color list

### ISSUE THREAD

**Issue by ntawfik** [summernote/django-summernote#350]
I want to give the user certain colors to choose from. 
So can I customize the color list? ['color', ['color']]

**Comment by lqez** [comment]
You can customize the color table by modifying https://github.com/summernote/summernote/blob/develop/src/js/base/settings.js#L139-L160

In django-summernote, it can be done by putting it within `summernote` section.
```python
SUMMERNOTE_CONFIG = {
    'summernote': {
        'colors': [ ... ],
        'colorNames': [ ... ],
    },
}
```
