### ISSUE TITLE
not full path to uploaded media

### ISSUE THREAD

**Issue by Przemek625** [summernote/django-summernote#351]
I use default configuration of `django-summernote` I am using it with rest DRF. 
```
{
  "id": 1,
  "title": "ABC",
  "section": "abc",
  "urlKey": "url_key",
  "content": "<p>Coś o poradniku zawodowym :)!</p><p><img src=\"/media/django-summernote/2019-03-20/70447090-363a-484c-8f4c-b691a821e3cb.jpg\" style=\"width: 50%; float: right;\" class=\"note-float-right\"></p>"
}
```
It doesnt return full location to resource on server.

How to make library to return full url like this:
`http://127.0.0.1:8000/media/django-summernote/2019-03-20/70447090-363a-484c-8f4c-b691a821e3cb.jpg`

**Comment by lqez** [comment]
Fixed by #352. Thanks for your suggestion.

**Comment by Przemek625** [comment]
@lqez Wow, that is great!

**Comment by Przemek625** [comment]
@lqez did you add the new settings option to docs?

**Comment by lqez** [comment]
@Przemek625 Ooops, not yet. It would be much appreciated if you can add it to README. 👍

**Comment by Przemek625** [comment]
@lqez Yup, I can add this to readme! :)
