### ISSUE TITLE
complete the README about attachment_absolute_uri option

### ISSUE THREAD

**Issue by Przemek625** [summernote/django-summernote#353]
The README is missing the info about 'attachment_absolute_uri' option

**Comment by Przemek625** [comment]
@lqez Can You assign me the issue? I would like to resolve it.

**Comment by Przemek625** [comment]
By fault. I choosed the wrong project hehe

**Comment by Przemek625** [comment]
@lqez Can you assign the task to me? I would like to resolve it :)

**Comment by lqez** [comment]
Closed by https://github.com/summernote/django-summernote/commit/45ca8dfc55b50f5bb596796c7798b4198f0df73a. Thank you, @Przemek625 !
