### ISSUE TITLE
Django 3.0 deprecation warnings

### ISSUE THREAD

**Issue by amureki** [summernote/django-summernote#355]
Greetings!

Thank you for the great package!

I just discovered while using it the next warning:
```
/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django_summernote/widgets.py:26
  /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django_summernote/widgets.py:26: RemovedInDjango30Warning: django.contrib.staticfiles.templatetags.static() is deprecated in favor of django.templatetags.static.static().
    'language': static('summernote/lang/summernote-' + lang + '.min.js'),
```

Could we consider fixing it at some point?
My versions stack:
Python 3.6.7
Django==2.1.7
django-summernote==0.8.11.4

Thanks!

**Comment by lqez** [comment]
Thank you for using django-summernote. Could you make a pull request for this? Django says it will be deprecated from `3.0`. You can find out how to prepare on https://docs.djangoproject.com/en/dev/releases/2.1/#features-deprecated-in-2-1
