### ISSUE TITLE
InlineWidget throws JS Errors, normal widget does not

### ISSUE THREAD

**Issue by faulander** [summernote/django-summernote#358]
Using Django 2.2:

in my forms.py:
```
class NewReply(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ('message',)
        widgets = {
            'message': SummernoteWidget(),
        }

```
this works as can be seen in the screenshot:
![image](https://user-images.githubusercontent.com/38588197/56730745-f4999680-6758-11e9-85e0-cc88e60953e8.png)

when i change to "SummernoteInplaceWidget" i get several JS Errors, like it can be seen on the screenshot:
![image](https://user-images.githubusercontent.com/38588197/56730805-1e52bd80-6759-11e9-9e5d-96354ac4dcbf.png)

What am i doing wrong?

**Comment by lqez** [comment]
For InplaceWidget, you have to include jQuery by manually.
