### ISSUE TITLE
Is it possible to pass a string to summernote editor once it has been instantiated via {{form.comment}}

### ISSUE THREAD

**Issue by PJ03029174** [summernote/django-summernote#359]
Hi, I've been using the SummernoteWidget in my form and its working really well I'm manually typing text into the widget. I'm trying to insert text client side via javascript and I can't get the widget to display the text. Is this possible? Thanks, I'd really appreciate the help as I've been stuck a few days.

**Comment by lqez** [comment]
Yes, sure, you can. Just call [insertion APIs of Summernote](https://summernote.org/deep-dive/#insertion-api).
Thank you for using.
