### ISSUE TITLE
URLs expire

### ISSUE THREAD

**Issue by jasonhoward64** [summernote/django-summernote#360]
I'm using S3 to server my static files. I'm currently running version 2.48 of boto.

When I upload images into the summernote widget, the images appear, but the URLs that represent the images expire after 1 hour. None of any of the other images that I upload to my site, which are served via AWS S3, have this problem. 

Do you know what might be the cause of these expiring URLs and how I can fix it?

Thanks!

**Comment by lqez** [comment]
This problem might be caused by django storage extensions. Please refer the document of extensions for setting expiration of stored objects.
XRef: https://stackoverflow.com/questions/47774081/set-never-expire-on-amazon-s3-object
