### ISSUE TITLE
Dropping an image into my form submits the form

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#362]
I have an inplace summernote widget for leaving comments. If I drag and drop a picture onto the form, it appears in the widget, cool.  But in addition to uploading the image, it's also posting my form in the background and that's causing duplications of comments.  It's shows 404, but the comment is still appearing somehow (why is it submitting the form anyway?)
```
[08/May/2019 21:53:14] "POST /summernote/upload_attachment/ HTTP/1.1" 200 185
Not Found: /quests/submission/15/complete/
[08/May/2019 21:53:15] "POST /quests/submission/15/complete/ HTTP/1.1" 404 1772
[08/May/2019 21:53:15] "GET /media/django-summernote/2019-05-08/3485d494-cc80-4438-b769-67345ad9bdd8.png HTTP/1.1" 200 7085
```
My form doesn't visibly change except for the picture appearing.  But if I submit, it ends up being submitted twice (or if I cancel without submitting, it's already been submitted once).

Actually, If I keep dropping new images into the form, it submits the form (in secret) for every image.  So I end up with tons of extra comments!

Any idea why this might be happening or how I can prevent it?

**Comment by tylerecouture** [comment]
I was able to work around the problem by checking the value of the submit button (which doesn't exist when summernote submits the form).  However, I still don't understand why summernote is submitting the form at all.

**Comment by lqez** [comment]
Sorry for bothering you. Could you record a screencast for this situation? (with logs of django runserver together)

**Comment by tylerecouture** [comment]
https://youtu.be/Th1upRLjdic

**Comment by tylerecouture** [comment]
Note that I am still stuck on django 2.0.x and django-summernote==0.8.8.6 due to this problem: https://github.com/summernote/django-summernote/issues/344

**Comment by tylerecouture** [comment]
This seems to be fixed now?  At least now that I've upgrade to django 2.2 and the latest django-summernote.
