### ISSUE TITLE
images are appearing in request.FILES resulting in duplicate upload

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#363]
I have a form with a `SummernoteInplaceWidget`.  When I add an image with the image button on the menu, the image is uploaded in the background by summernote, but it's also added to `request.FILES`.

Because my form also has a file field (for uploading non-image files).  The summernote images end up getting uploaded twice.  Once by summernote when the image is added, and once again by my code that saves the `request.FILES`.
```
# forms.py
class SubmissionForm(forms.Form):
    comment_text = forms.CharField(label='', required=False, widget=SummernoteInplaceWidget())

    files = RestrictedFileFormField(required=False,
                                    max_upload_size=16777216,
                                    widget=forms.ClearableFileInput(attrs={'multiple': True}),
                                    label="Attach files",
                                    help_text="Hold Ctrl to select multiple files, 16MB limit per file")
```

```
# views.py
@login_required
def submit(request, submission_id):
    ...

    if request.method == "POST":
        form = SubmissionForm(request.POST, request.FILES)

        if form.is_valid():
            ...

            if request.FILES:
                # This re-saves the summernote images a second time, along with other files from the field field.
                file_list = request.FILES.getlist('files')
                for afile in file_list:
                    newdoc = Document(docfile=afile, comment=comment_new)
                    newdoc.save()

        ...
```

Is there a way I can differentiate the files added into the summernote widget vs the files added using the field field widget? Or a way to prevent the images from being added to `request.FILES`

**Comment by lqez** [comment]
Thank you for reporting. I successfully regenerated this problem.

**Comment by lqez** [comment]
Fixed by https://github.com/summernote/django-summernote/commit/f113f39facb608509c0647658958c2da0020f756
This will be shipped with next release, thanks!
