### ISSUE TITLE
Unable to add font

### ISSUE THREAD

**Issue by jasonhoward64** [summernote/django-summernote#369]
I'd like to add some Google fonts to django-summernote as selectable fonts. I've loaded the font within the html file. I know that I'm doing this correct as the the rest of the text on the page uses this font (i.e. Questrial)

I then go into my settings file and add Questrial to the 'fontname' line

SETTINGS_DEFAULT = {
    'iframe': True,
    'airMode': False,
    'empty': ('<p><br/></p>', '<p><br></p>'),

    'width': 720,
    'height': 480,
    'toolbar': [
        ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'superscript', 'subscript',
                  'strikethrough', 'clear']],
        ['fontname', ['fontname', 'Questrial']],
        ['fontsize', ['fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['height', ['height']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video', 'hr']],
        ['view', ['fullscreen', 'codeview']],
        ['help', ['help']],
    ],
Even with this change, I don't have the ability to select the Questrial font in the summernote widget.

Any help would be appreciated.

Thanks!

**Comment by lqez** [comment]
Summernote tests each font (whether exist or not) before adding. Please put custom web font names in `fontNamesIgnoreCheck` either.
Ref: https://summernote.org/deep-dive/#custom-fontnames
