### ISSUE TITLE
Disabling attachment feature not working?

### ISSUE THREAD

**Issue by niccolomineo** [summernote/django-summernote#372]
I added

`SUMMERNOTE_CONFIG = {
    'disable_attachment': True
}`

and did `makemigrate` / `migrate`, but I don't seem to notice any changes.

Shouldn't it disable the feature (including removing the "Django Summernote" module link from the admin home)?

**Comment by claudep** [comment]
It seems to be very hard to really disable attachments (and drag and drop) with Summernote. However this is a pure summernote issue, not related to django-summernote IMHO.
