### ISSUE TITLE
how to change toolbar

### ISSUE THREAD

**Issue by tenji73** [summernote/django-summernote#373]
first of all: FANTASTIC PLUGIN! great work. thanks guys!

however..  i was trying to change the items in the toolbar in the SUMMERNOTE_CONFIG
`
SUMMERNOTE_CONFIG = {
    'js': (
        '$("#summernote").summernote({toolbar: [["style", ["bold", "italic", "underline", "clear"]]]});'
        ),
}
`
but i am getting the "can only concatenate tuple (not "str") to tuple" error.. what is the right way to do this?

thank you!
tom

**Comment by tenji73** [comment]
ok. got it... :-)
just in case anybody has the same issue:
`
SUMMERNOTE_CONFIG = {
    'summernote': {'toolbar': ['bold', 'italic', 'underline', 'clear', 'fontsize', 'ul', 'ol', 'paragraph']},
}
`

**Comment by jaradc** [comment]
This REALLY needs to be in the github getting started readme. Isn't this like, the very first question someone would have after installing? Sure, there's a link to a page with jQuery solutions but that's not obvious how to implement when getting started. Please take this as feedback.

**Comment by lqez** [comment]
Just updated.
https://github.com/summernote/django-summernote/commit/c3cbb00f19db67aee466c435d076c5390236fb73
