### ISSUE TITLE
Release Django-summernote

### ISSUE THREAD

**Issue by claudep** [summernote/django-summernote#375]
I would much appreciate having a new release of django-summernote, as the current release is not compatible with Django 3.0 (commit 8b57e507ec5 fixed that).

**Comment by lqez** [comment]
I hope we could release it within this Oct.

There is a sprint event in Seoul. I will try to release it at the event.
Just FYI: https://www.sprintseoul.org

**Comment by claudep** [comment]
Thanks. That looks like a great event, a bit far from my home unfortunately :smile:

**Comment by adrianglazer** [comment]
Hi Iqez! I would really appreciate a new release also. Kind regards!

**Comment by lqez** [comment]
Done! Thank you all for waiting. Sorry for blocking.
