### ISSUE TITLE
Editor not loading for inline TextField

### ISSUE THREAD

**Issue by oromero** [summernote/django-summernote#38]
Summernote is not loading for an inline model admin.

I have an inline model:

``` python
class ModelAInline(admin.StackedInline, SummernoteInlineModelAdmin):
    model = ModelA
    extra = 1

class ModelBAdmin(SummernoteModelAdmin):
    ...
    inlines = [ModelAInline]

admin.site.register(ModelB, ModelBAdmin)
```

ModelB has a TextField which is loading with summernote widget correctly. ModelA has a TextField but it's not loading correctly, it just displays a white section, iframe doesn't seem to be loading.

I found the following JS warnings on console:

``` javascript
ReferenceError: content_iframe is not defined
ReferenceError: __prefix__ is not defined
```

Both JS errors point to line "32 > eval:1", referring, I think, to:

```
eval("settings = window.parent.settings_id_modela_set-0-content/ line 32 &gt; eval_iframe;");
```

I'am using version 0.5.12

**Comment by willplaehn** [comment]
Not sure if a nice solution is out there since the issue is rather old, but I wrote a javascript snippet that interfaces with the hooks in `django/admin/static/admin/js/inlines.js`. It can be easily included by extending `change_form.html` and adding between script tags.

django-summernote = 0.8.6
Django = 1.10.4

I believe this meets the use case @oromero laid out for the standard admin inlines:

```
(function($){
    var updateIframeIndex = function(el, prefix, index) {
        var id_regex_underscore = new RegExp("(" + prefix + "_(\\d+|__prefix__))");
        var id_regex_hyphen = new RegExp("(" + prefix + "-(\\d+|__prefix__))");
        var us_replacement = prefix + "_" + index;
        var hyph_replacement = prefix + "-" + index;
        el.prev().html(el.prev().html().replace(id_regex_underscore, us_replacement));
        $.globalEval(el.prev().html());
        if (el.attr('id')) {
            el.attr('id', el.attr('id').replace(id_regex_underscore, us_replacement));
        }
        if (el.attr('src')) {
            el.attr('src', el.attr('src').replace(id_regex_hyphen, hyph_replacement));
        }
    };
    $(document).on('formset:added', function(e, row, prefix){
        var totalForms = $("#id_" + prefix + "-TOTAL_FORMS").prop("autocomplete", "off");
        var iframe_selector = '#id_' + prefix + '_' + '__prefix__' + '_body_iframe'
        updateIframeIndex($(iframe_selector), prefix, totalForms.val() - 1);
    });
    $(document).on('formset:removed', function(e, row, prefix) {
        var iframe_selector = 'iframe[id^=id_' + prefix + '_][id$=_body_iframe]';
        var iframe_extra_selector = '#id_' + prefix + '___prefix___body_iframe';
        $(iframe_selector).not(iframe_extra_selector).each(function( index ) {
            updateIframeIndex($(this), prefix, index);
        });
    });
})(django.jQuery);
```

The challenge in working with the admin inlines is that `inline.js` re-indexes everything when inlines are added or removed.

I think the selectors in this code snippet have to be carefully reviewed in more scenarios, but this might be the basis for a solution.

**Comment by willplaehn** [comment]
[Django admin JS customization documentation here](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/javascript/)

**Comment by lqez** [comment]
<img width="1017" alt="screen shot 2018-02-22 at 2 53 59 pm" src="https://user-images.githubusercontent.com/579366/36522834-096b96b6-17e2-11e8-9ed2-b90cc05098ca.png">
Sorry for letting this issue alone, but it looks like fine now.
