### ISSUE TITLE
django-summernote breaks after upgrading to Django 3

### ISSUE THREAD

**Issue by mpibpc-mroose** [summernote/django-summernote#381]
After upgrading my app to Django 3 I get the following error:

```
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/source/lib/models.py", line 8, in <module>
    from django_summernote.widgets import SummernoteInplaceWidget
  File "/usr/local/lib/python3.7/site-packages/django_summernote/widgets.py", line 4, in <module>
    from django.contrib.staticfiles.templatetags.staticfiles import static
ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'
```
regarding to https://docs.djangoproject.com/en/dev/internals/deprecation/ that module was removed.

After investigation of the Django sources replacing should be easy:

```
# django 2.x django\contrib\staticfiles\templatetags\staticfiles.py
def static(path):
    warnings.warn(
        'django.contrib.staticfiles.templatetags.static() is deprecated in '
        'favor of django.templatetags.static.static().',
        RemovedInDjango30Warning,
        stacklevel=2,
    )
    return _static(path)
```

I think the problem may be that the package at https://pypi.org/project/django-summernote/ is outdated. It dates from January 2019. As the problem ist already fixed in the summernote sources only a new package needs to get published.

**Comment by ronaldgrn** [comment]
try using the latest version

```
https://github.com/summernote/django-summernote.git@702b574920342766f56262725d87125719156878#egg=django_summernote
```

**Comment by mpibpc-mroose** [comment]
I understand that this is a possible solution. But I do not understand, why the package maintainer stopped to publish updates via pypi?

**Comment by ronaldgrn** [comment]
life happens I guess. I'm just happy it works at all and I didn't have to patch it myself :)

**Comment by ismaemahh** [comment]
> try using the latest version
> 
> ```
> pipenv install git+https://github.com/summernote/django-summernote.git@702b574920342766f56262725d87125719156878#egg=django_summernote
> ```

I tried your solution and python manage.py runserver worked, but in the form, a field that I use summernote shows a  messsage "127.0.0.1 access is refused". Do you know how to fix this? thanks
![issue_summernote](https://user-images.githubusercontent.com/56642544/70804832-3b92d580-1d96-11ea-9a10-cfcc18b00d65.JPG)

**Comment by pip182** [comment]
I'm having the exact same problem as ismaemahh...

**Comment by mimi89999** [comment]
@ismaemahh https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-X_FRAME_OPTIONS https://docs.djangoproject.com/en/3.0/ref/clickjacking/

**Comment by mimi89999** [comment]
@lqez Is it a good idea to set `X-Frame-Options: sameorigin` in _summernote_?

**Comment by htrampe** [comment]
He guys,
while installing summernote with pip i've got the error, that staticfields.templatetags are missing. These packages were removed in django 3.0, so i'am not able to install the editor. No change with the latest version. Help would be grate, thx!

**Comment by lqez** [comment]
I just published `0.8.11.5` with Django 3.0 support.
https://github.com/summernote/django-summernote/releases/tag/0.8.11.5

**Comment by Khumoyun098** [comment]
Who knows alternative module of django-summernote? I want use it for Django 3.1

**Comment by marobo** [comment]
Add this `X_FRAME_OPTIONS = 'SAMEORIGIN'` to your settings.py
[See](https://github.com/summernote/django-summernote)

**Comment by anandabayu** [comment]
> Add this `X_FRAME_OPTIONS = 'SAMEORIGIN'` to your settings.py
> [See](https://github.com/summernote/django-summernote)

It's solve the problem, thanks

**Comment by binaryeast** [comment]
I think we should write this on README.

Thanks to all!

> Add this `X_FRAME_OPTIONS = 'SAMEORIGIN'` to your settings.py
> [See](https://github.com/summernote/django-summernote)
