### ISSUE TITLE
SummernoteModelAdmin adding a required File field.

### ISSUE THREAD

**Issue by MrTj458** [summernote/django-summernote#383]
When I add the SummernoteModelAdmin to my model it is adding a required 'File' field at the bottom of the admin page. Am I doing something wrong?

Without SummernoteModel Admin:
<img width="864" alt="Screen Shot 2019-12-20 at 11 17 23 AM" src="https://user-images.githubusercontent.com/12666122/71281123-6216ba80-231a-11ea-93a2-94318244d64d.png">

With SummernoteModelAdmin:
<img width="964" alt="Screen Shot 2019-12-20 at 11 16 38 AM" src="https://user-images.githubusercontent.com/12666122/71281156-6f33a980-231a-11ea-9aee-2622904ebc54.png">

Here is my admin.py:
```
from django.contrib import admin
from django_summernote.admin import SummernoteModelAdmin
from . import models


class RecipientModelAdmin(SummernoteModelAdmin):
    summernote_fields = ('text',)


admin.site.register(models.Sponsor)
admin.site.register(models.Recipient, RecipientModelAdmin)
```

And here is my model:
```
class Recipient(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='recipients/')
    text = models.TextField()

    def __str__(self):
        return self.name
```

**Comment by lqez** [comment]
Thank you for reporting. I'll check it.

**Comment by maddrum** [comment]
I saw that there is a solution for this in gihub, already. Thank you for that!
Will there be a new version in pypl with that bugfix?

**Comment by lqez** [comment]
HOTFIX just uploaded. Sorry about that.
https://github.com/summernote/django-summernote/releases/tag/0.8.11.6
