### ISSUE TITLE
Plugin works in summernote, but not django-summernote?

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#385]
Since upgrading to Django 2.2 and django-summernote 0.8.11.6 several of my Summernote add ons have stopped working.

For example, [summernote-table-styles](https://github.com/tylerecouture/summernote-table-styles) which works no problem in summernote<=0.8.12, as shown [in this live example](https://rawgit.com/tylerecouture/summernote-table-styles/master/Example/example.html):

But in my django app the extension's TableStyles button doesn't even appear.
```
    'popover': {
        'table': [
            ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
            ['delete', ['deleteRow', 'deleteCol', 'deleteTable']],
            ['custom', ['tableStyles']]
        ],
    },
```

Here are the django app (left) and raw summernote side by side, both with same extension, and same jquery versions (3.4.1):
![image](https://user-images.githubusercontent.com/10604391/72574234-3507ea00-387d-11ea-9877-6fd83239dfa2.png)

I can't figure out the problem, could you give me a tip on how to troubleshoot this?  The extension is loading, at least the js is in the page and runs when the page loads...

**Comment by tylerecouture** [comment]
Any thoughts on this? I just revisted and still can't get this to work.  All of my summernote plugins that use a popover are broken in django-summernote

**Comment by lqez** [comment]
@tylerecouture Sorry for late replying. I'll check it with your [plugin](https://github.com/tylerecouture/summernote-table-styles).

**Comment by tylerecouture** [comment]
Any luck?

**Comment by lqez** [comment]
It displayed well by adding `summernote-table-styles.js` in `settings.py`.
<img width="943" alt="Screen Shot 2020-05-23 at 5 50 02 AM" src="https://user-images.githubusercontent.com/579366/82708461-4775b280-9cb9-11ea-8285-a886bb64daef.png">

But Summernote does not handle the click event within its popovers. Table popover itself and table-styles dropdown were hided after clicking the table style button. 
Xref: https://github.com/summernote/summernote/pull/3429

So I made a patch for this.
https://github.com/summernote/summernote/pull/3741

**Comment by lqez** [comment]
Anyway, the plugin was well loaded and worked properly. So I'm closing this.
