### ISSUE TITLE
plugin list-of-links not appearing

### ISSUE THREAD

**Issue by jacopsd** [summernote/django-summernote#386]
Tried to enable list-of-links plugin

Settings:
```
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'width': '100%',
    'height': '400',
    'toolbar': [
...
        ['insert', ['link', 'list-of-links']],
...
        ['misc', ['print', 'help', ]],
    ],

    'js': (
        '/static/summernote_plugins/summernote-ext-print.js',
        '/static/summernote_plugins/summernote-list-of-links.js',
    ),

```

While the ext-print plugin works fine, list-of-links just does not appear at all.
No errors appear on chrome console.
How can this be debugged?

**Comment by sg3-141-592** [comment]
I've tried to re-create but working for me.

Details of what I've done in-case it gives you a clue to what the issue is.
- My environment is Python 3.6.8, Django 2.2.6
- I downloaded summernote-list-of-links from [https://github.com/lespoupeesrusses/summernote-list-of-links/blob/master/summernote-list-of-links.js](https://github.com/lespoupeesrusses/summernote-list-of-links/blob/master/summernote-list-of-links.js). There was a note on the repo saying it needed Bootstrap so I included that into my template.
- I created a file data.json in the static directory.
- Updated settings.py to add
```
SUMMERNOTE_CONFIG = {
...
   'toolbar': [
...
      ['insert', ['list-of-links']],
...
   ],
   'listOfLinks': {
       'listUrl': '/static/data.json',
    }
...
   'js': (
        '/static/summernote/summernote-ext-print.js',
        '/static/summernote/summernote-list-of-links.js',
    ),
    'js_for_inplace': (
        '/static/summernote/summernote-ext-print.js',
        '/static/summernote/summernote-list-of-links.js',
    ),
```
And that was it. Worked first time. Neat little extension I'd not seen before.

**Comment by jacopsd** [comment]
Thank you for your help.
With these settings, and starting all over I am seeing the plugin button now.

However, the options 'listOfLinks': {} are not passed to the js code of the plugin, so it doesn't get the listUrl, causing the list to be empty.

**Comment by sg3-141-592** [comment]
I see.

If you F-12 open Developer Tools in your browser and have a look at the Network Traffic does the page make any attempt to access '/static/data.json'?

And how are the contents of your data.json formatted? I just used the example in their [README.md](https://github.com/lespoupeesrusses/summernote-list-of-links/blob/master/README.md) like below.
```
[
   ["http://www.google.fr", "Google"],
   ["http://www.facebook.com", "Facebook"]
]
```

**Comment by jacopsd** [comment]
I stepped through the js code and the variable options.listOfLinks is undefined.
So the listURL is not used. Hence there is no request to the data.json file (cross checked that as well)

```
  $.extend($.summernote.plugins, {
        'list-of-links': function(context) {
            var self = this,
                ui = $.summernote.ui,
                $editor = context.layoutInfo.editor,
                options = context.options,
                listUrl,
                dialogTitle;

            if (options.listOfLinks !== undefined) {
                listUrl = options.listOfLinks.listUrl;
                dialogTitle = options.listOfLinks.title;
            }
```

**Comment by sg3-141-592** [comment]
I've just noticed, my list of links is working fine when its being served up through an iframe, but its not working on the inplace.

It isn't until I added the extension to the header of my page that the inplace version started working.
```
<script type="text/javascript" src="/static/summernote/summernote-list-of-links.js"></script>
```

My branch trying stuff out is at [https://github.com/sg3-141-592/django-summernote/tree/listoflinks](https://github.com/sg3-141-592/django-summernote/tree/listoflinks) and both the iframe and inplace versions are working for my latest testing.

I'll have to have a better look when I get a chance to see if this is the right behaviour.

**Comment by lqez** [comment]
I tested it as same as @sg3-141-592 did above, it worked well in both types without any custom modification.

```python
# settings.py
SUMMERNOTE_CONFIG = {                                                                                  
    ...
    'summernote': {                                                                                    
        'toolbar': [                                                                                   
            ['insert', ['list-of-links']],                                                             
        ],                                                                                             
       'listOfLinks': {                                                                                
           'listUrl': '/static/data.json',                                                             
        },                                                                                             
    },                                                                                                 
    'js': (                                                                                            
        '/static/summernote-list-of-links.js',                                                         
    ),                                                                                                 
    'js_for_inplace': (                                                                                
        '/static/summernote-list-of-links.js',                                                         
    ),
    ...
}
```
