### ISSUE TITLE
Travis CI job is failing for Python 3.4

### ISSUE THREAD

**Issue by sg3-141-592** [summernote/django-summernote#388]
As part of working a separate Pull Request #387 I noticed that the CI job is failing for Python 3.4.

```
PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8
The command "pip install -q -U pip tox tox-travis python-coveralls" failed and exited with 1 during .
```

I broke down the pip install into the separate installs to see which particular library it was that was causing the error (see [Job #1.2 - sg3-141-592/django-summernote](https://travis-ci.com/sg3-141-592/django-summernote/jobs/282625987)) and its **python-coveralls**. Specifically when it tries to install **PyYAML**.

Looking at the python-coveralls pypi, their latest release version 2.9.3 does not support Python 3.4. The last version that claims to support Python 3.4 is 2.9.1. I tried running the pipeline again with that specific version (see [Job #2.2 - sg3-141-592/django-summernote](https://travis-ci.com/sg3-141-592/django-summernote/jobs/282627367)) and I got the same error. The 2.9.1 version of python-coveralls [setup.py](https://github.com/z4r/python-coveralls/blob/master/setup.py) does not specify any versions for the dependencies. It always tries to install the latest PyYAML when you try and pull down the library. And the latest PyYAML doesn't support Python 3.4. Its very new (6th of January) so it hasn't been an issue for long.

I finally re-ran the CI job specifying a version of PyYAML and the Python 3.4 job started working again (see [Build #3](https://travis-ci.com/sg3-141-592/django-summernote/builds/147050819)).

There's lots to consider around Python 3.4 so I'll leave it with you guys, but I thought I should raise what I found and see how you best want to proceed.

**Comment by lqez** [comment]
Thanks, I just dropped Python 3.4.
https://github.com/summernote/django-summernote/commit/4b32d5b2c96a2c1900c48357f2dfb50aa30d9a12
