### ISSUE TITLE
Injection Vulnerability

### ISSUE THREAD

**Issue by campfireman** [summernote/django-summernote#391]
Thanks for creating this app, you saved me a good chunk of work! I just wanted to share a concern. Maybe I'm preaching to the converted, but there is no sanitzation done on the content.

This is of course not a competence this app needs to have but WYSIWYG editors often will be used to display HTML content created by users. To make this work you can of course turn off escaping (like i did):
`{{ content|safe }}`
And hooray it works. If you're a naive dev like me you expose yourself to great problems. 
`<script>alert('hacked')</script>`
Maybe you could add a warning to the docs that sanitization needs to be done?

Something like this could be an option:
[https://github.com/mozilla/bleach](url)

**Comment by campfireman** [comment]
This is how I solved it.
`
import bleach
from django import forms

from django_summernote.widgets import SummernoteWidget

ALLOWED_TAGS = [
    'a', 'div', 'p', 'span', 'img', 'em', 'i', 'li', 'ol', 'ul', 'strong', 'br',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'table', 'tbody', 'thead', 'tr', 'td',
    'abbr', 'acronym', 'b', 'blockquote', 'code', 'strike', 'u', 'sup', 'sub',
]

STYLES = [
    'background-color', 'font-size', 'line-height', 'color', 'font-family'
]

ATTRIBUTES = {
    '*': ['style', 'align', 'title', ],
    'a': ['href', ],
}


class HTMLField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(HTMLField, self).__init__(*args, **kwargs)
        self.widget = SummernoteWidget()

    def to_python(self, value):
        value = super(HTMLField, self).to_python(value)
        return bleach.clean(
            value, tags=ALLOWED_TAGS, attributes=ATTRIBUTES, styles=STYLES)

`

**Comment by lqez** [comment]
Thanks @campfireman ! Could you make a patch for this?
This should be very helpful for other django-summernote users.

**Comment by campfireman** [comment]
I created a pull request:
https://github.com/summernote/django-summernote/pull/396

I made quite some changes, I am open to any criticism!

**Comment by lqez** [comment]
Closed by #396
