### ISSUE TITLE
How to set editor's content

### ISSUE THREAD

**Issue by calicant** [summernote/django-summernote#394]
Is there a way to set editor content?
I'm using IFRAME in admin.
Something like: 

$("#summernote").summernote("code", "foo");

Thanks,

Luca

**Comment by lqez** [comment]
If we would like to set a content before editing it, place a text before initiating it.
Or if you're using a Form or a ModelForm, then just set the default value.

```html
<div id="summernote"><p>foo</p></div>
```
```javascript
$('#summernote').summernote();
```

```python
class Post(models.Model):
    title = models.CharField(max_length=255, help_text="Title of blog posting")
    body = models.TextField(blank=True, null=True, default="<p>foo</p>")
```
