### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by Letme** [summernote/django-summernote#397]
Would it be possible to change img (and video stuff) to amp styled `amp-img`  easily? AMP images also need width/height defined and layout parameters which then helps make responsive webpages. I seen that width solution here ends up in style, but since I want layout in, it will require some code modifications.

Anyway question first is: Is AMP support acceptable?
Second question: Is it easily done (by Django newbie) and if you point me where to look, or I rather leave it to someone faster/better?

**Comment by lqez** [comment]
Thank you for using Summernote and django-summernote.
Below part is the code for image uploading. You can modify it by overriding template.
https://docs.djangoproject.com/en/3.0/howto/overriding-templates/

https://github.com/summernote/django-summernote/blob/c3cbb00f19db67aee466c435d076c5390236fb73/django_summernote/templates/django_summernote/widget_common.html#L93-L125

Or, creating a new summernote plugin for AMP support can be another option.
https://summernote.org/plugins
