### ISSUE TITLE
Add Button for Inserting Code Snippets, and Enable Markdown in Editor?

### ISSUE THREAD

**Issue by jaradc** [summernote/django-summernote#398]
![markdown-possible](https://user-images.githubusercontent.com/12854767/80287299-a7daf980-86e5-11ea-9e3b-97e940c1c3cf.png)

I have looked all over Github for answers to these questions but maybe I haven't found it yet.

 1. How do I add a dedicated button for inserting code snippets exactly like there is here on GitHub?
 2. How do I allow for markdown in the SummerNote editor? Specifically, I want to use ` characters and the standard # (basically just like here on GitHub).

Can I achieve this with SummerNote? Is it a plugin? I've already added 'pre' tag to my `styleTags` but I want a dedicated button that's visible for inserting code snippets.

**Comment by lqez** [comment]
Yes you can add customized buttons by plugins.
How to make a plugin: https://summernote.org/plugins
Plugin list: https://github.com/summernote/awesome-summernote

But Markdown support is not an easy issue and we do not have a plan to add it now.
