### ISSUE TITLE
How do I change the font size and color ? 

### ISSUE THREAD

**Issue by AaronMcPoland** [summernote/django-summernote#399]

**Comment by dduraipandian** [comment]
```javascript
jQuery(window).on("load", function(){
    setTimeout(function () {
        $('#summernote').summernote('fontSize', 18);
    }, 2000);
});
```

update the javascript path in summernote config.

```python
SUMMERNOTE_CONFIG = {
    'js': ('/static/app/js/sm.js',),
}
```

Hope this helps.!

**Comment by AaronMcPoland** [comment]
> ```js
> jQuery(window).on("load", function(){
>     setTimeout(function () {
>         $('#summernote').summernote('fontSize', 18);
>     }, 2000);
> });
> ```
> 
> update the javascript path in summernote config.
> 
> ```python
> SUMMERNOTE_CONFIG = {
>     'js': ('/static/app/js/sm.js',),
> }
> ```
> 
> Hope this helps.!

That worked great, thanks. Although when I try to add more than one like below:
jQuery(window).on("load", function(){
    setTimeout(function () {
        $('#summernote').summernote('fontSize' , 50);
        $('#summernote').summernote('foreColor' , 'rgb(89, 89, 89)');
        $('#summernote').summernote('foreName' , 'Lato');
    }, 2000);
});
 when I delete it, it  wipes all the style expect the first one, is there a way to have it like :$('#summernote').summernote('fontSize', 18 & 'fontName' , 'Lato' & 'fontColor', 'blue');

**Comment by dduraipandian** [comment]
Is that fontName or foreName? If that is foreNmae, can you change and try?

**Comment by lqez** [comment]
Thank you @dduraipandian !
This is not an issue of django-summernote. So I'm closing this.
If you have any question of the editor itself, please visit https://github.com/summernote/summernote

**Comment by qpxltin972651411** [comment]
### 123
