### ISSUE TITLE
Issue with embeded tweet

### ISSUE THREAD

**Issue by nordbit** [summernote/django-summernote#40]
I'm not sure, is it a summernote issue, but after embeding Tweet from twitter.com in "source html" mode of summernote, after saving js from tw.com is parsed to string and some parts of embeded Tweet code removed.

From pure twitter.com code:

```
<blockquote class="twitter-tweet" lang="pl"><p>Jakże chciałbym widzieć, że wszyscy mają godną pracę. To podstawowa sprawa w perspektywie ludzkiej godności.</p>&mdash; Papież Franciszek (@Pontifex_pl) <a href="https://twitter.com/Pontifex_pl/statuses/481367134899941378">czerwiec 24, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

to:

```
<iframe data-original-title="Embedded Tweet" title="" style="display: block; max-width: 99%; min-width: 220px; padding: 0px; border-radius: 5px; margin: 10px 0px; border-width: 1px; border-style: solid; border-color: rgb(238, 238, 238) rgb(221, 221, 221) rgb(187, 187, 187); -moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none; box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.15); position: static; visibility: visible; width: 500px;" class="twitter-tweet twitter-tweet-rendered" allowtransparency="true" scrolling="no" id="twitter-widget-0" frameborder="0" height="360"></iframe>
<script async="" src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

Removing django-summernote as editor in model and pasting pure HTML code works and Tweet is displaying corretly, so it in not a issue with my app

**Comment by pistatium** [comment]
I met with the issue of implantation of Tweet in the same way, too.
When I performed pasting up in CodeView, I want to delete the line of the following scripts automatically, but how should it come true?

__Paste it__
```
<blockquote class="twitter-tweet" data-lang="ja"><p lang="en" dir="ltr">Can&#39;t pop, won&#39;t pop🎈<a href="https://t.co/HDSjpxYHqy">https://t.co/HDSjpxYHqy</a><a href="https://t.co/EI4FIBlXLF">https://t.co/EI4FIBlXLF</a></p>&mdash; Twitter (@twitter) <a href="https://twitter.com/twitter/status/709518317401190400">2016年3月14日</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

__Want to delete automatically__
```
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

I am very happy if you help me.

**Comment by reriveroc** [comment]
@nordbit Hi!
On summernote.js search the line:
`$editable.html(dom.html($note) || dom.emptyPara);`

and replace it with:
`var str = dom.html($note) || dom.emptyPara;`
`str = str.replace('<script>', '<scriptfalse>');`
`str = str.replace('<script ', '<scriptfalse ');`
`str = str.replace('</script>', '</scriptfalse>');`
`$editable.html(str);`

And also search the line:
`$note.val(context.invoke('code'));`

and replace it with:
`var str = context.invoke('code');`
`str = str.replace('<scriptfalse>', '<script>');`
`str = str.replace('<scriptfalse ', '<script ');`
`str = str.replace('</scriptfalse>', '</script>');`
`$note.val(str);`
