### ISSUE TITLE
Reverse for 'django_summernote-upload_attachment' not found. 

### ISSUE THREAD

**Issue by lguariento** [summernote/django-summernote#400]
Hello,

I just installed django_summernote in my project and followed all the instructions in the readme. I get this:

`Reverse for 'django_summernote-upload_attachment' not found. 'django_summernote-upload_attachment' is not a valid view function or pattern name.`

This is my forms.py:

```
class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('image', 'short_biography', 'contact')

    def __init__(self, *args, **kwargs):

        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['short_biography'] = forms.CharField(widget=SummernoteWidget())  
```

What does it mean? I'm on python 3.8.2, django-summernote-0.8.11.6, Django 3.0.6.

Thanks.

**Comment by lguariento** [comment]
PS: even disabling attachments altogether with

```
SUMMERNOTE_CONFIG = {
    'disable_attachment': True,
    }
```

I still get the same issue.

**Comment by OttawaSTEM** [comment]
You need to add this to urls.py
 path('summernote/', include('django_summernote.urls')),

**Comment by Nitin-Panwar** [comment]
Thanks @OttawaSTEM, it is working now.
