### ISSUE TITLE
How can I disable the "original size" in popover ?

### ISSUE THREAD

**Issue by DamouEf** [summernote/django-summernote#401]
![image](https://user-images.githubusercontent.com/44479424/82153102-c1dfa600-9865-11ea-9bf5-bb6d9b30bfaa.png)

**Comment by lqez** [comment]
You can customize it by Summernote options.
e.g.)

```python
SUMMERNOTE_CONFIG = {
    ...
    'summernote': {
        'popover': {
            'image': [
                ['resize', ['resizeFull', 'resizeHalf', 'resizeQuarter']],
                ['float', ['floatLeft', 'floatRight', 'floatNone']],
                ['remove', ['removeMedia']],
            ],
        },
    },
    ...
}
```

<img width="351" alt="Screen Shot 2020-05-22 at 4 47 53 PM" src="https://user-images.githubusercontent.com/579366/82644397-3478c900-9c4c-11ea-8773-baf162483bfc.png">
