### ISSUE TITLE
Original Size for images no longer available

### ISSUE THREAD

**Issue by jasonhoward64** [summernote/django-summernote#406]
Latest copy of django-summernote. Original Size for image is missing. This should be to the right of the 25% option.

![image](https://user-images.githubusercontent.com/35666637/85731205-8c757600-b6b7-11ea-864c-fb8f6614b673.png)

**Comment by lqez** [comment]
The latest Summernote has a button for ‘Original Size’. (will be shipped with the latest django-summernote)
![image](https://user-images.githubusercontent.com/579366/107791743-a2938c00-6d97-11eb-86ce-09c5f9792121.png)
