### ISSUE TITLE
i know its a silly question, but will summernote work properly when viewed from mobile browser

### ISSUE THREAD

**Issue by anshuUnity** [summernote/django-summernote#413]
i know its a silly question, but will summernote work properly when viewed from mobile browser.

Moreover, i cannot see my summernote widget when deployed, on local machine it worked perfectly well. 
I have deployed my site on pythonanywhere.com. 
![Screenshot (53)](https://user-images.githubusercontent.com/64951054/88402532-e0739780-cde8-11ea-8cf8-8264e43625f4.png)

in this image description field has summernote widget but it is not showing neither in adminpage nor in the form.

**Comment by KimSJ** [comment]
did you remember to collectstatic?

**Comment by lqez** [comment]
Summernote does not support mobile browsers as well as desktop. (But can be used)
As @KimSJ  said, you have to run `collectstatic` command before deploying it.
