### ISSUE TITLE
Error when loading multiple instances at the same time: NameError: name 'config' is not defined

### ISSUE THREAD

**Issue by steffres** [summernote/django-summernote#418]
In our setup, we initialize multiple instances (6-8) of django-summernote's `SummernoteTextFormField` at the same time. Often this crashes, unfortunately not in a predictable or reproducable manner with the error: `NameError: name 'config' is not defined` at this line: https://github.com/summernote/django-summernote/blob/master/django_summernote/views.py#L34

Since my debugger would not stop at this code segment, I put print statements in there and saw that they were called in a non-sequential way. This means that the execution of the `__init__` method is done concurrently and so I assume that there is some kind of race condition somewhere responsible for ovewriting or deleting the config reference, which then results in the error I see.

I could however circumvent this, by putting one line into the beginning of the `__init__` method where I load the global reference to `config` into a temporary variable `config_tmp` right away, and then replaced all other occurences of `config` with this `config_tmp`. Then the NameError did not occur anymore. 

So I assume that the temporary variable stores whatever the 'global' variable `config` is referencing, and by this keeps it from being deleted or overwritten.

My modified `__init__` method looks like this:

```
    @using_config
    def __init__(self):
        config_tmp = config # <- Insertion of temporary variable

        super(SummernoteEditor, self).__init__()

        static_default_css = tuple(static(x) for x in config_tmp['default_css'])
        static_default_js = tuple(static(x) for x in config_tmp['default_js'])
        self.css = \
            config_tmp['base_css'] \
            + (config_tmp['codemirror_css'] if has_codemirror_config() else ()) \
            + static_default_css \
            + config_tmp['css']

        self.js = \
            config_tmp['base_js'] \
            + (config_tmp['codemirror_js'] if has_codemirror_config() else ()) \
            + static_default_js \
            + config_tmp['js']
```

Whatever the deeper lying cause of this I can not tell, not even if it might be actually due to our setup and not due to django-summernot itself. For this our setup involves:
* Django 2.1.9
* django-crispy-forms==1.7.2 (where the django-summernot widgets are integrated into)
* django_summernote.fields.SummernoteTextFormField

Just thought I'd document it here, in case it might be due to django-summernote or someone else encounters the same problem with a similiar setup.

**Comment by chapayevdauren** [comment]
@steffres I also see this error from time to time

**Comment by franciscosucre** [comment]
I have this error after deploying to AWS
