### ISSUE TITLE
Doesn't render content properly 

### ISSUE THREAD

**Issue by saileshkush95** [summernote/django-summernote#424]
This is working fine with django admin. But when i render content in frontend end. syntax is some thing like this
`{{ content|safe }}`

Every thing is rendering properly except blockquote and code. All the blockquote and code are render as a normal text. Do I also need to add somethings in the frontend too.

**Comment by lqez** [comment]
Thank you for using Summernote.
Check CSS (computed styles) on your page. Summernote itself does not affect styles on your pages.
It might need to add styles for `blockquote` and `code` tags.
