### ISSUE TITLE
"'disable_attachment': True" should hide the Attachments model in admin

### ISSUE THREAD

**Issue by KimSJ** [summernote/django-summernote#425]
Adding
```
SUMMERNOTE_CONFIG = {
...
    'disable_attachment': True,
}
```
still leaves the Attachments model visible in admin.

Arguably, the Attachments model should never have been created in the database in the first place!

See also #329

**Comment by lqez** [comment]
Sounds reasonable. :+1:

**Comment by lqez** [comment]
Fixed https://github.com/summernote/django-summernote/commits/main
