### ISSUE TITLE
Font sizes list 

### ISSUE THREAD

**Issue by baal130** [summernote/django-summernote#428]
If sumernote used with django can't change fontsizes list. Tried with config 
SUMMERNOTE_CONFIG = {
 'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
  'fontSizes': ['8', '9', '10', '13', '12', '14', '18', '24', '36'],    

}
And with jquery
 $('#summernote').summernote({fontSizes: ['8', '9', '10', '11', '12',  '150']})

How this should be handled?

**Comment by lqez** [comment]
You also have to put `fontsize` into `toolbar`.
e.g.) 
```
'toolbar': [
    ['style', ['style']],
    ['font', ['fontsize', 'bold', 'italic', 'clear', ]],
    ['color', ['forecolor', 'backcolor', ]],
    ['misc', ['picture', 'fullscreen', 'codeview', 'print', 'help', ]],
],
```
