### ISSUE TITLE
Use Imgur for image storage

### ISSUE THREAD

**Issue by Zackaryia** [summernote/django-summernote#430]
Is it possible to modify the current models and stuff to use Imgur for file storage instead of needing to get a s3 container or something like that.

**Comment by Zackaryia** [comment]
[https://apidocs.imgur.com/](https://apidocs.imgur.com/)

**Comment by Zackaryia** [comment]
https://github.com/Imgur/imgurpython

**Comment by Zackaryia** [comment]
From what i understand all you need to do is change the save function add a few settings and change the url

**Comment by Zackaryia** [comment]
This would be amazing for someone who wants to use heroku for free hosting something like mongodb for 1 gigabyte of database storage and imgur for near unlimited image storage so someone could have a blog and it would only cost them the domain name (plus heroku hobbist but im sure theres a way to get arround that.)

**Comment by lqez** [comment]
Sounds good. It could be done by using imgur as storage of django. e.g. https://github.com/preetamherald/django-imgur
