### ISSUE TITLE
Adding js for plugins is not working properly

### ISSUE THREAD

**Issue by saileshkush95** [summernote/django-summernote#436]
I'm trying to integrate on plugins but js is not loading properly.
plugins:=> https://github.com/pHAlkaline/summernote-plugins/tree/master/plugins/nugget

![Screenshot from 2021-01-27 17-45-30](https://user-images.githubusercontent.com/28560875/105988286-83260f00-60c7-11eb-9b31-825fbaa207ac.png)

Error in console
![Screenshot from 2021-01-27 17-47-38](https://user-images.githubusercontent.com/28560875/105988473-c6807d80-60c7-11eb-9984-696e87633338.png)

**Comment by lqez** [comment]
`Unexpected token '<'` errors are usually caused by wrong static file settings. Please check `summernote_plugins.js` was properly downloaded (by clicking the filename on the above screenshot).
