### ISSUE TITLE
django.conf.urls.url() is deprecated in favor of django.urls.re_path()

### ISSUE THREAD

**Issue by ncampuzano** [summernote/django-summernote#441]
In the new versions of Django (3.1.X), the url() is deprecated and now the idea is to use re_path(). If you can update the project for this new standard will be awesome. 

More information: 
https://docs.djangoproject.com/en/3.1/releases/3.1/#id2

**Comment by lqez** [comment]
Thank you, @ncampuzano !
I just noticed it only a few days ago. Could you make a pull request for this?
