### ISSUE TITLE
Any plans for new version?

### ISSUE THREAD

**Issue by ulgens** [summernote/django-summernote#447]
Hey everyone,

As far as I can see, this package is still getting updated. But the latest version is released on 23 Dec 2019, it's more than a year. Is there any plan to release a new one? If so, do you guys need any help with it? If not, can you please release one?

Thanks a lot.

**Comment by ulgens** [comment]
Special ping to @lqez :wave:

**Comment by dfrankow** [comment]
Thanks for your work on this project. I am also interested in the answer to this question.

**Comment by kevinmarsh** [comment]
Just to bump this again, with [Django 4.0 alpha 1](https://www.djangoproject.com/weblog/2021/sep/21/django-40-alpha-1-released/) being released (and final version scheduled for December 6th), it'd be good to get a new release of `django-sumernote` out which is compatible with modern Django versions. eg. the issues described in #449 are no longer `RemovedInDjango40Warning` warnings, but will be proper errors. These have been addressed in `master` [[1]](https://github.com/summernote/django-summernote/commit/0839f58dca921bb0bae787f6aebc71b09032893b), [[2]](https://github.com/summernote/django-summernote/commit/cdf674fc65491c72723d068e72f9ba9f85c5b482) but not in a new release meaning that users of this library are stuck either

1. not upgrading their Django version
2. or having to install `django-summernote` from a non PyPI release
3. or finding an alternative library.

If there's anything blocking the release or you need help with, please share so the community can try and support this project. Thanks

**Comment by dfrankow** [comment]
Well put. Yes, please support users from a PyPi release on modern Django.
