### ISSUE TITLE
TypeError: clean() got an unexpected keyword argument 'styles'

### ISSUE THREAD

**Issue by haradhansharma** [summernote/django-summernote#494]
clean of bleach does not have styles but why it is passing here I do not understand! `return bleach.clean(
            value, tags=ALLOWED_TAGS, attributes=ATTRIBUTES, styles=STYLES)`

Below is the clean of bleach:
`def clean(
    text,
    tags=ALLOWED_TAGS,
    attributes=ALLOWED_ATTRIBUTES,
    protocols=ALLOWED_PROTOCOLS,
    strip=False,
    strip_comments=True,
    css_sanitizer=None,
):`

**Comment by adampei** [comment]
I am using an older version of the bleach library. To resolve the issue, I uninstalled it and then reinstalled version 4.1.0 using the command 
```bash
pip install bleach==4.1.0
```

**Comment by larrybotha** [comment]
An alternative to pinning to an older version of `bleach` is to re-implement the summernote field using bleach's updated API:

```python
import bleach
from bleach.css_sanitizer import CSSSanitizer
from django.forms import fields
from django_summernote import settings as summernote_settings
from django_summernote.widgets import SummernoteWidget


class RichTextField(fields.CharField):
    def __init__(self, *args, **kwargs):
        kwargs.update({"widget": SummernoteWidget()})
        super().__init__(*args, **kwargs)

    def to_python(self, value):
        value = super().to_python(value)

        return bleach.clean(
            value,
            attributes=summernote_settings.ATTRIBUTES,
            css_sanitizer=CSSSanitizer(allowed_css_properties=summernote_settings.STYLES), 
            tags=summernote_settings.ALLOWED_TAGS,
        )
```

Bleach no longer accepts the `style` argument, and instead accepts a `css_sanitizer` argument.

This is most likely what the `SummernoteFormTextField` would like once updated

**Comment by claudep** [comment]
In PR #499, bleach was replaced by nh3.
