### ISSUE TITLE
Cannot upload image in IE8/IE9

### ISSUE THREAD

**Issue by culshaw** [summernote/django-summernote#54]
Trying to upload an image in either IE8 or IE9 gives you error 
"Got an error while uploading images."

Works in IE10 however!

**Comment by oiacrasec** [comment]
@culshaw can you send me please an example? Im getting an AttributeError: 'FileSystemStorage' object has no attribute 'rindex'

**Comment by oiacrasec** [comment]
I resolved my problem. i forgot to include all js =)
