### ISSUE TITLE
drop-down menus isn't working

### ISSUE THREAD

**Issue by yn-coder** [summernote/django-summernote#59]
django-summernote works, but drop-down menus isn't working. Style button and Line height buttons are virible, but doesn't roll out.

Simple buttons are work well.

Options taken from your readme.md. https://github.com/lqez/django-summernote#options
![2014-08-29 12_02_28-example com _ edit org](https://cloud.githubusercontent.com/assets/8451944/4087769/3537f63e-2f53-11e4-9d73-2c75a46eba5a.png)

Example project already use the bootstrap - may be, some conflict?

**Comment by Nithyakumar14** [comment]
Hi everybody
I agree this is bootstrap issue but if "li a" link convert to div tag this problem Solved 
Like:<ul class=dropdown-menu><li><a>test</a></li></ul>
to convert:<ul class=dropdown-menu><li><div>test</div></li></ul>
check it out if not get you let me know i will provide complete solution

Thank you

**Comment by gilgzz18** [comment]
I have the same problem but with bootstrap

NOTE: All buttons work, except those with dropdown menu


Regards,
Gilberto

**Comment by muhannadabbady** [comment]
in the summernote.css
find 
.panel-heading.note-toolbar{padding:0 0 5px 5px;margin:0}
change to 
.panel-heading.note-toolbar{padding:0 0 5px 5px;margin:0;overflow-y: unset;}
