### ISSUE TITLE
Auto clean up the copypasted text?

### ISSUE THREAD

**Issue by yn-coder** [summernote/django-summernote#65]
Can summernote auto cleaning up the copypasted text? Text from buffer can contain formating tags, and I see two ways:

* Clean the resulting html before save it to database, and remove the unsual tags
* Tell to editor to allow only plain text inserting

**Comment by danniranderis** [comment]
+1

**Comment by tanaysoni** [comment]
In my opinion, second option should be good. The paste option should get only plain text without any formatting tags.

**Comment by lqez** [comment]
This is **very** important issue for all wysiwyg users. But it's up to `summernote`, not `django-summernote`. I'm handling similar issues on `summernote`.
Please watch https://github.com/summernote/summernote/issues/1168 .
Thanks!

**Comment by ppython** [comment]
You can achieve this with [summernote 'summernote-cleaner' plugin](https://github.com/StudioJunkyard/summernote-cleaner) :

and an extra summernote config:
```
SUMMERNOTE_CONFIG.update({
    'js': (
        os.path.join(STATIC_URL, '/summernote/summernote-cleaner.js'),
    ),
})
```

**Comment by AlexLinus** [comment]
It doesnt work!
