### ISSUE TITLE
404 Error on TextArea in Admin interface

### ISSUE THREAD

**Issue by kevgathuku** [summernote/django-summernote#67]
I just installed Django summernote (v0.5.15) on a new Django 1.6.7. project. 
I'm using the default settings. 
However the editor is not displayed in the admin interface.

Here is my admin.py
```python
from django.contrib import admin
from django_summernote.admin import SummernoteModelAdmin

# Register your models here.
from models import Post

# Apply summernote to all TextField in model.
class PostAdmin(SummernoteModelAdmin):
	fields = ['title', 'body']

admin.site.register(Post, PostAdmin)
```

The attachments are working just fine.
However I get a 404 error in the TextArea for the url http://localhost:8000/summernote/editor/id_body/
![admin_error](https://cloud.githubusercontent.com/assets/3721994/4807182/a5d4e3f8-5e91-11e4-980e-d526bb7a41ac.JPG)

Would you mind helping out?

**Comment by lqez** [comment]
I'm closing this issue. Please reopen this again if you're still in same problem.

**Comment by pastorenue** [comment]
HI! I have django-summernote installed too with django 1.11,
However the editor is not displayed in the admin interface.

Here is my admin.py
`from django.contrib import admin
from django_summernote.admin import SummernoteModelAdmin
from .models import *
from django.template.defaultfilters import slugify


@admin.register(Entry)
class EntryAdmin(SummernoteModelAdmin):
	summernote_fields = ('content',)
	

	def save_model(self, request, obj, form, change):
		obj.slug = slugify(obj.title)
		super(EntryAdmin, self).save_model(request, obj, form, change)


@admin.register(Author)
class AuthorAdmin(admin.ModelAdmin):
	list_display = ('user', 'name')`

But I get this output on load
![capture](https://user-images.githubusercontent.com/9276129/40189840-ab3fdb70-59fd-11e8-92a1-c8b0cb8d8a58.JPG)
