### ISSUE TITLE
iframe styles incorrect

### ISSUE THREAD

**Issue by melinath** [summernote/django-summernote#71]
![screen shot 2014-11-30 at 8 54 37 pm](https://cloud.githubusercontent.com/assets/299979/5241473/29d4b5ce-78d3-11e4-9332-341b69093e29.png)

The django_summernote styles (which are included in the iframe version) result in the editor div being set to `display: inline-block` - which means that the width of the editor is the width of the toolbar. Removing that, and just using the default summernote styles, results in a full-width editor. Could this please be fixed?

I am using grappelli, but this seems like it would be an issue in any case.

**Comment by lqez** [comment]
@melinath Sorry for that. I added a commit for this - https://github.com/summernote/django-summernote/commit/3c94e7d64eebed6b8c94e3b06effc807d90e8839. Please test it again with 0.6.1.
