### ISSUE TITLE
Security: upload_attachment with @login_required 

### ISSUE THREAD

**Issue by regqueryvalueex** [summernote/django-summernote#74]
Sequrity: I think, developers need to add @login_required decorator before:

https://github.com/summernote/django-summernote/blob/master/django_summernote/views.py#L18
def upload_attachment(request):

Or, maybe, make it optional somwhere in settings.py

**Comment by lqez** [comment]
@regqueryvalueex Oh, looks like it should be.

**Comment by lqez** [comment]
Thanks, I added it https://github.com/summernote/django-summernote/commit/06e619eb90d11768bf4337a10bb4b7f20f7b18fe.
