### ISSUE TITLE
Error in insert images from "select images" button when using diango-summernote

### ISSUE THREAD

**Issue by ghost** [summernote/django-summernote#75]
Hi all.

When I using diango-summernote to insert the images with "select images" button, an error appeared as "Resource interpreted as Image but transferred with MIME type text/html: "http://127.0.0.1:8000/summernote/editor/id_t_r_text/django-summernote/2015-02-01/de52c064-8829-438c-bd00-3615df5fb95d.gif/"."

Can anyone tell me to solve this problem?

Many thanks.

**Comment by lqez** [comment]
Sorry for late answer.
Did you add url for django-summernote? Ref: Step 3 of https://github.com/summernote/django-summernote#setup
