### ISSUE TITLE
Use project's own bootstrap, jquery and fontawesome?

### ISSUE THREAD

**Issue by wryfi** [summernote/django-summernote#77]
My project already uses bootstrap, with custom less styles compiled by django-compressor. It already includes jquery and fontawesome.

Is there some way that I can prevent django-summernote from also loading its own version of these libraries? How do I use my own that are already part of my site?

**Comment by oiacrasec** [comment]
Create your own widget extending SummernoteWidgetBase and remove def media, for example:

import json
from django.conf import settings
from django.template import Context
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe
from django_summernote.widgets import SummernoteWidgetBase


class SummernoteCleanWidget(SummernoteWidgetBase):

    def render(self, name, value, attrs=None):
        attrs_for_textarea = attrs.copy()
        attrs_for_textarea['hidden'] = 'true'
        attrs_for_textarea['id'] += '-textarea'
        html = super(SummernoteCleanWidget, self).render(name, value, attrs_for_textarea)
        html += render_to_string(
            'django_summernote/widget_inplace.html',
            Context(dict({
                'id': attrs['id'].replace('-', '_'),
                'id_src': attrs['id'],
                'value': value if value else '',
                'settings': json.dumps(self.template_contexts()),
                'STATIC_URL': settings.STATIC_URL,
            }))
        )
        return mark_safe(html)

**Comment by okaysimon** [comment]
It seems that css/js files has been written in the template file "widget_iframe_editor.html" and cannot be overridden by SUMMETNOTE_CONFIG settings.

**Comment by getup8** [comment]
This removes those for me if I put this in settings.py (I keep font-awesome css):

```python
SUMMERNOTE_CONFIG = {
    # Set external media files for SummernoteInplaceWidget.
    # !!! Be sure to put {{ form.media }} in template before initiate summernote.
    'inplacewidget_external_css': (
        '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css',
    ),
    'inplacewidget_external_js': (),
}
```

**Comment by lqez** [comment]
Now we support separated include settings for each widget.
