### ISSUE TITLE
The height size is not right with the latest summernote when using inplace widget

### ISSUE THREAD

**Issue by liuhongjiang** [summernote/django-summernote#80]
Using inplace widget, and the default height  480px is used, but after render, the height is set to the editable div, not the whole editor. 
![image](https://cloud.githubusercontent.com/assets/2692065/6849151/571d0e98-d40c-11e4-83cb-871f00faec20.png)

**Comment by liuhongjiang** [comment]
I fixed this problem and it's included in pull request #79 , please check it out.

**Comment by lqez** [comment]
Thanks for your contribution!
