### ISSUE TITLE
Font size issue - Chrome

### ISSUE THREAD

**Issue by catgeek86** [summernote/django-summernote#82]
On Chrome, the font size drop down does not work properly.
It changes the font sizes, regardless of what you select, to 16. 

The font can then be changed back to the original size by using the 'remove font style' button.

The font size works on Firefox and IE

**Comment by lqez** [comment]
Thank you for reporting.
However, `font-size` issues are up to `summernote`, not `django-summernote`. Ref : https://github.com/summernote/summernote/issues?utf8=%E2%9C%93&q=font-size
