### ISSUE TITLE
Font Family Issue

### ISSUE THREAD

**Issue by catgeek86** [summernote/django-summernote#83]
On Chrome only Arial and Courier New show as options (Helvetica is shown as the selected option by default, but does not show up in the drop down options)
 
On Firefox only Arial, Courier New, and Times New Roman show up as options.

On IE there are more font family options available.

**Comment by lqez** [comment]
Thank you for reporting.
However, As same as your previous issue, `font-family` issues are up to `summernote`, not `django-summernote`. Ref : https://github.com/summernote/summernote/issues?utf8=%E2%9C%93&q=font-family
