### ISSUE TITLE
event callbacks is case sensitive

### ISSUE THREAD

**Issue by Catstyle** [summernote/django-summernote#86]
environment:
django 1.7.5
chrome  43.0.2357.65 (64-bit)

just a simple `content = forms.CharField(widget=SummernoteInplaceWidget())`
but when i submitted the form i couldn't received the content data
after some debugging, it turns out that in the templates/django_summernote/widget_inplace.html
the oninit/onblur callbacks should be onInit/onBlur

**Comment by lqez** [comment]
OMG, you're right. And there are several non-backward-compatibility changes in summernote after `0.6.4`. So I'm investigating now. Thank you for reporting.

**Comment by inchis** [comment]
Thanks please let me know what you come up with

**Comment by lqez** [comment]
Thank you guys! I just bumped it to `0.6.7`.
