### ISSUE TITLE
django summernote not working properly

### ISSUE THREAD

**Issue by inchis** [summernote/django-summernote#88]
I am having 2 issues with django summernote

everything is setup as it should be but it generally doesn't update the form [post data returns an empty string

1. Post data empty

2. images do upload to server but they wont updata on the text area as they should so the image upload does not return results which is the main reason I opted for summernote

And the other thing is I am using django 1.3, but I soughted out compatibility issues where there was a need

**Comment by inchis** [comment]
What do you mean "BUG",

**Comment by lqez** [comment]
I just released `0.6.7` with fixes of these issues. Thank you for reporting!

**Comment by inchis** [comment]
Can I download that or is it possible that you can email me a copy to
carlosnkosikhona@gmail.com

**Comment by lqez** [comment]
You can install it via `pip install django-summernote==0.6.7` or download it from https://github.com/summernote/django-summernote/releases/tag/0.6.7 .

**Comment by inchis** [comment]
sorry got it, its work fine great work much appreciated

**Comment by dobestan** [comment]
thanks!
