### ISSUE TITLE
Q: mixing modelForm and model, problem with Images

### ISSUE THREAD

**Issue by hemulin** [summernote/django-summernote#89]
(noob warning)

I wanted to use summernote within a model but without using the default modelForm.
I ended up mixing the two like this (can't have widgets on model field...):
```
# In models I have
class Article(models.Model):
  """Represents a wiki article"""
  title = models.CharField(max_length=100)
  slug = models.SlugField(max_length=50, unique=True)
  text = models.TextField()
  author = models.ForeignKey(User)
  created_on = models.DateTimeField(auto_now_add=True)
  objects = models.Manager()
  tags = TaggableManager(through=TaggedArticle)

class ArticleForm(forms.ModelForm):
  class Meta:
    model = Article
    fields = ['text']
    widgets = {
            'text': SummernoteWidget(),
          }
```
After having the right display while serving the template, I attempt to save the Article like this:
```
# in views, a part of the saving method:
    form = ArticleForm(request.POST or None)
    if form.is_valid():
        #import pdb; pdb.set_trace()
        article = Article()
        article.text = form.cleaned_data['text'] # THIS IS MY HACKISH WAY OF FETCHING THE CONTENT
        article.author = request.user
        article.title = request.POST['title']
        if request.POST.has_key('tags'): #add relevant ones
          article_tags = request.POST.getlist('tags')
          article_tags = [tag for tag in user_tags]
          article.tags.add(*article_tags)
        article.save()
        return HttpResponse("Article saved successfully")
```
1) I have everything configured (MEDIA_ROOT, MEDIA_URL, summernote url as described in the setup)
2) The widget is displayed well within iframe
3) When uploading an image I get the "mime interpreted text blah blah blah" error
4) After saving, when displaying the article, the text is displayed well with all the markup but no image is displayed

Finally, how would you suggest me to solve the problem and having the images uploaded and displayed correctly in the resulted article text?

cheers and thanks for this great app.

**Comment by hemulin** [comment]
Quick update, while reviewing changes in git, I've noticed that the uploaded images appear in django-summernote/"date-of-upload"/"some-hash-string"."image-extension"

Perhaps this information will help in identifying/resolving the problem.

**Comment by hemulin** [comment]
Yet another update on the situation:
URLs works well. Local files not. Similar to [that question](http://stackoverflow.com/questions/26789826/django-summernote-image-upload).

![This is a screenshot](http://i.imgur.com/MmvfWME.png) Above is a screenshot of the network tab after loading a local file to the iframe widget

![image on server](http://i.imgur.com/OoI48GP.png) As you can see, the image is accessible on the server while browsing through the media url.

What am I doing wrong?

**Comment by andyfuse** [comment]
I overwrote next things in my settings.py:

SUMMERNOTE_CONFIG = {
    ....
    'attachment_upload_to': upload_to,
   ....
}

def upload_to(instance,filename):
.... return os.path.join('django-summernote', filename)

and my MEDIA_ROOT and MEDIA_URL variables are:

MEDIA_ROOT = 'mine/static/mysite/media'
MEDIA_URL = '/media/'

next step I made was adding one string to urlpattern:

urlpatterns = patterns('',
 ....
) +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

and now everything works fine for me.

**Comment by hemulin** [comment]
Thank you very much. It worked.

**Comment by lqez** [comment]
Sorry for late replying. Thank you @andyfuse and @hemulin.
