### ISSUE TITLE
Error in plugin summernote-ext-video.js non-existing function getEditor()

### ISSUE THREAD

**Issue by hemulin** [summernote/django-summernote#90]
File: django_summernote/static/django_summernote/plugin/summernote-ext-video.js
Change line #4: var editor = $.summernote.eventHandler.getEditor();
To: var editor = $.summernote.eventHandler.getModule();

**Comment by lqez** [comment]
Ooops, I forgot to update plugin with newer summernote.
I released `0.6.8` with newer plugins.
