### ISSUE TITLE
How to override Textareas for Admin Forms?

### ISSUE THREAD

**Issue by wshayes** [summernote/django-summernote#91]
I'm new to Django and trying to figure out how to override all of my textarea fields in my Admin Model Forms. I saw this in the django-summernote docs:

     from django_summernote.admin import SummernoteModelAdmin

      # Apply summernote to all TextField in model.
      class SomeModelAdmin(SummernoteModelAdmin):  # instead of ModelAdmin
      ...
But I'm not sure what should replace the ellipses. Is there a way to do this for all textareas in Admin at once or does this need to be applied to each Model?

I posted this question on StackOverflow but didn't get any responses:  http://stackoverflow.com/questions/30339346/django-summernote-how-do-i-override-the-admin-form-textareas-with-the-summernot  

Happy to post the answer there if someone can help me with this.

**Comment by wshayes** [comment]
Finally figured out the problem I had.

All I needed to do was add the following to my admin.py script:

    from django_summernote.admin import SummernoteModelAdmin

    class QuestionAdmin(SummernoteModelAdmin):
        pass

    admin.site.register(Question, QuestionAdmin)

This will override the forms to add Summernote in place of the Textfields and register the new Admin form.  I was missing adding QuestionAdmin to the admin.site.register command.

**Comment by lqez** [comment]
@wshayes Yeap, you've got it.
