### ISSUE TITLE
Pasting in FireFox/Safari removes current items

### ISSUE THREAD

**Issue by jtesch** [summernote/django-summernote#92]
Appending to the text in the editor using keyboard shortcut or the menu removes the current text in FireFox and Safari. It works fine in Chrome.
I am using the summernote widget in the admin interface for a model.

**Comment by lqez** [comment]
Did you mean `Ctrl + V`, `Cmd + V` or context menu (by right clicking)?

**Comment by jtesch** [comment]
Yes, I retested this as well and it appears that it is working now.

**Comment by lqez** [comment]
@jtesch cool
