### ISSUE TITLE
In-place widget doesn't support page-bottom javascript loading

### ISSUE THREAD

**Issue by jaddison** [summernote/django-summernote#94]
The in-place widget template assumes jQuery is loaded at the top of the page - at least from what I can tell. For page load timing/speed reasons, I like to load all javascript at the bottom of the page, but this results in javascript errors with summernote.

I've hacked a few javascript changes to get around this - here's a git diff of the changes I've done to `widget_inplace.html` (note the + and - lines):

``` javascript
 <div id='{{ id_src }}'>{{ value|safe }}</div>
 <script>
+var summernote_inplace_initializers = summernote_inplace_initializers || [];
+summernote_inplace_initializers.push(function() {
-$(function() {
     var {{ id }}_textarea = window.document.getElementById('{{ id_src }}-textarea');
     var {{ id }}_src = window.document.getElementById('{{ id_src }}');
```

And then in your own script at the bottom of the page where you're using the in-place widget, after all javascript files have been loaded:

``` javascript
while (summernote_inplace_initializers.length){
    summernote_inplace_initializers.shift().call();
}
```

I'd prefer not to have to do this modification, if you guys can think of a better way around this?

**Comment by lqez** [comment]
Thank you for reporting.
I've received this issue from coworkers, and this must be reformed.

**Comment by the4thv** [comment]
I think this is same problem I've experienced, trying to use SummernoteInplaceWidget() with crispy-forms (1.4.0) and Django 1.8.2. The Summernote object doesn't render at all and looking for javascript errrors, there is 'Uncaught ReferenceError: $ is not defined'. 

It is trying to add the javascript directly under the form textarea.

By the way, thanks for Django-summernote, it's really useful!

**Comment by danniranderis** [comment]
+1

**Comment by lupinia** [comment]
+1

**Comment by cdrice** [comment]
+1
This bit me during my own integration.  I tried the workaround described by @jaddison but then ran into the same error as described in #144.  I spent a while trying to make it happy bottom-loading, but my js-fu was not strong enough.  I finally gave up and moved my jquery loading to head on pages I need the inplace widget.

**Comment by lqez** [comment]
I made a PR for this : https://github.com/summernote/django-summernote/pull/21818
Could you see it whether it can properly work or not?
