### ISSUE TITLE
Summernote Code View can't work when I use SyntaxHighLighter

### ISSUE THREAD

**Issue by tmacjx** [summernote/django-summernote#95]
I'm using Summernote editor in my django-project.
when I add some code in it,I found all code in one line.
Could Anyone help me?
Or same problem?

![2015-07-07 11 45 03](https://cloud.githubusercontent.com/assets/11555807/8538417/814e14b8-249e-11e5-8980-bb4fbe13a516.png)
![2015-07-07 11 45 22](https://cloud.githubusercontent.com/assets/11555807/8538408/5dce6b5a-249e-11e5-8328-8fbad347f1b7.png)
![2015-07-07 11 45 41](https://cloud.githubusercontent.com/assets/11555807/8538428/a1408de6-249e-11e5-9c74-32bf163597f9.png)

**Comment by lqez** [comment]
It looks like you should set `prettifyHtml` as `false`. See https://github.com/summernote/summernote/pull/791

**Comment by tmacjx** [comment]
![2015-07-08 10 43 27](https://cloud.githubusercontent.com/assets/11555807/8561898/42b89474-255e-11e5-88b0-0a4dd0d1f1ee.png)
I hava add  'prettifyHtml': False,  in  django-summernote    settings.py
But problem can't solve still.

**Comment by tmacjx** [comment]
SETTINGS_DEFAULT = {
    'iframe': True,
    'airMode': False,
    'styleWithSpan': True,
    'direction': 'ltr',
    'empty': ('<p><br/></p>', '<p><br></p>'),

    'width': 720,
    'height': 480,
    'toolbar': [
        ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'superscript', 'subscript',
                  'strikethrough', 'clear']],
        ['fontname', ['fontname']],
        ['fontsize', ['fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['height', ['height']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video', 'hr']],
        ['view', ['fullscreen', 'codeview']],
        ['help', ['help']],
    ],
    'prettifyHtml': False, 
    'lang':'zh-CN' ,
    'lang_matches': {
        'ar': 'ar-AR',
        'ca': 'ca-ES',
        'cs': 'cs-CZ',
        'da': 'da-DK',
        'de': 'de-DE',
        'es': 'es-ES',
        'fa': 'fa-IR',
        'fi': 'fi-FI',
        'fr': 'fr-FR',
        'he': 'he-IL',
        'hu': 'hu-HU',
        'id': 'id-ID',
        'it': 'it-IT',
        'ja': 'ja-JP',
        'ko': 'ko-KR',
        'nb': 'nb-NO',
        'nl': 'nl-NL',
        'pl': 'pl-PL',
        'pt': 'pt-BR',
        'ro': 'ro-RO',
        'ru': 'ru-RU',
        'sk': 'sk-SK',
        'sl': 'sl-SI',
        'sr': 'sr-RS',
        'sv': 'sv-SE',
        'th': 'th-TH',
        'tr': 'tr-TR',
        'uk': 'uk-UA',
        'vi': 'vi-VN',
        'zh': 'zh-CN',
    },
  
    'attachment_upload_to': uploaded_filepath,
    'attachment_storage_class': None,
    'attachment_filesize_limit': 1024 * 1024,
    'attachment_require_authentication': False,

    'inplacewidget_external_css': (
        '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css',
        '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css',
    ),
    'inplacewidget_external_js': (
        '//code.jquery.com/jquery-1.9.1.min.js',
        '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js',
    ),
}

**Comment by tmacjx** [comment]
from django.contrib import admin

from article.models import Author,Tag,Classification,Article
admin.py

# Register your models here.
from django_summernote.admin import SummernoteModelAdmin
admin.site.register(Author)
admin.site.register(Tag)
admin.site.register(Classification)

class ArticleAdmin(SummernoteModelAdmin):
      pass
admin.site.register(Article,ArticleAdmin)

**Comment by lqez** [comment]
Got it. `django-summernote` did not support recently added settings of `summernote`.
I just added support for `prettifyHtml` to `0.6.10`. Please update it.
Thanks.

**Comment by Chayemor** [comment]
I just installed today and I was getting the same problem even **after adding** `prettifyHtml`. Realized then that Codemirror has an option, _lineWrapping_ which is set to **False** by default. So change that to **True**, you are good to go.

setting.py

SUMMERNOTE_CONFIG = {
    'prettifyHtml': False,
    # Codemirror as codeview
    # If any codemirror settings are defined, it will include codemirror files automatically.
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    ),
    'codemirror': {
        'mode' : 'htmlmixed',
        'lineWrapping' : True,
        'lineNumbers': 'true',

        # You have to include theme file in 'css' or 'css_for_inplace' before using it.
        'theme': 'monokai',
    },
}
