### ISSUE TITLE
How to Alias when deploying with wsgi

### ISSUE THREAD

**Issue by dlsrnsi** [summernote/django-summernote#96]
Hi!

I use summernote for some write form.

when I tested it with localhost in my computer, it worked well

But when I deployed with apache2 and mod_wsgi, it doesn't work.

I think it is caused from Alias such as /summernote/ like that.

I tried somthing. such as change it as inplace widget, for add alias for summernote

But these didn't work.

How can I make summernote work?

![default](https://cloud.githubusercontent.com/assets/7012023/8639184/e119fe12-290c-11e5-803f-7200c5414117.JPG)

**Comment by lqez** [comment]
You may need an understanding of handling media and static files.
Please read below documents and set aliases based on your `settings.py`
  - https://docs.djangoproject.com/en/1.8/howto/static-files/
  - http://timmyomahony.com/blog/static-vs-media-and-root-vs-path-in-django/

**Comment by dlsrnsi** [comment]
@lqez Thanks!! It works!!

**Comment by lqez** [comment]
@dlsrnsi oky doky !
